### PR TITLE
Update to new CI Sanity scripts

### PR DESCRIPTION
**Pull request by rahulbatra85**

### CODE REVIEW

**Comment by rahulbatra85** [comment]
retest Ubuntu-sanity please

**Comment by rahulbatra85** [comment]
retest Ubuntu-sanity please

**Comment by rahulbatra85** [comment]
retest Ubuntu-sanity please

**Comment by rahulbatra85** [comment]
retest Ubuntu-GPU-single please

**Review by jayfurmanek — APPROVED** [review]
A couple follow on items to this:
 - let's add a ROCm check for local_config_rocm
 - let's use bazelisk in general now

**Pull request merged**
