### PR TITLE
Proposed perf fix for column reductions

### PR DESCRIPTION
**Pull request by parallelo**
Changed column reduction kernel launch sites to reflect upstream more closely. Biggest change is wrt removing the ROCm-specific ifdefs in LaunchColumnReduction(). ColumnReduceSimpleKernel can be extremely slow in certain cases, and this commit allows for the use of LaunchColumnReduction_LTE16Cols() and LaunchColumnReduction_LTE4096Cols() when extent_y is below 16 or 4096, respectively. 

Note that this commit enables generally what exists already upstream.

### CODE REVIEW

**Comment by parallelo** [comment]
[Issue 330](https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/issues/330) reported approximate perf.  

Pre-PR:  ~2400 sec/epoch (reported by dekken on Vega FE)  
Post-PR:  <200 sec/epoch (self measured on gfx900)

The `python3 test.py` run also appears to be converging.  However, I haven't run the unit tests yet (while wait for CI to finish).

**Comment by parallelo** [comment]
Final comment for the evening, this reduction perf bottleneck also appeared to affect the DeepInterest workload, and I bet there are more.

**Comment by parallelo** [comment]
There are some errors I'm looking into.  Stay tuned..

**Comment by parallelo** [comment]
Some failing unit tests on ROCm:
```
Executed 1067 out of 1067 tests: 1042 tests pass and 25 fail locally.
```
The CUDA build has other unrelated problems -- looks like a regression was added a week or so ago.

**Comment by parallelo** [comment]
Some of the reduction unit tests are failing, even though we're basically reusing existing code on the GPU path.  Currently digging deeper into the details of the failures.

**Comment by parallelo** [comment]
jenkins: retest this please

**Comment by parallelo** [comment]
jenkins: retest this please

**Comment by parallelo** [comment]
jenkins: retest this please

**Comment by whchung** [comment]
jenkins: retest this please

**Comment by whchung** [comment]
@parallelo from CI test log ( http://ml-ci.amd.com:21096/job/tensorflow-upstream-unit-tests/713/console ) it seems there are a couple of unit tests failing potentially due to this PR. Could you help take a look at it?

**Comment by parallelo** [comment]
Yep, I'm already working on it.

**Comment by parallelo** [comment]
Last round of tests showed 25 unit test failures, including some reduction-specific ones.

**Comment by parallelo** [comment]
jenkins: retest this please

**Comment by parallelo** [comment]
Quick update:  Trying to reproduce the 25 unit test failures on my local machine.  I'm attempting to use all of the same (custom) packages/etc as those on our CI runs.  There must be some minor difference that exists on my local machine.  Still looking..

**Comment by whchung** [comment]
/cc @aurotripathy

On LSTM workloads I was expecting this PR bring some perf boost. But it does seem the PR still have some issues which has to be addressed.

**Comment by whchung** [comment]
after #470 this PR actually now becomes trivial. taking it.

**Pull request merged**
