### PR TITLE
Develop upstream sync 241014

### PR DESCRIPTION
**Pull request by draganmladjenovic**

### CODE REVIEW

**Comment by i-chaochen** [comment]
```
[2024-10-14T21:00:43.606Z] ERROR: /root/.cache/bazel/_bazel_root/fbac33eb30dbfb6b11b15a7ff5ac830d/external/local_xla/xla/stream_executor/rocm/BUILD:1075:9: in deps attribute of cc_test rule @local_xla//xla/stream_executor/rocm:rocm_timer_test_gpu_amd_any: Label '@local_xla//xla/stream_executor/gpu:gpu_stream' is duplicated. Since this rule was created by the macro 'xla_test', the error might have been caused by the macro implementation
[2024-10-14T21:00:43.606Z] ERROR: /root/.cache/bazel/_bazel_root/fbac33eb30dbfb6b11b15a7ff5ac830d/external/local_xla/xla/stream_executor/rocm/BUILD:1075:9: Analysis of target '@local_xla//xla/stream_executor/rocm:rocm_timer_test_gpu_amd_any' failed
```

seems the xla/stream_executor/rocm/BUILD files is wrong again....

**Comment by draganmladjenovic** [comment]
Retest non-pip tests please.

**Comment by inemankov** [comment]
Retest gpu-non-pip-multi please

**Comment by inemankov** [comment]
test gpu-non-pip-multi

**Comment by mmakevic-amd** [comment]
retest gpu-pycpp please

**Comment by draganmladjenovic** [comment]
Hallelujah! @i-chaochen It is ready to merge. Thanks @mmakevic-amd on good work on previous ones making this one a breeze.

**Review by i-chaochen — COMMENTED** [review]
@draganmladjenovic  shoule we upstream these fixes to openxla?

**Review by i-chaochen — APPROVED** [review]

**Review by mmakevic-amd — APPROVED** [review]

**Pull request merged**
