### PR TITLE
Populating memory bandwidth information in the DeviceDescription

### PR DESCRIPTION
**Pull request by deven-amd**
Populating memory bandwidth information in the DeviceDescription, using information from the call to hipGetDeviceProperties

/cc @sunway513 @ekuznetsov139

### CODE REVIEW

**Comment by ROCm-Apps-Test** [comment]
Can one of the admins verify this patch?

**Comment by ekuznetsov139** [comment]
I see that it now reports deviceMemoryBandwidth: 450.61GiB/s for MI25, is that the correct value?

**Comment by deven-amd** [comment]
>> I see that it now reports deviceMemoryBandwidth: 450.61GiB/s for MI25, is that the correct value?

Yes, checked it with @sunway513

**Comment by sunway513** [comment]
@deven-amd , I thought we should see:
 2*256*945 = 483.84 GB/s
Which is aligned to the marketing numbers (specification) :
https://www.amd.com/en/products/professional-graphics/instinct-mi25

**Comment by ekuznetsov139** [comment]
Observe that 483.84 is exactly 450.61 * 1.024 * 1.024 * 1.024.

The bandwidth is 450.61 of 1024^3 bytes/s or 483.84 of 10^9 bytes/s. It is calculated by stream_executor as "483 840 000 000" (or so) and then converted into 450.61 for display in tensorflow/core/platform/numbers.cc (function HumanReadableNumBytes()).

**Pull request merged**
