### PR TITLE
Misc terminology change: reinstate tf_cuda_ related symbols

### PR DESCRIPTION
**Pull request by whchung**
For existing build logic in upstream TensorFlow, reinstante tf_cuda_ symbols to
ease maintainence efforts in our downstream fork.

For ROCm-specific tests, use tf_gpu_ symbols.

### CODE REVIEW

**Comment by whchung** [comment]
@parallelo the idea is also the same as #264 and #262 . With this PR merged all the logic in ops / tests / GPU common runtime are more or less aligned with upstream TF with the addition of `TENSORFLOW_USE_ROCM` macro, which will be submitted upstream this week.

@sunway513 I removed one place where we set `-march=haswell`. It's not used in our regular build so I think it shall be fine.

**Comment by sunway513** [comment]
@whchung the changes on `-march=haswell` LGTM.

**Comment by parallelo** [comment]
jenkins:  retest this please

**Comment by parallelo** [comment]
Regarding the AWS instances running out of memory, I believe this is now fixed.  

Here's the current fail list:
```
//tensorflow/python/kernel_tests:cond_v2_test                            [0m[31m[1mFAILED
//tensorflow/python/kernel_tests:cond_v2_test_gpu                        [0m[31m[1mFAILED
//tensorflow/python/kernel_tests:gpu_fusion_ops_test                     [0m[31m[1mFAILED
//tensorflow/python/kernel_tests:gpu_fusion_ops_test_gpu                 [0m[31m[1mFAILED
```
Looks like the two `gpu_fusion_ops_test*` tests are also currently failing on `develop-upstream`.

**Pull request merged**
