### PR TITLE
Fixing certificate not trusted for docker package installation

### PR DESCRIPTION
**Pull request by jerryyin**
Please refer to this [log](http://ml-ci.amd.com:21096/job/develop-upstream-unit-tests/job/tensorflow-upstream-unit-tests-gpu-multi/28/console) for original failure.

### CODE REVIEW

**Comment by jerryyin** [comment]
jenkins retest this please

**Comment by jerryyin** [comment]
jenkins retest this please

**Review by deven-amd — APPROVED** [review]

**Review by sunway513 — APPROVED** [review]
LGTM

**Comment by jerryyin** [comment]
@deven-amd Sure, I think is is related with our (QTS data center) network configurations and probably does not need to upstream.

The log failure from referenced from the body shows the failure log without it. Basically, any apt-get related tasks would fail for lack of ca-certificate (However, this is only reproducible in our CI machines. Otherwise due to how prevalent Ubuntu docker base image is used, this should fail everywhere).

What this fix does is to install the ca-certificate (included in software-properties-common). `--allows-unauthenticated` explicitly waived the apt-get command from validating certificate. Once it successfully completed, ca-certificate would be installed to container and rest of `apt-get` does not need `--allows-unauthenticated` any more

**Pull request merged**
