### PR TITLE
Develop upstream sync 190506

### PR DESCRIPTION
**Pull request by sunway513**
List of conflicts:
        tensorflow/compiler/xla/service/gpu/elemental_ir_emitter.cc
        both modified:   tensorflow/compiler/xla/service/gpu/gpu_executable.h
        both modified:   tensorflow/core/kernels/BUILD
        added by us:     tensorflow/core/platform/default/rocm_rocdl_path.cc
        added by us:     tensorflow/core/platform/rocm_rocdl_path.cc
        both modified:   tensorflow/examples/saved_model/integration_tests/BUILD
        both modified:   tensorflow/lite/python/lite_test.py
        both modified:   tensorflow/python/distribute/BUILD
        both modified:   tensorflow/python/keras/distribute/BUILD
        both modified:   tensorflow/stream_executor/rocm/BUILD
        both modified:   tensorflow/stream_executor/rocm/rocm_diagnostics.cc
        both modified:   tensorflow/stream_executor/rocm/rocm_dnn.cc
        both modified:   tensorflow/stream_executor/rocm/rocm_driver.cc
        both modified:   tensorflow/stream_executor/rocm/rocm_gpu_executor.cc
        both modified:   tensorflow/stream_executor/rocm/rocm_platform.cc
        added by us:     tensorflow/stream_executor/rocm/rocm_rng.h
        deleted by them: tensorflow/tools/docker/parameterized_docker_build.sh

### CODE REVIEW

**Comment by whchung** [comment]
@sunway513 
`rocm-xla` path has only 1 failure: `//tensorflow/compiler/xla/service/gpu:redzone_allocator_test`
`rocm` path build timed out for some reason. let me restart jenkins.
`cuda` and `rocm-v2` paths are good.

**Comment by whchung** [comment]
jenkins: retest this please

**Comment by sunway513** [comment]
jenkins: retest this please

**Comment by whchung** [comment]
@sunway513 for `rocm` build failures, please refer to this issue upstream. seems eigen pointer moves changed the behavior a bit:
https://github.com/tensorflow/tensorflow/issues/28411

**Comment by whchung** [comment]
may need to patch eigen with patch at:
https://bitbucket.org/eigen/eigen/pull-requests/639/fix-avx512-gcc-63-compilation/diff

**Pull request merged**
