### PR TITLE
[Do not Merge] Rocm xla changes to abtract use of llvm backend intrinsics

### PR DESCRIPTION
**Pull request by sumesh13**
1. Introduce target machine features that provides target specific intrinsic ids for generating llvm IR

### CODE REVIEW

**Comment by ROCm-Apps-Test** [comment]
Can one of the admins verify this patch?

**Comment by ROCm-Apps-Test** [comment]
Can one of the admins verify this patch?

**Comment by whchung** [comment]
the PR doesn't seem correct to me. it should only contain your changes, not upstream changes.

**Comment by whchung** [comment]
so maybe instead trying to send the PR to `develop-upstream`, you can try:

- change `master` branch in this repository to match upstream TensorFlow, and send your PR to `master`.
- just send it to upstream TensorFlow.

I'd prefer the latter approach.

**Pull request closed without merging**
