### PR TITLE
Change default ROCM to 6.2

### PR DESCRIPTION
**Pull request by jayfurmanek**

### CODE REVIEW

**Comment by jayfurmanek** [comment]
retest gpu-pycpp please

**Review by i-chaochen — APPROVED** [review]

**Comment by i-chaochen** [comment]
do we need to update these 3?

- https://github.com/ROCm/tensorflow-upstream/blob/develop-upstream/tensorflow/tools/ci_build/Dockerfile.rocm#L9 
- https://github.com/ROCm/tensorflow-upstream/blob/develop-upstream/tensorflow/tools/ci_build/linux/rocm/run_gpu_single.sh#L40
- https://github.com/ROCm/tensorflow-upstream/blob/develop-upstream/tensorflow/tools/ci_build/linux/rocm/run_gpu_multi.sh#L32

**Comment by jayfurmanek** [comment]
retest gpu-pycpp please

**Review by hsharsha — APPROVED** [review]

**Comment by hsharsha** [comment]
Also we need to update rocAutomation to pull latest 6.2 docker images.

**Comment by jayfurmanek** [comment]
> do we need to update these 3?
> 
> * https://github.com/ROCm/tensorflow-upstream/blob/develop-upstream/tensorflow/tools/ci_build/Dockerfile.rocm#L9
> * https://github.com/ROCm/tensorflow-upstream/blob/develop-upstream/tensorflow/tools/ci_build/linux/rocm/run_gpu_single.sh#L40
> * https://github.com/ROCm/tensorflow-upstream/blob/develop-upstream/tensorflow/tools/ci_build/linux/rocm/run_gpu_multi.sh#L32

That first image we don't use anymore, but yes we should probably update the defaults in the test scripts as well

**Comment by jayfurmanek** [comment]
retest gpu-non-pip-multi please

**Comment by jayfurmanek** [comment]
retest cpu-pycpp please

**Comment by jayfurmanek** [comment]
retest gpu-non-pip-multi  please

**Comment by jayfurmanek** [comment]
retest cpu-pycpp please

**Comment by jayfurmanek** [comment]
retest gpu-non-pip-multi please

**Pull request merged**
