### PR TITLE
Develop upstream sync 200706

### PR DESCRIPTION
**Pull request by deven-amd**

### CODE REVIEW

**Comment by ROCm-Apps-Test** [comment]
Can one of the admins verify this patch?

**Comment by deven-amd** [comment]
only one failure in `rocm` and it is the flaky one
```
//tensorflow/python/keras/distribute:keras_embedding_model_correctness_test_gpu FAILED in 3 out of 3 in 207.6s
```

link to the failing run
http://ml-ci.amd.com:21096/job/develop-upstream-unit-tests/job/tensorflow-upstream-unit-tests/2061/

**Comment by deven-amd** [comment]
jenkins : retest rocm please

**Comment by deven-amd** [comment]
one test in `rocm-cpp` timed-out....this is getting frustrating
```
//tensorflow/core/nccl:nccl_manager_test                                TIMEOUT in 3 out of 3 in 915.0s
```

http://ml-ci.amd.com:21096/job/develop-upstream-unit-tests/job/tensorflow-upstream-unit-tests-rocm-cpp/634/

will request jenkins to kick it off again

**Comment by deven-amd** [comment]
jenkins : retest rocm-cpp please

**Pull request merged**
