### PR TITLE
Develop upstream sync 220425

### PR DESCRIPTION
**Pull request by rahulbatra85**
https://github.com/ROCmSoftwarePlatform/frameworks-internal/issues/1562

### CODE REVIEW

**Comment by jayfurmanek** [comment]
https://github.com/ROCmSoftwarePlatform/frameworks-internal/issues/1562

**Comment by rahulbatra85** [comment]
jenkins: retest Ubuntu-GPU-multi please

**Comment by rahulbatra85** [comment]
jenkins: retest Ubuntu-GPU-multi please

**Comment by jayfurmanek** [comment]
jenkins: retest Ubuntu-GPU-single please

**Comment by jayfurmanek** [comment]
jenkins: retest Ubuntu-CPU please

**Comment by jayfurmanek** [comment]
jenkins: retest Ubuntu-GPU-multi please

**Comment by jayfurmanek** [comment]
jenkins: retest Ubuntu-CPU please

**Comment by jayfurmanek** [comment]
jenkins: retest Ubuntu-sanity please

**Comment by jayfurmanek** [comment]
jenkins: retest Ubuntu-sanity please

**Comment by jayfurmanek** [comment]
jenkins: retest Ubuntu-sanity please

**Pull request merged**
