### PR TITLE
Develop upstream sync 220822

### PR DESCRIPTION
**Pull request by jayfurmanek**
https://github.com/ROCmSoftwarePlatform/frameworks-internal/issues/2388

### CODE REVIEW

**Comment by jayfurmanek** [comment]
retest Ubuntu-GPU-multi please

**Review by rsanthanam-amd — APPROVED** [review]

**Comment by jayfurmanek** [comment]
retest Ubuntu-GPU-single please

**Comment by jayfurmanek** [comment]
retest Ubuntu-GPU-single please

**Comment by jayfurmanek** [comment]
retest Ubuntu-GPU-single please

**Comment by jayfurmanek** [comment]
retest Ubuntu-GPU-single please

**Comment by jayfurmanek** [comment]
retest Ubuntu-GPU-single please

**Pull request merged**
