### PR TITLE
[DO NOT MERGE]  test revised fix for upstream 

### PR DESCRIPTION
**Pull request by sumesh13**
PR-28270 needs a revised fix. Testing if  its good for ROCM

### CODE REVIEW

**Comment by sunway513** [comment]
jenkins: retest this please

**Comment by sumesh13** [comment]
Finished testing on ROCM

**Comment by sumesh13** [comment]
jenkins: retest this please

**Comment by sumesh13** [comment]
jenkins: retest this please

**Comment by whchung** [comment]
@sumesh13 I assume this PR can be closed now?

**Pull request closed without merging**
