### PR TITLE
Develop upstream sync 200113

### PR DESCRIPTION
**Pull request by whchung**

### CODE REVIEW

**Comment by whchung** [comment]
jenkins: retest rocm rocm-cpp rocm-xla please.

**Comment by whchung** [comment]
jenkins: retest please.

**Comment by whchung** [comment]
jenkins: retest rocm-cpp please.

**Comment by whchung** [comment]
jenkins: retest rocm please.

**Comment by whchung** [comment]
jenkins: retest rocm-xla please.

**Comment by whchung** [comment]
`rocm-cpp` shows failure. but test log shows:

```
Executed 859 out of 859 tests: 859 tests pass.
[32mINFO:[0m Build completed successfully, 20902 total actions
```

not sure why yet. will keep monitoring other 2 targets.

**Comment by deven-amd** [comment]
`rocm-cpp` failure is in the nccl_manager test. 

looking into the failure. also aborting the `rocm` and `rocm-xla` runs as we will need to rerun them anyway

**Comment by whchung** [comment]
`rocm` path should be find according to earlier build runs:
http://ml-ci.amd.com:21096/job/develop-upstream-unit-tests/job/tensorflow-upstream-unit-tests/1646/console

so is `rocm-xla` path:
http://ml-ci.amd.com:21096/job/develop-upstream-unit-tests/job/tensorflow-upstream-unit-tests-rocm-xla/993/console

**Comment by whchung** [comment]
jenkins: retest rocm-cpp please.

**Comment by deven-amd** [comment]
@whchung , the `rocm-cpp` failure was genuine...just pushed out a commit to fix it

**Comment by whchung** [comment]
@deven-amd thanks for the fix. the weekly merge for this week is now completed.

**Pull request merged**
