### PR TITLE
Updating BNA fusion to recognize the FusedBatchNorm*V3 Ops

### PR DESCRIPTION
**Pull request by deven-amd**

### CODE REVIEW

**Comment by whchung** [comment]
@deven-amd  could you fix the unit test errors? we definitely want this PR be merged.

**Comment by deven-amd** [comment]
yeah...looking into the failure...suspect the bug is on the MIOpen side. will have an update later today

**Comment by deven-amd** [comment]
The BNA unit test is now passing....the rocm failure is a TIMEOUT error
```
/tensorflow/python/keras/distribute:keras_save_load_test_gpu           TIMEOUT in 3 out of 3 in 915.0s
```
http://ml-ci.amd.com:21096/job/develop-upstream-unit-tests/job/tensorflow-upstream-unit-tests/2216/

will request jenkins to re-run the rocm test

**Comment by deven-amd** [comment]
jenkins : retest rocm please

**Comment by deven-amd** [comment]
same test timing out again.... :( 

http://ml-ci.amd.com:21096/job/develop-upstream-unit-tests/job/tensorflow-upstream-unit-tests/2217/

going to add a commit to `no_rocm` that test

**Comment by deven-amd** [comment]
jenkins: retest rocm please

**Comment by deven-amd** [comment]
a different test is timing out now.....this blows
```
//tensorflow/python/kernel_tests:qr_op_test                             TIMEOUT in 3 out of 3 in 915.0s
```
http://ml-ci.amd.com:21096/job/develop-upstream-unit-tests/job/tensorflow-upstream-unit-tests/2218/

beginning to think the culprit maybe the node. All 3 CI jobs ran on `prj47-rack-17`. `rocm` run on that node seem to be taking a hour longer than on other nodes

**Comment by deven-amd** [comment]
current run will fail too because the CI nodes all went down due to power issues.

will request jenkins to rerun rocm once the CI nodes are back up

**Comment by deven-amd** [comment]
jenkins: retest rocm please

**Comment by deven-amd** [comment]
finally ... hallelujah

**Pull request merged**
