### PR TITLE
Changes to support reloctable rocm for UT execution

### PR DESCRIPTION
**Pull request by pruthvistony**

### CODE REVIEW

**Comment by ROCm-Apps-Test** [comment]
Can one of the admins verify this patch?

**Comment by ROCm-Apps-Test** [comment]
Can one of the admins verify this patch?

**Comment by ROCm-Apps-Test** [comment]
Can one of the admins verify this patch?

**Comment by ROCm-Apps-Test** [comment]
Can one of the admins verify this patch?

**Comment by ROCm-Apps-Test** [comment]
Can one of the admins verify this patch?

**Comment by ROCm-Apps-Test** [comment]
Can one of the admins verify this patch?

**Comment by pruthvistony** [comment]
This change is no more required, since the code is implemented in a different way.
So closing the PR.

**Pull request closed without merging**
