### PR TITLE
Conversion from Rocsolver to Hipsolver for most LA functions.

### PR DESCRIPTION
**Pull request by stevenireeves**

### CODE REVIEW

**Comment by stevenireeves** [comment]
Jenkins retest : Ubuntu-GPU-multi please

**Comment by stevenireeves** [comment]
jenkins : retest Ubuntu-GPU-multi please

**Comment by stevenireeves** [comment]
@micmelesse FYI

**Comment by stevenireeves** [comment]
@deven-amd any comments on this PR?

**Comment by stevenireeves** [comment]
jenkins : retest Ubuntu-GPU-multi

**Comment by stevenireeves** [comment]
jenkins : retest Ubuntu-GPU-multi

**Comment by stevenireeves** [comment]
jenkins : retest Ubuntu-GPU-multi please

**Comment by stevenireeves** [comment]
jenkins : retest Ubuntu-GPU-multi please

**Comment by stevenireeves** [comment]
jenkins : retest Ubuntu-GPU-multi please

**Comment by stevenireeves** [comment]
jenkins : retest Ubuntu-GPU-multi please

**Comment by reza-amd** [comment]
@stevenireeves , do these changes work with older versions of ROCm?

**Comment by stevenireeves** [comment]
@reza-amd hipSolver is for ROCm4.5+. 

@deven-amd How much back-portability do we need for updates in develop-upstream, now that we are versioning Tensorflow with a specific ROCm version on Pypi? If we need more back portability I'll need to have significant changes to gpu_solvers.h/rocm_solvers.cc

**Comment by stevenireeves** [comment]
jenkins : retest Ubuntu-GPU-multi please

**Comment by stevenireeves** [comment]
jenkins : retest Ubuntu-GPU-multi please

**Comment by deven-amd** [comment]
> How much back-portability do we need for updates in develop-upstream

We need to ensure that we can build TF with current ROCm release (ROCm 4.5) and the previous two (ROCm 4.4, ROCm 4.3)...so for the near term, we need to ensure we can build with both (hipsolver and rocsolver) . Once we get to ROCm 4.7 (?), we can drop the rocsolver references / uses

**Comment by stevenireeves** [comment]
@deven-amd Alright I'll pull the old rocSolver stuff back in for <4.5. 
@reza-amd FYI.

**Comment by deven-amd** [comment]
if possible, please re-organize commits according to functionality (will make it easier to upstream)
* commit / changes to include  "hipsolver" as part of "local_config_rocm" 
* commit / changes to dynamically load "hipsolver" APIs
* commit / changes to replace calls to "rocsolver" APIs with calls to "hipsolver" APIs instead (based on ROCm version)

**Comment by stevenireeves** [comment]
@deven-amd I might create a different PR for this. It will be simpler to implement those changes if I start fresh.

**Pull request closed without merging**
