### PR TITLE
[ROCM] Fix includes for ROCm 5.6

### PR DESCRIPTION
**Pull request by jayfurmanek**
Merge for commits needed for ROCM 5.6

 - Fix includes for ROCm 5.6 https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/commit/cb323a85827a30b39dfd59bdd3555723876ef915

### CODE REVIEW

**Comment by jayfurmanek** [comment]
retest Ubuntu-GPU-multi please
retest Ubuntu-GPU-single please
retest gpu-pycpp please

**Comment by jayfurmanek** [comment]
retest gpu-non-pip-multi please

**Comment by jayfurmanek** [comment]
retest gpu-pycpp please

**Comment by jayfurmanek** [comment]
retest gpu-pycpp please

**Review by i-chaochen — APPROVED** [review]

**Comment by jayfurmanek** [comment]
retest gpu-pycpp please
retest cpu-non-pip please

**Comment by jayfurmanek** [comment]
retest cpu-non-pip please

**Comment by jayfurmanek** [comment]
retest gpu-pycpp please

**Comment by jayfurmanek** [comment]
retest cpu-non-pip please

**Pull request merged**
