### PR TITLE
Develop upstream sync 230313

### PR DESCRIPTION
**Pull request by rahulbatra85**
Weekly sync

### CODE REVIEW

**Comment by rahulbatra85** [comment]
retest Ubuntu-sanity please!

**Comment by i-chaochen** [comment]
@rahulbatra85 Thanks for this weekly-sync!

It will be great if you could add some info on the description (i.e., fixes and disable with related tickets/PRs) like we used to do.

exemplar weekly-sync:

https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/pull/1992
https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/pull/1987
https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/pull/2012

**Comment by rahulbatra85** [comment]
> @rahulbatra85 Thanks for this weekly-sync!
> 
> It will be great if you could add some info on the description (i.e., fixes and disable with related tickets/PRs) like we used to do.
> 
> exemplar weekly-sync:
> 
> https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/pull/1992 https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/pull/1987 https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/pull/2012

Yes, I will add all the info once I am done with weekly sync. CI_Sanity and cpu run is still failing.

**Comment by rahulbatra85** [comment]
Weekly sync issues 
https://github.com/ROCmSoftwarePlatform/frameworks-internal/issues/3952
https://github.com/ROCmSoftwarePlatform/frameworks-internal/issues/3951
https://github.com/ROCmSoftwarePlatform/frameworks-internal/issues/3950

**Comment by rahulbatra85** [comment]
- Had to revert this f9df95097680d5468dc67d868d1294be8889e522. Otherwise, Ubuntu Sanity CI fails.
- Tensorflow updated a commit number for dependency(google_benchmark), but it has bug around libpfm library and fails to build https://github.com/google/benchmark
- A commit probably fixes the issue https://github.com/google/benchmark/commit/68aa1903b18f6967a608f3584db3eac28a4f883c, but it not in the v1.71 release that tensorflow moved to

**Review by i-chaochen — APPROVED** [review]

**Pull request merged**
