### PR TITLE
Remove jax from install list in tf-build container

### PR DESCRIPTION
**Pull request by jayfurmanek**

### CODE REVIEW

**Review by rahulbatra85 — APPROVED** [review]

**Review by i-chaochen — APPROVED** [review]

**Comment by jayfurmanek** [comment]
retest gpu-non-pip-multi please

**Comment by jayfurmanek** [comment]
retest code-check please

**Comment by jayfurmanek** [comment]
retest Ubuntu-CPU please

**Comment by i-chaochen** [comment]
retest Ubuntu-CPU please

**Comment by jayfurmanek** [comment]
no longer needed

**Pull request closed without merging**
