### PR TITLE
adding HIP_HIDDEN_FREE_MEM=500 to Dockerfile.rocm

### PR DESCRIPTION
**Pull request by deven-amd**

### CODE REVIEW

**Comment by whchung** [comment]
@deven-amd , `rocm` and `rocm-v2` paths seem to fail on the same test due to timeout. should we change them to large from medium?

**Comment by deven-amd** [comment]
let me run that test locally...and see how much time it takes and if it passes!

will submit a commit to bump the timeout value later tonight

**Comment by deven-amd** [comment]
@whchung 

I see that `//tensorflow/python/kernel_tests:conv_ops_test_gpu` has already been tagged as `large` in PR #412 , so won't make the same change here.

Once PR #412 is merged, this PR should be good to go as well

**Comment by whchung** [comment]
got it. didn't realize we are dealing the same case in #412.

**Pull request merged**
