### PR TITLE
update eigen patch for hip-clang scalar accessor in r1.15-rocm branch

### PR DESCRIPTION
**Pull request by jeffdaily**
@yxsamliu please make sure this branch is working for you.

### CODE REVIEW

**Comment by ROCm-Apps-Test** [comment]
Can one of the admins verify this patch?

**Comment by sunway513** [comment]
manually kicked off one CI run here for hip/hcc path:
http://ml-ci.amd.com:21096/job/tf-develop-upstream-releases/job/tensorflow-upstream-rel1.15-nightly/188/

**Comment by jeffdaily** [comment]
Assuming hip/hcc path is okay, I would then want approval from @yxsamliu prior to merging.

**Comment by sunway513** [comment]
The CI check was failed, kicked of another two CI builds.

**Comment by sunway513** [comment]
The following unit test would fail with this PR using hip/hcc:
//tensorflow/python/keras/optimizer_v2:adamax_test_gpu     
Reproducible with multiple CI runs.

**Comment by jeffdaily** [comment]
Thank you for running CI against this PR.  I will look into the failure.

**Comment by jeffdaily** [comment]
This same test is failing in my ROCm 3.0 container with the r1.15-rocm branch.  Is this test flaky?

**Comment by jeffdaily** [comment]
The failing unit test was marked no_rocm in the r1.15 branch, so I have updated this PR to tag the same test as no_rocm in this PR targeting the r1.15-rocm branch.

**Comment by jeffdaily** [comment]
CI build has passed after disabling the failing test.  See https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/pull/826/commits/924610cd556e3caf642de787efda4982da3828ef .

**Pull request merged**
