### PR TITLE
R1.10 rocm release branch 

### PR DESCRIPTION
**Pull request by sunway513**
Don't Merge, this PR is to kick off the CI and compare between r1.10-rocm with the r1.10 branch.

### CODE REVIEW

**Comment by whchung** [comment]
@sunway513 has there been a CI test set for this PR?

**Comment by sunway513** [comment]
jenkins: retest this please

**Comment by parallelo** [comment]
jenkins:  retest this please

**Comment by sunway513** [comment]
jenkins: retest this please

**Comment by parallelo** [comment]
FYI - We currently can't do PR builds off of other branches, but the `r1.10-rocm` branch is being built every night here:  http://205.234.28.200:21096/job/tensorflow-upstream-rel1.10-nightly/

Here's the summary of job 17:  
```
[31m[1mERROR: [0m/workspace/tensorflow/contrib/eager/python/examples/densenet/BUILD:5:1: file '//tensorflow:tensorflow.bzl' does not contain symbol 'cuda_py_test' (did you mean 'tf_py_test'?)
[31m[1mERROR: [0m/workspace/tensorflow/contrib/eager/python/examples/densenet/BUILD:17:1: name 'cuda_py_test' is not defined
[33mDEBUG: [0m/home/jenkins/workspace/tensorflow-upstream-rel1.10-nightly/bazel-ci_build-cache/.cache/bazel/_bazel_jenkins/eab0d61a99b6696edb3d2aff87b585e8/external/bazel_tools/tools/build_defs/pkg/pkg.bzl:224:17: @//tensorflow/tools/lib_package:common_deps: you provided a non dictionary to the pkg_tar `files` attribute. This attribute was renamed to `srcs`. Consider renaming it in your BUILD file.
[33mDEBUG: [0m/home/jenkins/workspace/tensorflow-upstream-rel1.10-nightly/bazel-ci_build-cache/.cache/bazel/_bazel_jenkins/eab0d61a99b6696edb3d2aff87b585e8/external/bazel_tools/tools/build_defs/pkg/pkg.bzl:224:17: @//tensorflow/tools/lib_package:cheaders: you provided a non dictionary to the pkg_tar `files` attribute. This attribute was renamed to `srcs`. Consider renaming it in your BUILD file.
[31m[1mERROR: [0mpackage contains errors: tensorflow/contrib/eager/python/examples/densenet
[33mDEBUG: [0m/home/jenkins/workspace/tensorflow-upstream-rel1.10-nightly/bazel-ci_build-cache/.cache/bazel/_bazel_jenkins/eab0d61a99b6696edb3d2aff87b585e8/external/bazel_tools/tools/build_defs/pkg/pkg.bzl:224:17: @//tensorflow/tools/lib_package:eager_cheaders: you provided a non dictionary to the pkg_tar `files` attribute. This attribute was renamed to `srcs`. Consider renaming it in your BUILD file.
[33mDEBUG: [0m/home/jenkins/workspace/tensorflow-upstream-rel1.10-nightly/bazel-ci_build-cache/.cache/bazel/_bazel_jenkins/eab0d61a99b6696edb3d2aff87b585e8/external/bazel_tools/tools/build_defs/pkg/pkg.bzl:224:17: @//tensorflow/tools/lib_package:clib: you provided a non dictionary to the pkg_tar `files` attribute. This attribute was renamed to `srcs`. Consider renaming it in your BUILD file.
[33mDEBUG: [0m/home/jenkins/workspace/tensorflow-upstream-rel1.10-nightly/bazel-ci_build-cache/.cache/bazel/_bazel_jenkins/eab0d61a99b6696edb3d2aff87b585e8/external/bazel_tools/tools/build_defs/pkg/pkg.bzl:224:17: @//tensorflow/tools/lib_package:clicenses: you provided a non dictionary to the pkg_tar `files` attribute. This attribute was renamed to `srcs`. Consider renaming it in your BUILD file.
[31m[1mERROR: [0mSkipping '//tensorflow/python/distribute:distribute_coordinator_test': no such package 'tensorflow/python/distribute': BUILD file not found on package path
[35mWARNING: [0mTarget pattern parsing failed.
[...]
Executed 533 out of 533 tests: 533 tests pass.
[0m[31m[1mAll tests passed but there were other errors during the build.
[0m
[31m[1mFAILED:[0m Build did NOT complete successfully
```

**Pull request closed without merging**
