### PR TITLE
Enable strsm/dtrsm through a const_cast hack

### PR DESCRIPTION
**Pull request by iotamudelta**
Mainly just update reasons for unit test failures and enable one.

### CODE REVIEW

**Comment by iotamudelta** [comment]
Interesting, `matrix_solve_ls_op_test.py` and `linalg_ops_test.py` both run on my 1.8.2 RC ROCm.
@whchung any reason you could come up with why that is the case?

**Comment by whchung** [comment]
I am not sure. Perhaps it's due to differences of `rocBLAS` in 1.8.1 (installed in the CI nodes) and 1.8.2?

**Comment by iotamudelta** [comment]
Could be. Let's shelve this along the rocFFT PR until 1.8.2 is rolled out on the CI?

**Comment by whchung** [comment]
agree

**Comment by whchung** [comment]
@iotamudelta CI node has been upgraded to 1.8.2. time to respin this PR?

**Comment by iotamudelta** [comment]
@whchung works fine now - can we integrate?

**Pull request merged**
