### PR TITLE
Develop upstream sync 230703

### PR DESCRIPTION
**Pull request by i-chaochen**
Full details:
https://github.com/ROCmSoftwarePlatform/frameworks-internal/issues/4807#issuecomment-1621968046

### CODE REVIEW

**Comment by i-chaochen** [comment]
retest Ubuntu-CPU please

**Comment by i-chaochen** [comment]
retest Ubuntu-CPU please

**Comment by i-chaochen** [comment]
retest Ubuntu-CPU please

**Comment by i-chaochen** [comment]
retest Ubuntu-CPU please

**Comment by i-chaochen** [comment]
retest Ubuntu-CPU please

**Comment by i-chaochen** [comment]
retest Ubuntu-CPU please

**Review by draganmladjenovic — APPROVED** [review]

**Comment by draganmladjenovic** [comment]
retest Ubuntu-CPU please

@i-chaochen 
//tensorflow/python/kernel_tests/nn_ops:conv_ops_test_gpu might be genuine failure.

retest Ubuntu-GOU-single please

**Comment by i-chaochen** [comment]
retest Ubuntu-CPU please
retest Ubuntu-GPU-single please

**Comment by i-chaochen** [comment]
> retest Ubuntu-CPU please
> 
> @i-chaochen //tensorflow/python/kernel_tests/nn_ops:conv_ops_test_gpu might be genuine failure.
> 
> retest Ubuntu-GOU-single please

Hmmm....these tests are passed in previous CI and my local. Do you get failed in your side?

**Comment by draganmladjenovic** [comment]
> > retest Ubuntu-CPU please
> > @i-chaochen //tensorflow/python/kernel_tests/nn_ops:conv_ops_test_gpu might be genuine failure.
> > retest Ubuntu-GOU-single please
> 
> Hmmm....these tests are passed in previous CI and my local. Do you get failed in your side?

Actually it doesn't.

**Comment by i-chaochen** [comment]
retest Ubuntu-CPU please

**Comment by i-chaochen** [comment]
merge it since spmd_expansion_mlir is no longer flaky and we need to remove my skipped in CPU script
https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/pull/2149

**Pull request merged**
