### PR TITLE
Develop upstream sync 230220

### PR DESCRIPTION
**Pull request by jayfurmanek**
https://github.com/ROCmSoftwarePlatform/frameworks-internal/issues/3730

- hipevent update reverted: https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/pull/1996/commits/512694caa62cfd29d45b013c667731837ac48088
- gpu_fusion_rewrite removed: https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/pull/1996/commits/f76b4d4a2d3a3aa0a95ce9d4822eb94abb9af127
- AvgPoolGradOutputMemoryOutOfBounds test works on NCHW on ROCM, but the test is NHWC, so disable https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/pull/1996/commits/6a2e045bd7200dbac26e82b6184bb46871dfa1d2
- New test [replay_computation_bin_gpu_test](https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/pull/1996/commits/cdcd9098a4fbe6b301e30c9a7fb93dc9af7ea3e1) didn't work on ROCM, fixed

### CODE REVIEW

**Comment by jayfurmanek** [comment]
retest gpu-non-pip-large please
retest Ubuntu-GPU-single please

**Comment by jayfurmanek** [comment]
retest gpu-non-pip-large please

**Comment by jayfurmanek** [comment]
retest Ubuntu-GPU-single please
retest gpu-non-pip-large please

**Comment by jayfurmanek** [comment]
retest gpu-non-pip-large please

**Comment by jayfurmanek** [comment]
retest Ubuntu-GPU-single please

**Comment by i-chaochen** [comment]
maybe we shall create a ticket for testAvgPoolGradOutputMemoryOutOfBounds?

**Comment by jayfurmanek** [comment]
retest Ubuntu-GPU-single please

**Comment by jayfurmanek** [comment]
> maybe we shall create a ticket for testAvgPoolGradOutputMemoryOutOfBounds?

https://github.com/ROCmSoftwarePlatform/frameworks-internal/issues/3770

**Review by i-chaochen — APPROVED** [review]

**Review by i-chaochen — COMMENTED** [review]
I found this replay_computation_bin_gpu_test issue on the nightly-upstream CI as well, we shall push this change PR to upstream.

**Pull request merged**
