### PR TITLE
Install miopenkernels packages to Dockerfile.rocm

### PR DESCRIPTION
**Pull request by jayfurmanek**
https://github.com/ROCmSoftwarePlatform/frameworks-internal/issues/2162

### CODE REVIEW

**Comment by jayfurmanek** [comment]
retest Ubuntu-CPU please

**Comment by jayfurmanek** [comment]
retest Ubuntu-CPU please

**Comment by jayfurmanek** [comment]
retest Ubuntu-CPU please

**Comment by jayfurmanek** [comment]
retest Ubuntu-GPU-single please

**Comment by jayfurmanek** [comment]
retest Ubuntu-GPU-single please

**Comment by jayfurmanek** [comment]
retest Ubuntu-GPU-single please

**Review by rsanthanam-amd — APPROVED** [review]

**Pull request merged**
