### PR TITLE
find rocm components individually

### PR DESCRIPTION
**Pull request by afzpatel**
Required for spack since all the rocm components are located in different paths

### CODE REVIEW

**Comment by i-chaochen** [comment]
retest Ubuntu-GPU-multi please
retest Ubuntu-CPU please

**Comment by hsharsha** [comment]
retest Ubuntu-CPU please
retest Ubuntu-GPU-single please

**Comment by afzpatel** [comment]
retest Ubuntu-GPU-single please

**Review by hsharsha — APPROVED** [review]
LGTM

**Comment by i-chaochen** [comment]
retest Ubuntu-GPU-single please

**Comment by afzpatel** [comment]
retest Ubuntu-GPU-single please

**Comment by afzpatel** [comment]
retest Ubuntu-GPU-single please

**Comment by afzpatel** [comment]
I'm not able to reproduce the ci build failure for Ubuntu-GPU-single on my local machine, any ideas what the issue might be?

**Comment by afzpatel** [comment]
retest Ubuntu-GPU-single please

**Comment by hsharsha** [comment]
> I'm not able to reproduce the ci build failure for Ubuntu-GPU-single on my local machine, any ideas what the issue might be?

I think it is landing on a node where the rocm driver is not stable which causes the tests to fail. If you can add the logs to your local run, here we can disregard the CI failure and merge this change.

**Comment by i-chaochen** [comment]
retest Ubuntu-GPU-single please

**Comment by i-chaochen** [comment]
retest Ubuntu-GPU-single please

**Comment by i-chaochen** [comment]
> I'm not able to reproduce the ci build failure for Ubuntu-GPU-single on my local machine, any ideas what the issue might be?

It's because one of nodes has driver issue, we already marked it offline and I'm tring to retest it another node.

**Comment by afzpatel** [comment]
Here's a log of my test run on mi100. There are only 2 test failures, one of which is that the test failed to allocate enough memory on the device. The errors I was getting on the ci are not present in the local run.
[mi100_command.log](https://github.com/user-attachments/files/15902402/mi100_command.log)

**Comment by i-chaochen** [comment]
retest Ubuntu-GPU-single please

**Comment by i-chaochen** [comment]
> Here's a log of my test run on mi100. There are only 2 test failures, one of which is that the test failed to allocate enough memory on the device. The errors I was getting on the ci are not present in the local run. [mi100_command.log](https://github.com/user-attachments/files/15902402/mi100_command.log)

Yes, it wouldn't have any problem because I can see [gpu-pycpp](http://ml-ci.amd.com:21096/job/tensorflow/job/github-prs-rocmfork-develop-upstream/job/rocm-latest-gpu-pycpp/570/) is green

**Review by i-chaochen — APPROVED** [review]

**Comment by afzpatel** [comment]
Now that the pr is merged, this change needs to be backported to the r2.14-rocm-enhanced-spack branch. Also another branch called r2.16-rocm-enhanced-spack should be created with this change and https://github.com/ROCm/tensorflow-upstream/commit/f4f4e8698b90755b0b5ea2d9da1933b0b988b111

**Comment by hsharsha** [comment]
https://github.com/ROCm/tensorflow-upstream/commit/f4f4e8698b90755b0b5ea2d9da1933b0b988b111 
Instead of creating a new branch w can we just use that as patch and apply it during spack tf installtion? That way we can use the rocm-2.xx-enhanced along with the patch.

**Comment by afzpatel** [comment]
> [f4f4e86](https://github.com/ROCm/tensorflow-upstream/commit/f4f4e8698b90755b0b5ea2d9da1933b0b988b111) Instead of creating a new branch w can we just use that as patch and apply it during spack tf installtion? That way we can use the rocm-2.xx-enhanced along with the patch.

Sounds good, I'll try that out.

**Pull request merged**
