### PR TITLE
rocm device_tracer implementation

### PR DESCRIPTION
**Pull request by eshcherb**
ROCM device tracer implementation

### CODE REVIEW

**Comment by ROCm-Apps-Test** [comment]
Can one of the admins verify this patch?

**Comment by ROCm-Apps-Test** [comment]
Can one of the admins verify this patch?

**Comment by eshcherb** [comment]
I have addressed the comment from PR #106 

The PR depends on changes to HIP and HCC to function properly:
    HCC: https://github.com/eshcherb/hcc branch 'roctracer-hip-frontend' - working on publishing it as PR
    HIP: https://github.com/eshcherb/HIP branch 'roctracer-hip-frontend-180807' PR#622

Also going to change the CI script for TensorFlow so this PR can be tested with modified HIP / HCC, as well as ROCm GPU tracer,  #105 can be used as an example.

**Comment by eshcherb** [comment]
Also the PR is using the ROC-tracer library, working on open-soucing it:
https://github.com/ROCmSoftwarePlatform/roctracer

**Comment by whchung** [comment]
@eshcherb Thanks. Since there is a new dependent component (`roctracer`) needed in order to enable the feature introduced in this PR. Please help change `tensorflow/tools/ci_build/Dockerfile.rocm` whatever way you want to make sure TensorFlow is built with `roctracer`. It it suggested to change `Dockerfile.rocm` so HCC / HIP are cloned from your fork, or the branches which contains references to `roctracer`.

**Comment by whchung** [comment]
comments by @MikalaiDrabovich

'stream:all' data is missing in RunMetadata for rocm, but it is always present in cuda. That's critical since that's where native tfprof and also tensorscope take op gpu time ( 'acc time').
I diff'ed device_tracer_rocm.cc with cuda variant and the part which adds to 'stream:all' looks ok - data is being added to stream:all , yet it doesn't appear in RunMetadata - @eshcherb @whchung please take a look of what's going on with stream:all
tensorflow-upstream/tensorflow/core/platform/default/device_tracer_rocm.cc

Line 289 in 81544e8

 collector->Save(strings::StrCat(stream_device, "all"), ns); 
Not critical but nice to follow the same format: - 'stream:N' (where N is some int number) streams in rocm contain only memcpy ops, but should also include other ops (sum of times from all n streams will be equal to times stream:all)

**Comment by MikalaiDrabovich** [comment]
Update - looks like 'stream:all' is not always missing: every 8-9 steps it appears in RunMetadata, then again is missing for next 8-9 steps, this is for tf_cnn_benchmarks.  I haven't observed this with official resnet model from tensorflow/models/tree/master/official/resnet Digging deeper ...

**Comment by eshcherb** [comment]
As I understand the records are collecting to stream raws and to 'all' row.
Are the records missing only in 'all' raws or they missing in both stream and 'all' rows.

Was I saw that the records are delayed by HCC runtime so the can come much later.
Do you merge the timelines/metadata from all steps?

**Comment by MikalaiDrabovich** [comment]
> Are the records missing only in 'all' raws or they missing in both stream and 'all' rows.
both

> Do you merge the timelines/metadata from all steps?
roctracer sends already merged data, tensorscope now accounts for this, unlike tfprof which erroneously treats merged data as being from one step. But tfprof doesn't seem to be maintained now: https://github.com/tensorflow/tensorflow/issues/20960#issuecomment-414479927

**Comment by parallelo** [comment]
Regarding the most recent commit, I suspect that we won't be able to merge this PR if `ci_build/Dockerfile.rocm` is changed to use your forks for HIP & HCC.  I'd recommend using a separate Dockerfile instead (e.g. `Dockerfile.rocm-roctracer`).  This will allow our critical CI infrastructure to proceed normally, and for the important rocTracer development to continue in parallel.

**Comment by whchung** [comment]
Close this PR as it has been superseded by #238

**Pull request closed without merging**
