### PR TITLE
Develop upstream sync 180924

### PR DESCRIPTION
**Pull request by jeffdaily**

### CODE REVIEW

**Comment by jeffdaily** [comment]
@whchung @deven-amd need your advice on these two failing tests.

 - tensorflow/python/kernel_tests/map_stage_op_test.py
 - tensorflow/python/kernel_tests/stage_op_test.py

Both tests were last modified Jan 25 so not recently.  The map_stage_op_test.py is a copy of stage_op_test.py but with additional tests and modifications.  However, the test cases that fail for both are parts of the tests that are mostly just a copy-and-paste of each other and they both involve a `six.moves.Queue.get(timeout=TIMEOUT)`.  If I increase the TIMEOUT value in each file from 1 to 6, the tests all pass.  Anything less than a TIMEOUT of 6 has resulted in failure.

Would it be correct to increase the TIMEOUT value?

It's not clear to me why this test is only now failing.  The Queue is filled by another thread that is running a simple graph session then putting to the queue.  The queue is however timing out when `i=0`, resulting in the failure.  The only way the queue could be empty is if the background thread is taking too long to process.  See below for the test case.

```python
  def testCapacity(self):
    capacity = 3

    with ops.Graph().as_default() as G:
      with ops.device('/cpu:0'):
        x = array_ops.placeholder(dtypes.int32, name='x')
      with ops.device(test.gpu_device_name()):
        stager = data_flow_ops.StagingArea(
            [
                dtypes.int32,
            ], capacity=capacity, shapes=[[]])
        stage = stager.put([x])
        ret = stager.get()
        size = stager.size()

    G.finalize()

    from six.moves import queue as Queue
    import threading

    queue = Queue.Queue()
    n = 8

    with self.test_session(use_gpu=True, graph=G) as sess:
      # Stage data in a separate thread which will block
      # when it hits the staging area's capacity and thus
      # not fill the queue with n tokens
      def thread_run():
        for i in range(n):
          sess.run(stage, feed_dict={x: i})
          queue.put(0)

      t = threading.Thread(target=thread_run)
      t.daemon = True
      t.start()

      # Get tokens from the queue until a timeout occurs
      try:
        for i in range(n):
          queue.get(timeout=TIMEOUT)
      except Queue.Empty:
        pass

      # Should've timed out on the iteration 'capacity'
      if not i == capacity:
        self.fail("Expected to timeout on iteration '{}' "
                  "but instead timed out on iteration '{}' "
                  "Staging Area size is '{}' and configured "
                  "capacity is '{}'.".format(capacity, i, sess.run(size),
                                             capacity))
```

**Comment by jeffdaily** [comment]
jenkins: retest this please

**Comment by whchung** [comment]
@jeffdaily since said tests depend on the performance of multi-threaded performance of copy routine which may vary per platform. I think it's okay to enlarge TIMEOUT value for now.

Wondering do you still have a ROCm 1.8.x installation? Perhaps it shows a performance regression in the incumbent ROCm 1.9.

**Comment by jeffdaily** [comment]
I have one 1.8.x installation left.  I'm running the tests locally now and will report soon.

**Comment by jeffdaily** [comment]
The same two tests fail for the 1.8.x installation.  In hindsight, if it had been a rocm regression, we would have seen it during last week's merge, right?  Since the 1.8.x tests are failing in the same way, this implies it is something upstream.

@whchung  Should I proceed with changing the TIMEOUT?

**Comment by whchung** [comment]
@jeffdaily please workaround it by changing TIMEOUT.

**Comment by whchung** [comment]
@jeffdaily merged this PR even though CUDA path has not been verified due to CI config issue.

**Comment by jeffdaily** [comment]
jenkins: retest this please

**Pull request merged**
