### PR TITLE
Dropping whitespeace/comment/trivial differences in content to reduce…

### PR DESCRIPTION
**Pull request by deven-amd**
… the diff count between develop-upstream and upstream/master

### CODE REVIEW

**Comment by ROCm-Apps-Test** [comment]
Can one of the admins verify this patch?

**Comment by deven-amd** [comment]
jenkins : retest rocm please

**Comment by deven-amd** [comment]
failing `rocm` run (with two spurious failures):

http://ml-ci.amd.com:21096/job/develop-upstream-unit-tests/job/tensorflow-upstream-unit-tests/1611/

**Comment by deven-amd** [comment]
the `//tensorflow/python:convert_to_constants_test ` test keeps failing more often than not.

m gonna push out a commit to add the `no_rocm` back to it

**Comment by deven-amd** [comment]
yet another `rocm` run with spurious failures....gonna add the `no_rocm` tag to those tests too :(

http://ml-ci.amd.com:21096/job/develop-upstream-unit-tests/job/tensorflow-upstream-unit-tests/1612

http://ml-ci.amd.com:21096/job/develop-upstream-unit-tests/job/tensorflow-upstream-unit-tests/1613

**Pull request merged**
