### PR TITLE
Multi gpu fix

### PR DESCRIPTION
**Pull request by micmelesse**
This pr reenables some tests from https://github.com/tensorflow/tensorflow/pull/50331.  See https://github.com/ROCmSoftwarePlatform/frameworks-internal/issues/241#issuecomment-899761734 for more info.

### CODE REVIEW

**Comment by rsanthanam-amd** [comment]
jenkins: retest Ubuntu-CPU please

**Comment by rsanthanam-amd** [comment]
jenkins: retest Ubuntu-sanity please

**Comment by rsanthanam-amd** [comment]
jenkins: retest Ubuntu-GPU-single please

**Comment by rsanthanam-amd** [comment]
jenkins: retest Ubuntu-GPU-multi please

**Comment by micmelesse** [comment]
jenkins: retest Ubuntu-CPU please

**Comment by micmelesse** [comment]
jenkins: retest Ubuntu-GPU-single please

**Comment by micmelesse** [comment]
jenkins: retest Ubuntu-GPU-multi please

**Comment by micmelesse** [comment]
jenkins: retest Ubuntu-GPU-multi please

**Comment by stevenireeves** [comment]
LGTM, can you upstream these changes? Thanks!

**Review by stevenireeves — APPROVED** [review]

**Comment by micmelesse** [comment]
> LGTM, can you upstream these changes? Thanks!

I have started a pr here, https://github.com/tensorflow/tensorflow/pull/51470. I will add reviewers when it is ready.

**Pull request merged**
