### PR TITLE
ROCm 2.7-specific fixes for 1.14

### PR DESCRIPTION
**Pull request by whchung**
Internal ticket: SWDEV-196996.

### CODE REVIEW

**Comment by sunway513** [comment]
I'll pull and check this PR, thanks.

**Comment by whchung** [comment]
Should the test is fine on `r1.14-rocm`, please only cherry-pick commit `023e352` onto `develop-upstream`.

**Comment by sunway513** [comment]
LGTM, let's wait for the TF1.14 CI check here:
http://ml-ci.amd.com:21096/job/tensorflow-upstream-rel1.14-nightly/92/console

**Comment by sunway513** [comment]
For the #92 CI build it can finish the tests and built py2.7/3.5/3.6 whl packages, but failed with py3.7.
It doesn't look related to the PR.
I've kicked of another run, and will merge this PR so it can unblock the QA's test on TF-XLA. 
Failure message:
```
[32m[643 / 4,079][0m [-----] Executing genrule //tensorflow/python:framework/fast_tensor_util.pyx_cython_translation [for host]
[31m[1mERROR: [0m/home/jenkins/workspace/tensorflow-upstream-rel1.14-nightly/bazel-ci_build-cache/.cache/bazel/_bazel_jenkins/eab0d61a99b6696edb3d2aff87b585e8/external/local_config_rocm/rocm/BUILD:116:1: declared output 'external/local_config_rocm/rocm/rocm/include/base/backend_manager.hpp' was not created by genrule. This is probably because the genrule actually didn't create this output, or because the output was a directory and the genrule was run remotely (note that only the contents of declared file outputs are copied from genrules run remotely)
[31m[1mERROR: [0m/home/jenkins/workspace/tensorflow-upstream-rel1.14-nightly/bazel-ci_build-

**Pull request merged**
