### PR TITLE
merge all RCCL changes into r1.15-rocm branch

### PR DESCRIPTION
**Pull request by jeffdaily**

### CODE REVIEW

**Comment by jeffdaily** [comment]
@sunway513 for our sanity, is there any way we can trigger a CI build against this PR?  I ran and verified the nccl_manager_test locally prior to submitting this PR, but perhaps more rigor is warranted.

**Comment by sunway513** [comment]
@jeffdaily , yes, will kick off a CI run of it, thanks.

**Comment by sunway513** [comment]
@jeffdaily , let's watch for the following one:
http://ml-ci.amd.com:21096/job/tensorflow-upstream-rel1.15-nightly/11/console

**Comment by jeffdaily** [comment]
I realized too late that this PR won't have the change to the `run_csb_test.sh` script or the new `rocm_multi_gpu` tag.  I'll need to cherry-pick that from upstream PR.

**Comment by jeffdaily** [comment]
@sunway513  http://ml-ci.amd.com:21096/job/tensorflow-upstream-rel1.15-nightly/15/ has completed successfully.

**Comment by sunway513** [comment]
LGTM, thanks @jeffdaily

**Pull request merged**
