### PR TITLE
Disable sub tests in dot_operation_test

### PR DESCRIPTION
**Pull request by sumesh13**
Sub tests disabled fall into two categories of fails
1. Due to need for complex data type support
2. Need for strided gemm

### CODE REVIEW

**Comment by sumesh13** [comment]
jenkins: retest this please

**Comment by sumesh13** [comment]
jenkins: retest this please

**Comment by whchung** [comment]
jenkins: retest this please

**Comment by whchung** [comment]
jenkins: retest this please

**Pull request merged**
