### PR TITLE
Install hipblasLT in containers for ROCM5.5

### PR DESCRIPTION
**Pull request by jayfurmanek**

### CODE REVIEW

**Review by rahulbatra85 — APPROVED** [review]

**Comment by jayfurmanek** [comment]
retest gpu-pycpp please

**Comment by jayfurmanek** [comment]
retest gpu-pycpp please

**Comment by jayfurmanek** [comment]
retest gpu-pycpp please

**Comment by jayfurmanek** [comment]
retest gpu-pycpp please

**Review by i-chaochen — APPROVED** [review]

**Pull request merged**
