### PR TITLE
Develop upstream sync 190625

### PR DESCRIPTION
**Pull request by jeffdaily**

### CODE REVIEW

**Comment by jeffdaily** [comment]
Jenkins: retest rocm-xla please

**Comment by jeffdaily** [comment]
@whchung I'll need your help/advice.  The cuda CI is broken due to upstream removing `GpuExecutable::CheckCompatibilityWithServiceExecutableRunOptions`.  During the merge, I chose to keep `gpu_executable.h` as-is, with a pure virtual function.  But now nvptx_compiler.cc is trying to instantiate the `GpuExecutable` base class, which has a pure virtual, and fails.

**Comment by whchung** [comment]
@jeffdaily try cherry-pick @jerryyin 's work in https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/pull/523

**Comment by jerryyin** [comment]
@jeffdaily The root cause of your problem is not that upstream is trying to remove `CheckCompatibilityWithServiceExecutableRunOptions()`, because we created this function and it never existed before in upstream. The problem is that `nvptx_compiler` should never instantiate the `GpuExecutable`, because we made only either `NVPTXExecutable` or `AMDGPUExecutable` to be instantiable. If you replace `GpuExecutable` with `NVPTXExecutable`, it should fix your compilation issues now.

As @whchung has pointed out, a easier way to address though is to just apply #523 so that you don't have to address this && I don't have to fix the conflict.

**Comment by jeffdaily** [comment]
I have cherry-picked #523 and fixed merge conflicts.  Hopefully CI passes.  Thanks @jerryyin and @whchung for your help.

**Comment by whchung** [comment]
@jeffdaily I just merged #523 and I took liberty resolving additional conflicts in this PR because of that.

**Comment by jeffdaily** [comment]
Jenkins: retest rocm-xla please

**Comment by jeffdaily** [comment]
Only XLA path is failing.
```
TIMEOUT //tensorflow/compiler/xla/client/lib:svd_test_gpu     
FAILED  //tensorflow/compiler/xla/service/gpu/tests:gemm_rewrite_test
```

**Comment by whchung** [comment]
for `gemm_rewrite_test` let's skip it. it's doing something CUA-specific.
for `svd_test_gpu` please run it locally and see if we need to change its timeout value.

**Comment by jeffdaily** [comment]
Any idea how long svd_test_gpu is supposed to take?  It's going on beyond 10 minutes and longer running locally.

**Comment by jeffdaily** [comment]
@whchung  in case it helps triage the svd_test_gpu, these were the XLA-related files that had merge conflicts.  Perhaps I resolved one or more of these files incorrectly.

```
CONFLICT (content): Merge conflict in tensorflow/compiler/xla/tests/select_and_scatter_test.cc
CONFLICT (content): Merge conflict in tensorflow/compiler/xla/tests/exhaustive_op_test.cc
CONFLICT (content): Merge conflict in tensorflow/compiler/xla/service/instruction_fusion.h
CONFLICT (content): Merge conflict in tensorflow/compiler/xla/service/instruction_fusion.cc
CONFLICT (content): Merge conflict in tensorflow/compiler/xla/service/gpu/nvptx_compiler.cc
CONFLICT (content): Merge conflict in tensorflow/compiler/xla/service/gpu/gpu_executable.h
CONFLICT (content): Merge conflict in tensorflow/compiler/xla/service/gpu/gemm_thunk.cc
CONFLICT (content): Merge conflict in tensorflow/compiler/xla/service/gpu/BUILD
CONFLICT (content): Merge conflict in tensorflow/compiler/xla/BUILD
CONFLICT (content): Merge conflict in tensorflow/compiler/jit/xla_device_ops.h
CONFLICT (add/add): Merge conflict in tensorflow/compiler/jit/xla_activity_listener_test.cc
CONFLICT (add/add): Merge conflict in tensorflow/compiler/jit/xla_activity_listener.h
CONFLICT (add/add): Merge conflict in tensorflow/compiler/jit/xla_activity_listener.cc
CONFLICT (add/add): Merge conflict in tensorflow/compiler/jit/xla_activity.proto
```

**Comment by jeffdaily** [comment]
Looking into the svd_test_gpu log, it might be stalling during `SVDTest.Various_Size_Random_Matrix_128x256`.  

```
...
[       OK ] SVDTest.Various_Size_Random_Matrix_512x128 (25258 ms)
[ RUN      ] SVDTest.Various_Size_Random_Matrix_128x256
2019-06-28 21:52:01.967616: I tensorflow/compiler/xla/service/platform_util.cc:85] platform Host present but no XLA compiler available: could not find registered compiler for platform Host -- check target      linkage (hint: try linking in tensorflow/compiler/jit:xla_cpu_jit)
2019-06-28 21:52:01.967651: I tensorflow/compiler/xla/service/platform_util.cc:85] platform Host present but no XLA compiler available: could not find registered compiler for platform Host -- check target      linkage (hint: try linking in tensorflow/compiler/jit:xla_cpu_jit)
```

**Pull request merged**
