### PR TITLE
syncing code with the upstream repo for the contents in the tensorflow/core/kernels/data directory

### PR DESCRIPTION
**Pull request by deven-amd**
copied over the code directly from the upstream repo.

there are no CUDA/ROCm specific changes here (save for one place where we add `|| TENSORFLOW_USE_ROCM`)

the eventual goal is to get the contents in `tensorflow/core/kernels` directory completely in sync with the upstrem repo, and the diffs in this dir were adding unnecessary noise, so removing them.

### CODE REVIEW

**Comment by deven-amd** [comment]
hmm...seeing the following error everywhere

```
ImportError: cannot import name 'TPUEstimator'
```

do not know what is triggering it

**Comment by deven-amd** [comment]
jenkins : retest rocm-xla please

**Comment by deven-amd** [comment]
jenkins : retest rocm please

**Comment by deven-amd** [comment]
jenkins : retest rocm-v2 please

**Comment by deven-amd** [comment]
jenkins : retest cuda please

**Comment by whchung** [comment]
@deven-amd might need to rebase for this PR to proceed.

**Comment by deven-amd** [comment]
yes...need to address the failures too :(

too many things going on....will get to this eventually :)

**Comment by deven-amd** [comment]
abandoning this, since starting from scratch will be easier.

**Pull request closed without merging**
