### PR TITLE
Prototype of MIGraph integration

### PR DESCRIPTION
**Pull request by mei-ye**
Tensorflow-MIGraph integration work.   Can run simple inference models.  But still at the stage of debugging and ongoing hand-shake with MIGraph.   Not ready to get upstreamed, but you can do a internal review.  Feel free to pull in more reviewers.

### CODE REVIEW

**Comment by ROCm-Apps-Test** [comment]
Can one of the admins verify this patch?

**Comment by ROCm-Apps-Test** [comment]
Can one of the admins verify this patch?

**Comment by whchung** [comment]
@mei-ye thanks for the contribution. i have a general understanding of the PR now. would wait for your signal when you feel it's more ready to be tested along with MIGraph. we'll need to amend CI build scripts to incorporate MIGraph then.

**Comment by parallelo** [comment]
Jenkins:  add to whitelist

**Comment by whchung** [comment]
close this PR as MIGraphX could consume TF protobuf directly

**Pull request closed without merging**
