### PR TITLE
Revise support for Math calls

### PR DESCRIPTION
**Pull request by sumesh13**
Revise this support taking into account PR merges upstream

### CODE REVIEW

**Comment by whchung** [comment]
@sumesh13 the PR looks good to me. Please revise the description so we know its associated upstream PR

**Comment by sumesh13** [comment]
> @sumesh13 the PR looks good to me. Please revise the description so we know its associated upstream PR

There is no upstream PR  for this yet. I revised this support based on how the support for intrinsics and shfl has been merged into upstream.

**Comment by whchung** [comment]
Got it. When you upstream this do we want to propose change the name of EmitLibdeviceMathcall to something more neutral such as EmitDeviceMathcall? Libdevice refers to the NV device lib.

**Comment by sumesh13** [comment]
> Got it. When you upstream this do we want to propose change the name of EmitLibdeviceMathcall to something more neutral such as EmitDeviceMathcall? Libdevice refers to the NV device lib.

Sure...I can do that ...

**Pull request merged**
