### PR TITLE
Porting AMP related changes to r1.15-rocm

### PR DESCRIPTION
**Pull request by deven-amd**
/cc @sunway513  @ekuznetsov139

### CODE REVIEW

**Comment by ROCm-Apps-Test** [comment]
Can one of the admins verify this patch?

**Comment by sunway513** [comment]
Let's see the results in the following CI run:
http://ml-ci.amd.com:21096/job/tf-develop-upstream-releases/job/tensorflow-upstream-rel1.15-enhanced-nightly/215/

**Comment by ekuznetsov139** [comment]
CI fails because it can't find packages rocm-profiler and cxlactivitylogger in the latest rocm apt repo. Perhaps tie it to 3.0 for now (further changes may be needed to make it build on 3.1 anyway)?

**Comment by sunway513** [comment]
CI result is on par with the original r1.15-rocm branch, will merge this PR. 
Thanks @deven-amd

**Pull request merged**
