### PR TITLE
Feature adopt hipLaunchKernelGGLEx

### PR DESCRIPTION
**Pull request by whchung**
This PR attempts to adopt `hipLaunchKernelGGLEx` introduced in https://github.com/ROCm-Developer-Tools/HIP/pull/994 . With the new API it helps to unify kernel launch interface between CUDA and ROCm where kernel dispatching results would always be checked by TensorFlow.

Relevant PR upstream: #24293

### CODE REVIEW

**Comment by parallelo** [comment]
ROCm build failed due to pip again.  Re-running.  (also testing `rocm-v2`)

Jenkins:  retest this please

**Comment by whchung** [comment]
@parallelo Meanwhile this PR is flawed, I'm fixing it too

**Comment by whchung** [comment]
`rocm` path works fine but `cuda` path needs to be looked at.

**Comment by whchung** [comment]
@deven-amd / @parallelo need your comments:

based on our experiences getting things upstreamed, I think we may need to change the strategy here.

instead of changing each operator to adopt `GPU_LAUNCH_KERNEL`, what if we change the internal of `CudaLaunchKernel` so it conditions upon `TENSORFLOW_USE_ROCM` and call `hipLaunchKernelGGL` on ROCm path? This should greatly reduce lines to be changed in TF operators, which should (hopefully) reduce time for it be accepted upstream.

**Pull request closed without merging**
