### PR TITLE
Develop upstream sync 190916

### PR DESCRIPTION
**Pull request by jerryyin**
Compiles fine for //tensorflow/tools/pip_package:build_pip_package

The biggest single update in the weekly merge task is in `tensorflow/python/kernel_tests/signal/fft_ops_test.py`. I kept the upstream version and added no-rocm guard to complex data type. 

-----

conflict file list:
- tensorflow/compiler/jit/BUILD
- tensorflow/compiler/xla/service/gpu/BUILD
- tensorflow/compiler/xla/service/gpu/collective_permute_thunk.cc
- tensorflow/compiler/xla/service/gpu/nvptx_compiler.cc
- tensorflow/python/BUILD
- tensorflow/python/kernel_tests/signal/fft_ops_test.py

### CODE REVIEW

**Comment by jerryyin** [comment]
Current state: 

Cuda, ROCm, ROCm-v2 failures:

- //tensorflow/python/feature_column:feature_column_test
- //tensorflow/python/feature_column:feature_column_v2_test
- //tensorflow/tools/docs:tf_doctest
- //tensorflow/python/keras/optimizer_v2:optimizer_v2_test
- //tensorflow/python/keras/optimizer_v2:optimizer_v2_test_gpu

ROCm and ROCm-v2 failures:

- //tensorflow/python/kernel_tests/linalg:linear_operator_circulant_test
- //tensorflow/python/kernel_tests/linalg:linear_operator_circulant_test_gpu

ROCm-XLA failures:

- //tensorflow/compiler/mlir/lite/tests/end2end:glob_lit_tests

**Comment by jerryyin** [comment]
Both rocm and rocm-v2 test log shows failure for `//tensorflow/python/kernel_tests/linalg:linear_operator_circulant_test`:

> ...
2019-09-17 19:33:03.575536: I tensorflow/stream_executor/stream.cc:2123] [stream=0x4ebebd0,impl=0x4ebec70] did not wait for [stream=0x4cbb7a0,impl=0x4cba950]
2019-09-17 19:33:03.575605: I tensorflow/stream_executor/stream.cc:5071] [stream=0x4ebebd0,impl=0x4ebec70] did not memcpy host-to-device; source: 0x3da86c0
2019-09-17 19:33:03.575794: F tensorflow/core/common_runtime/gpu/gpu_util.cc:340] CPU->GPU Memcpy failed
Fatal Python error: Aborted

I cannot reproduce this offline. @whchung I vaguely remember some issues regarding CPU->GPU memcpy failures last week. Should we just disable the test for now?

**Comment by whchung** [comment]
@jerryyin this test should be reviewed. normally it means something new in StreamExecutor API.

**Comment by jerryyin** [comment]
@whchung Sounds good, will try harder tomorrow.

**Comment by jerryyin** [comment]
Merging the pull request as: two commits before have a full pass CI run, the last commit merged in verified commit, and that at least one build succeed in last CI run.

**Pull request merged**
