### PR TITLE
Adding ROCm support for CTC Loss

### PR DESCRIPTION
**Pull request by deven-amd**
/cc @whchung @jerryyin @ekuznetsov139

### CODE REVIEW

**Comment by ROCm-Apps-Test** [comment]
Can one of the admins verify this patch?

**Review by jerryyin — APPROVED** [review]
Nice!

**Comment by deven-amd** [comment]
jenkins : retest rocm-xla please

**Comment by deven-amd** [comment]
only one failure in the `rocm-xla` run and it seems to one of those flaky failures.
`//tensorflow/compiler/xla/tests:transpose_test_gpu`

link to the failing run : 
http://ml-ci.amd.com:21096/job/develop-upstream-unit-tests/job/tensorflow-upstream-unit-tests-rocm-xla/1069/

**Comment by deven-amd** [comment]
rebasing PR to resolve merge conflict

**Pull request merged**
