### PR TITLE
[ROCM] adding env variable to control rocm_dnn workspace limit

### PR DESCRIPTION
**Pull request by pemeliya**
This fixes the issue: https://github.com/ROCm/frameworks-internal/issues/6958

### CODE REVIEW

**Review by jayfurmanek — APPROVED** [review]

**Review by i-chaochen — APPROVED** [review]
LGTM, I wonder do we need to upstream this to XLA as well?

**Comment by pemeliya** [comment]
> LGTM, I wonder do we need to upstream this to XLA as well?

Yes probably to XLA too.. because by default this patch does nothing, unless one defines this env variable

**Comment by jayfurmanek** [comment]
retest Ubuntu-GPU-single please

**Comment by jayfurmanek** [comment]
retest Ubuntu-CPU  please

**Comment by jayfurmanek** [comment]
> LGTM, I wonder do we need to upstream this to XLA as well?

This came from a request and I asked them to push upstream first, but that didn't happen. It's unclear if it would be accepted, as is but we can try.

**Comment by jayfurmanek** [comment]
retest Ubuntu-CPU please

**Comment by jayfurmanek** [comment]
retest Ubuntu-GPU-single please

**Comment by pemeliya** [comment]
retest Ubuntu-GPU-single please

**Comment by pemeliya** [comment]
retest Ubuntu-GPU-single please

**Comment by pemeliya** [comment]
Ubuntu-GPU-single CI job seems to have problems with a GPU driver which I saw by another TF commits as well..

**Comment by i-chaochen** [comment]
seems most of failed ones are from [sc-hw-smc-acc-17](http://ml-ci.amd.com:21096/computer/sc%2Dhw%2Dsmc%2Dacc%2D17/builds) it was ok since 5 hour ago for the build job according to the log...and it has driver problem before...
http://ml-ci.amd.com:21096/job/tensorflow/job/github-prs-rocmfork-develop-upstream/job/rocm-latest-ubuntu-gpu-single/1792/consoleFull
http://ml-ci.amd.com:21096/job/tensorflow/job/github-prs-rocmfork-develop-upstream/job/rocm-latest-ubuntu-gpu-single/1793/consoleFull


Right now is running for the weekly-sync CI. If the driver is failed there, we should take it down.

**Comment by i-chaochen** [comment]
retest Ubuntu-GPU-single please

**Comment by pemeliya** [comment]
retest Ubuntu-GPU-single please

**Comment by pemeliya** [comment]
retest Ubuntu-GPU-single please

**Pull request merged**
