### PR TITLE
Fix hip-clang build

### PR DESCRIPTION
**Pull request by yxsamliu**

### CODE REVIEW

**Comment by ROCm-Apps-Test** [comment]
Can one of the admins verify this patch?

**Comment by ROCm-Apps-Test** [comment]
Can one of the admins verify this patch?

**Comment by ROCm-Apps-Test** [comment]
Can one of the admins verify this patch?

**Comment by whchung** [comment]
jenkins: ok to test

**Comment by sunway513** [comment]
@yxsamliu please cherry-pick this fix to r1.15-rocm branch once this PR is merged, thanks.

**Pull request merged**
