### PR TITLE
[Draft] Enabling multiple kernels and unit tests

### PR DESCRIPTION
**Pull request by ekuznetsov139**
This PR enables for ROCm most kernels and C++ unit tests which are currently enabled for CUDA only, and which can be enabled without code changes or with minimal changes. 

Nontrivial changes include the following: 
* gpu_managed_allocator is implemented for ROCm (necessary for several tests).
* A number of changes are made to the implementation of reduction kernels (reduction_gpu_kernels.cu.h), primarily for the purpose of allowing complex type reductions to be executed in hipFloatComplex/hipDoubleComplex (compiler issues make using std::complex in ROCm device code very difficult).
* The number of threads/block for TopKKernel is reduced from 1024 to 256.
* A header gpuprim.h is created and a number of typedefs and macros are added to core/utils/gpu_device_functions.h.

It fixes https://github.com/ROCmSoftwarePlatform/tensorflow-internal/issues/3.

### CODE REVIEW

**Comment by ekuznetsov139** [comment]
jenkins: please retest

**Comment by ekuznetsov139** [comment]
jenkins : retest this please

**Comment by deven-amd** [comment]
@ekuznetsov139 

it will be helpful, both for our internal review and for upstreaming purposes, if this PR is broken down into multiple PRs as per functionality.

one PR / op would be ideal. It will lead to a lot of PRs, but that is ok, and the upstream guys seem to prefer it :)

**Comment by ekuznetsov139** [comment]
I'd have to expense a new keyboard because I'll wear this one down typing up 113 PRs, but okay...

**Pull request closed without merging**
