### PR TITLE
Fix timeout and run_under

### PR DESCRIPTION
**Pull request by jayfurmanek**
This was missed when moving to clang builds

### CODE REVIEW

**Comment by jayfurmanek** [comment]
retest Ubuntu-CPU please

**Comment by jayfurmanek** [comment]
retest Ubuntu-GPU-multi please

**Comment by jayfurmanek** [comment]
retest Ubuntu-CPU please
retest Ubuntu-GPU-multi please

**Comment by jayfurmanek** [comment]
retest Ubuntu-CPU please
retest Ubuntu-GPU-multi please

**Review by wenchenvincent — APPROVED** [review]
LGTM.

**Pull request merged**
