### PR TITLE
Rocm3.7 doc update

### PR DESCRIPTION
**Pull request by sunway513**
In this PR we update the whl packages built for ROCm3.7 and the corresponding installation instructions.

### CODE REVIEW

**Comment by mvermeulen** [comment]
Is the *.whl package you pick up from CSB "cp35" or "cp36", given the Python version changed?

**Comment by mvermeulen** [comment]
Is the *.whl package you pick up from CSB "cp35" or "cp36", given the Python version changed?

**Review by mvermeulen — COMMENTED** [review]
Is the wget from CSB a package named "*cp35*" or "*cp36*" given the change in python versions?

**Comment by sunway513** [comment]
@mvermeulen this document doesn't touch the CSB document. For CSB, it looks like this is what we have:
http://ml-ci.amd.com:21096/job/tensorflow-rocm-release/
http://ml-ci.amd.com:21096/job/tensorflow-rocm-v2-release/

**Comment by sunway513** [comment]
Thanks @mvermeulen , I've reverted the changes on those doc which is for CSB pkg.

**Review by mvermeulen — APPROVED** [review]

**Pull request merged**
