### PR TITLE
enabling device tracer

### PR DESCRIPTION
**Pull request by eshcherb**

### CODE REVIEW

**Comment by ROCm-Apps-Test** [comment]
Can one of the admins verify this patch?

**Comment by ROCm-Apps-Test** [comment]
Can one of the admins verify this patch?

**Comment by ROCm-Apps-Test** [comment]
Can one of the admins verify this patch?

**Comment by ROCm-Apps-Test** [comment]
Can one of the admins verify this patch?

**Comment by whchung** [comment]
@eshcherb please rebase logic in #260 and submit them here in this PR.

**Comment by eshcherb** [comment]
Yes, I see

**Comment by eshcherb** [comment]
I have rebased the logic from #260
Could you test it?

**Comment by whchung** [comment]
Jenkins: ok to test

**Comment by whchung** [comment]
@eshcherb all builds failed. please help make sure your PR at least builds on ROCm so we can help iron out the rest of the details.

**Comment by eshcherb** [comment]
Will check

**Comment by whchung** [comment]
@eshcherb is there an ETA for this PR?

**Comment by whchung** [comment]
@eshcherb per discussion underlying components have been integrated into HIP and HCC already in ROCm releases. Let me see if I could tune this PR better so it could be merged. Will ping you should I encounter issues.

**Comment by sunway513** [comment]
@eshcherb can we restart this PR?

**Comment by whchung** [comment]
will file a new PR. closing this one.

**Pull request closed without merging**
