### PR TITLE
Develop upstream sync 190701

### PR DESCRIPTION
**Pull request by jeffdaily**

### CODE REVIEW

**Comment by jeffdaily** [comment]
Test status:
- rocm, only 1 failure, //tensorflow/python/training/tracking:util_xla_test_gpu
- rocm-v2, only 1 failure, //tensorflow/python/training/tracking:util_xla_test_gpu
- rocm-xla: 
  - 8 fail to build
  - 7 fail to run

XLA seeing errors such as:
```
/usr/bin/ld: bazel-out/k8-opt/bin/external/llvm/libsupport.a(APInt.o): undefined reference to symbol 'round@@GLIBC_2.2.5'
//lib/x86_64-linux-gnu/libm.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
```
and
```
Rng should be expanded for GPU.
```

**Comment by whchung** [comment]
@jeffdaily For `Rng should be expanded for GPU.`, it's related to this commit:

```
commit 5ce1c98d49e683b125ad171cba1ece364f666e71
Author: Bixia Zheng <bixia@google.com>
Date:   Wed Jun 26 09:30:46 2019 -0700
```

**Comment by whchung** [comment]
@jeffdaily Try skip MLIR-related tests. Link errors and test errors are all related to newly released MLIR logic.

**Comment by jeffdaily** [comment]
@whchung yes I'll get a PR to mainline for the fix.

Only one test left failing.  `//tensorflow/compiler/mlir/tensorflow:error_util_test` .  I'll tag it as `no_rocm` for now.

**Comment by jeffdaily** [comment]
@whchung rocm-xla passes now that I skipped the one test.  The other three CI targets were already passing.  I think we're good to go for this week's merge.

**Pull request merged**
