### PR TITLE
Develop upstream sync 200527

### PR DESCRIPTION
**Pull request by whchung**

### CODE REVIEW

**Comment by ROCm-Apps-Test** [comment]
Can one of the admins verify this patch?

**Comment by deven-amd** [comment]
@whchung please cherry-pick the following PR to resolve the `rocm` failure

https://github.com/tensorflow/tensorflow/pull/39914

**Comment by whchung** [comment]
> @whchung please cherry-pick the following PR to resolve the `rocm` failure
> 
> [tensorflow#39914](https://github.com/tensorflow/tensorflow/pull/39914)

@deven-amd Thanks. I've revised this PR cherry-picking the commit.

**Comment by whchung** [comment]
@deven-amd, even after applying the patch those tests still fail `rocm` CI checks, any insights?

**Comment by deven-amd** [comment]
@whchung 

hmm...the test starts passing in the `upstream/master` branch after my change, but somehow the same change does not work for `develop-upstream` (based on the CI result) don't know why that is the case, will need to look into it.

in the meantime, we probably should revert to putting the no_rocm tag on it, so that we can take this PR and finish the merge.

**Comment by whchung** [comment]
@deven-amd do you prefer `no_rocm` tag in bazel script, or changing the test case Python and use `skipTest` with `is_built_with_rocm()` check?

**Comment by deven-amd** [comment]
either way is fine.

**Pull request merged**
