### PR TITLE
roctracer fix for ROCm 3.5

### PR DESCRIPTION
**Pull request by deven-amd**
Not really a new fix, rather simply enabling (by default) most of the code that was under `#if ROCTRACER_FLUSH_BUG_WORKAROUND`. With ROCm 3.5, the wait time (after the call to flush) does not seem anywhere near as bad as with ROCm 3.3.

### CODE REVIEW

**Comment by ROCm-Apps-Test** [comment]
Can one of the admins verify this patch?

**Comment by deven-amd** [comment]
one failure in `rocm`
```
//tensorflow/python/keras/distribute:keras_embedding_model_correctness_test_gpu FAILED in 3 out of 3 in 207.4s
```
http://ml-ci.amd.com:21096/job/develop-upstream-unit-tests/job/tensorflow-upstream-unit-tests/2049/console

the above is one a few test that seem to fail with more frequency on the CI nodes (though not always)...need to `no_rocm` them and then root cause them...but that will be in another PR.

will retest rocm for the time being.

**Comment by deven-amd** [comment]
jenkins : retest rocm please

**Comment by deven-amd** [comment]
the other flaky test timed-out this time :(
```
//tensorflow/python/kernel_tests:cwise_ops_test_gpu                     TIMEOUT in 3 out of 3 in 915.0s
```

http://ml-ci.amd.com:21096/job/develop-upstream-unit-tests/job/tensorflow-upstream-unit-tests/2050/console

hopefully third time will be the charm

**Comment by deven-amd** [comment]
jenkins : retest rocm please

**Comment by deven-amd** [comment]
jenkins : retest rocm please

**Pull request merged**
