### PR TITLE
Develop upstream sync 220516

### PR DESCRIPTION
**Pull request by rahulbatra85**

### CODE REVIEW

**Comment by rahulbatra85** [comment]
retest Ubuntu-GPU-multi please

**Comment by rahulbatra85** [comment]
retest Ubuntu-GPU-single please

**Comment by jayfurmanek** [comment]
https://github.com/ROCmSoftwarePlatform/frameworks-internal/issues/1651

**Comment by jayfurmanek** [comment]
https://github.com/ROCmSoftwarePlatform/frameworks-internal/issues/1692

**Comment by jayfurmanek** [comment]
retest Ubuntu-GPU-multi please

**Pull request merged**
