### PR TITLE
remove contrib/rccl

### PR DESCRIPTION
**Pull request by jeffdaily**
Remove RCCL version 1.  It was previously integrated using the contrib directory, which is removed in TF 2.0.

### CODE REVIEW

**Comment by whchung** [comment]
@jeffdaily thanks, let’s monitor CI test results

**Comment by deven-amd** [comment]
@jeffdaily 

If I remember correctly, then the `if not pywrap_tensorflow.IsBuiltWithROCm()` special casing in the following file/line
https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/blob/develop-upstream/tensorflow/python/distribute/__init__.py#L26

was needed to workaround circular python `import` dependencies, which were a consequence of `contrib/rccl`. Now that it is going away, I think we can get rid of the special casing as well.

Assuming you do not run into build errrors after removing that if statement, can I request you to add that change to this PR.

Thanks

deven

**Comment by jeffdaily** [comment]
@deven-amd Done.  I removed the special case in the file you indicated.

**Comment by whchung** [comment]
@jeffdaily weird. the purpose of this PR is to remove RCCL and embrace for TF v2, but `rocm-v2` is the only failing path. any insights?

**Comment by jeffdaily** [comment]
Looking at the full log output, I'm seeing 994 cases of `Cannot find a free GPU to run the test  on, exiting with failure...`.

**Comment by whchung** [comment]
@jeffdaily on the latest run we are seeing a lot of errors:

http://ml-ci.amd.com:21096/job/tensorflow-upstream-unit-tests-rocm-v2/64/console

on the other hand, if we take a look at the previous run it passes:

http://ml-ci.amd.com:21096/job/tensorflow-upstream-unit-tests-rocm-v2/63/console

does it mean commit https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/pull/400/commits/9d38319630e9dd6ddddcb9753bb59b5d33fda3b4 works, but commit https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/pull/400/commits/16b658437c2d1821eb06273c785ecae9aa4465ba brought undesirable side effects?

**Comment by jeffdaily** [comment]
Interesting.  Should I revert the commit @deven-amd requested and try again?  Or should we triage why https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/commit/16b658437c2d1821eb06273c785ecae9aa4465ba does not work?

**Comment by whchung** [comment]
@jeffdaily I believe the 2nd commit may have to be changed, if you compare with upstream you can see the number and order of imports are actually different:

this PR:
https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/pull/400/commits/16b658437c2d1821eb06273c785ecae9aa4465ba

upstream:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/distribute/__init__.py

**Comment by whchung** [comment]
i take back my earlier comment. it was wrong.

**Comment by whchung** [comment]
@jeffdaily I compared the logic with upstream and added a couple of commits. Let's monitor this build:

http://ml-ci.amd.com:21096/job/tensorflow-upstream-unit-tests-rocm-v2/74/

**Comment by jeffdaily** [comment]
> @jeffdaily I compared the logic with upstream and added a couple of commits. Let's monitor this build:
> 
> http://ml-ci.amd.com:21096/job/tensorflow-upstream-unit-tests-rocm-v2/74/

Sincerely sorry @whchung that you had to beat me to it.

**Comment by jeffdaily** [comment]
I'm seeing a warning in the log, possibly unrelated.  I looked at the offending file in the latest develop-upstream branch and it looks like it has been fixed already, but not part of this PR.
```
./tensorflow/core/kernels/reduction_gpu_kernels.cu.h:290:20: warning: extra tokens at end of #ifdef directive [-Wextra-tokens]
#ifdef GOOGLE_CUDA || __HIP__
```

**Comment by whchung** [comment]
> I'm seeing a warning in the log, possibly unrelated. I looked at the offending file in the latest develop-upstream branch and it looks like it has been fixed already, but not part of this PR.
> 
> ```
> ./tensorflow/core/kernels/reduction_gpu_kernels.cu.h:290:20: warning: extra tokens at end of #ifdef directive [-Wextra-tokens]
> #ifdef GOOGLE_CUDA || __HIP__
> ```

I just submitted and merged #406 to address this.

**Pull request merged**
