### PR TITLE
Adding MIOpen 3d convolution support

### PR DESCRIPTION
**Pull request by jerryyin**
This pull request add ROCm 3d convolution support by pulling in newest 3d convolution APIs from MIOpen. The newly added APIs are: 

- [miopenInitConvolutionNdDescriptor](https://github.com/AMDComputeLibraries/MLOpen/blob/develop/include/miopen/miopen.h#L623)
- [miopenGetConvolutionNdDescriptor](https://github.com/AMDComputeLibraries/MLOpen/blob/develop/include/miopen/miopen.h#L665)
- [miopenGetConvolutionNdForwardOutputDim ](https://github.com/AMDComputeLibraries/MLOpen/blob/develop/include/miopen/miopen.h#L759)
- [miopenSetTransposeConvNdOutputPadding](https://github.com/AMDComputeLibraries/MLOpen/blob/develop/include/miopen/miopen.h#L715)

Test run:
- Regressed all currently running conv2d tests and all are passing
- Regressed conv3d tests and are all passing

### CODE REVIEW

**Comment by jerryyin** [comment]
FYI, rocm build failed due to new convolutionNd APIs are not available in jenkins environment

**Comment by whchung** [comment]
@jerryyin could you revise "dropbox" package used inside `Dockerfile.rocm`, adding updated MIOpen package so we can see updated test results on `rocm` path?

**Comment by whchung** [comment]
https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/blob/develop-upstream/tensorflow/tools/ci_build/Dockerfile.rocm#L104

**Comment by jerryyin** [comment]
jenkins: ok to test

**Comment by jerryyin** [comment]
jenkins: ok to test

**Comment by jerryyin** [comment]
The CI helped me to exercised the miopenGetConvolutionNdDescriptor() API. Signature pasted below:

> /*! @brief Retrieves a N-dimensional convolution layer descriptor's details
      * @param convDesc   Convolution layer descriptor (input)
      * @param c_mode     Convolutional mode (output)
      * @param convDim    Convolutional dimension (output)
      * @param padA       Array of input data padding (output)
      * @param strideA    Array of convolution stride (output)
      * @param dilationA  Array of convolution dilation (output)
      * @return           miopenStatus_t
      */
     MIOPEN_EXPORT miopenStatus_t
     miopenGetConvolutionNdDescriptor(miopenConvolutionDescriptor_t convDesc,
                                 miopenConvolutionMode_t* c_mode,
                                 int* convDim,
                                 int* padA,
                                 int* strideA,
                                 int* dilationA);

According to the API description, convDim is an output, and it will be used to help determine the size of padA, strideA and dilationA arrays. Now the question is how to pre-allocate the correct size of the three arrays before making this API call. Looks like miopen crashes on my existing solution.

Will talk to Chao on his opinion of using the API and post back.

**Comment by jerryyin** [comment]
jenkins: ok to test

**Comment by jerryyin** [comment]
jenkins: ok to test

**Comment by jerryyin** [comment]
According to the test log, the failure is in batch_matmul_op_test only. It is caused by a failed BLAS (xGEMMBatched) call from rocm_blas.cc. 

Looking at the merge conflict, I didn't see any file related with batch_matmul yet. Will need to do local reproduce and debug.

**Comment by whchung** [comment]
@jer I think the PR is getting matured. Relevant 3D convolution tests seem to be passing. But we do need to address why the following tests are failing of being flaky:

```
//tensorflow/python/kernel_tests:pooling_ops_test_gpu
//tensorflow/python/kernel_tests:pooling_ops_test
//tensorflow/python/kernel_tests:conv_ops_test_gpu
//tensorflow/python/kernel_tests:conv_ops_test
```

**Comment by jerryyin** [comment]
@whchung It is an upstream bug [here](https://github.com/tensorflow/tensorflow/pull/18423#pullrequestreview-222299243). I am still looking into more issues into this pooling_ops_test just yet.

**Comment by jerryyin** [comment]
The current investigation is related with the environment variable. In #364, we disabled the case when TF_ENABLE_MAXPOOL_NANPROP == 1, but keep the case of TF_ENABLE_MAXPOOL_NANPROP == 0. 

Right now what happens is just the opposite, TF_ENABLE_MAXPOOL_NANPROP == 0 failed, but TF_ENABLE_MAXPOOL_NANPROP == 1 passed.

Right now, my theory is because MIOpen does not have the control over whether/not to propagate Nan values in a matrix. It therefore has some level of in-determinism and make the actual result differ from case to case.

Several things to verify:

- Make sure MIOpen does not support the toggle between propagation of Nans.
    - If it is the case, make sure there is some in-determinism in whether Nan will be propogated or not in actual runtime
- Make a decision on whether we should escalate this to be a feature request to MIOpen

**Comment by jerryyin** [comment]
Documenting the discussion result with @asroy in case we don't remember the decision.

[cudnnNanPropagation_t ](https://docs.nvidia.com/deeplearning/sdk/cudnn-developer-guide/index.html#cudnnNanPropagation_t) is a feature exist in cudnn. This descriptor field provides deterministic result when doing maxPooling related operations, for example, [cudnnPoolingBackward](https://docs.nvidia.com/deeplearning/sdk/cudnn-developer-guide/index.html#cudnnPoolingBackward). According to the documentation from cuda, this determinism comes with a price, quoted 

> The deterministic algorithm has been measured to be up to 50% slower than the legacy max backwards pooling algorithm, or up to 20% faster, depending upon the use case.

On the other hand, MIOpen never supports the Nan propagation related field before. This means in-determinism When there is Nan in the input. Use case wise, after a quick brainstorm, we don't find a particular valuable use case in regular calculation. On specific case we can think of is to help user track the appearance of Nan in calculation, in case pooling creates a "breakpoint" when it returns all dx as zero.

The current decision is that MIOpen do not support the Nan propagation unless we find a valuable use case. On our TF side, we will disable Nan related test in pooling backward operations.

Feel free to comment further if you have anything to add @asroy

**Comment by jerryyin** [comment]
Current CI result shows 1 infrastructure failure and 3 all passing. Considering the previous all-passing result in commit 8bd05df [ROCm-v2 result](http://ml-ci.amd.com:21096/job/tensorflow-upstream-unit-tests-rocm-v2/97/). I'm fairly confident with this PR now.

**Comment by jerryyin** [comment]
Amended the commit 9661dab according to @deven-amd comments. We should keep the CPU implementation which propogates Nans.

**Comment by whchung** [comment]
@jerryyin do you feel comfortable hitting the merge button now?

**Comment by jerryyin** [comment]
@whchung Feature wise I think so. Let me do a last sanity check on the dependency change in Dockerfile.rocm. Once that is done, and if you are okay with it, I can go ahead and hit the merge.

**Comment by deven-amd** [comment]
@jerryyin just to confirm, the MIOpen version that comes ROCm 2.3 has everything we need for 3d conv support...correct?

I ask because the `Dockerfile.rocm` changes from PR 411 conflict with the change in this PR. When PR 411 is ready to merge, my understanding is that we should use the `Dockerfile.rocm` from that PR (which uses MIOpen from ROCm 2.3) to over-ride the `Dockerfile.rocm` from this PR.

**Comment by jerryyin** [comment]
@deven-amd Your understanding is correct. Use your Dockerfile.rocm instead of this one.

**Pull request merged**
