### PR TITLE
Fixing logical order of operations for selecting NHWC in non-xla path.

### PR DESCRIPTION
**Pull request by stevenireeves**

### CODE REVIEW

**Comment by jayfurmanek** [comment]
Will try this to confirm.

**Review by jayfurmanek — APPROVED** [review]
Looks good. And this fixes the perf regression in tf_cnn_benchmark in ROCm 5.2 (the fastNHWC stuff is not ready to use yet)

**Comment by jayfurmanek** [comment]
We'll need this cherry-picked over to the `develop-upstream-QA-rocm52` branch as well.

**Comment by jayfurmanek** [comment]
https://github.com/ROCmSoftwarePlatform/frameworks-internal/issues/1226

**Comment by stevenireeves** [comment]
@deven-amd we will need these upstreamed as well.

**Pull request merged**
