### PR TITLE
Develop upstream sync 200302

### PR DESCRIPTION
**Pull request by deven-amd**

### CODE REVIEW

**Comment by ROCm-Apps-Test** [comment]
Can one of the admins verify this patch?

**Comment by deven-amd** [comment]
jenkins : retest this please

**Comment by deven-amd** [comment]
links to failing logs (before the retest command)...all failures have the following error

```
[91mE: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/j/json-c/libjson-c2_0.11-4ubuntu2_amd64.deb  Temporary failure resolving 'archive.ubuntu.com'

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

```

http://ml-ci.amd.com:21096/job/develop-upstream-unit-tests/job/tensorflow-upstream-unit-tests-rocm-cpp/382/

http://ml-ci.amd.com:21096/job/develop-upstream-unit-tests/job/tensorflow-upstream-unit-tests-rocm-xla/1163/

http://ml-ci.amd.com:21096/job/develop-upstream-unit-tests/job/tensorflow-upstream-unit-tests/1808/console

**Comment by deven-amd** [comment]
jenkins: retest rocm-cpp please

**Comment by deven-amd** [comment]
jenkins: retest rocm-cpp please

**Comment by deven-amd** [comment]
jenkins: retest rocm-cpp please

**Comment by deven-amd** [comment]
jenkins: retest rocm-cpp please

**Pull request merged**
