### PR TITLE
Develop upstream sync 191104

### PR DESCRIPTION
**Pull request by parallelo**
Upstream merge from Nov 4th 2019.  In addition to grabbing upstream commits, we also cherry-picked Deven's fix for the CSB's broken build system (upstream PR #33896).  

This current config builds successfully on my local machine.  

```
# git merge upstream/master --no-edit
Removing third_party/mlir/tools/mlir-tblgen/EnumsGen.h
Auto-merging third_party/mlir/BUILD
Auto-merging third_party/gpus/cuda/build_defs.bzl.tpl
Auto-merging tensorflow/tools/ci_build/install/install_pip_packages.sh
CONFLICT (content): Merge conflict in tensorflow/tools/ci_build/install/install_pip_packages.sh
Auto-merging tensorflow/tensorflow.bzl
CONFLICT (content): Merge conflict in tensorflow/tensorflow.bzl
Auto-merging tensorflow/python/platform/stacktrace_handler_wrapper.cc
Auto-merging tensorflow/python/ops/math_ops.py
Auto-merging tensorflow/python/ops/math_grad.py
Auto-merging tensorflow/python/kernel_tests/control_flow_ops_py_test.py
Auto-merging tensorflow/python/eager/forwardprop_test.py
Auto-merging tensorflow/python/debug/BUILD
Auto-merging tensorflow/python/BUILD
Auto-merging tensorflow/lite/python/BUILD
Auto-merging tensorflow/lite/profiling/memory_info.cc
Auto-merging tensorflow/lite/kernels/internal/BUILD
Auto-merging tensorflow/lite/kernels/BUILD
Removing tensorflow/lite/delegates/gpu/cl/kernels/sigmoid_test.cc
Removing tensorflow/lite/delegates/gpu/cl/kernels/sigmoid.h
Removing tensorflow/lite/delegates/gpu/cl/kernels/sigmoid.cc
Removing tensorflow/lite/delegates/gpu/cl/kernels/hard_swish_test.cc
Removing tensorflow/lite/delegates/gpu/cl/kernels/hard_swish.h
Removing tensorflow/lite/delegates/gpu/cl/kernels/abs_test.cc
Removing tensorflow/lite/delegates/gpu/cl/kernels/abs.h
Removing tensorflow/core/lib/gtl/stl_util.h
Auto-merging tensorflow/core/kernels/conv_grad_shape_utils.cc
Auto-merging tensorflow/core/kernels/conv_grad_ops_3d.cc
Auto-merging tensorflow/core/kernels/conv_grad_input_ops.cc
Auto-merging tensorflow/core/kernels/conv_grad_filter_ops.cc
Auto-merging tensorflow/core/kernels/BUILD
Auto-merging tensorflow/core/grappler/optimizers/BUILD
Auto-merging tensorflow/core/common_runtime/gpu/gpu_device.cc
Auto-merging tensorflow/core/BUILD
Removing tensorflow/compiler/xrt/client/xrt_tf_client.h
Removing tensorflow/compiler/xrt/client/xrt_tf_client.cc
Removing tensorflow/compiler/xrt/client/xrt_grpc_eager_client.h
Removing tensorflow/compiler/xrt/client/xrt_grpc_eager_client.cc
Removing tensorflow/compiler/xrt/client/xrt_client_test.cc
Removing tensorflow/compiler/xrt/client/xrt_client.h
Removing tensorflow/compiler/xrt/client/xrt_client.cc
CONFLICT (modify/delete): tensorflow/compiler/xrt/client/BUILD deleted in upstream/master and modified in HEAD. Version HEAD of tensorflow/compiler/xrt/client/BUILD left in tree.
Auto-merging tensorflow/compiler/xla/tests/test_macros.h
Auto-merging tensorflow/compiler/xla/tests/select_and_scatter_test.cc
Auto-merging tensorflow/compiler/xla/tests/BUILD
Removing tensorflow/compiler/xla/service/reduce_precision_insertion_test.cc
Removing tensorflow/compiler/xla/service/reduce_precision_insertion.h
Removing tensorflow/compiler/xla/service/reduce_precision_insertion.cc
Auto-merging tensorflow/compiler/xla/service/llvm_ir/ir_array.cc
Auto-merging tensorflow/compiler/xla/service/hlo_parser_test.cc
Auto-merging tensorflow/compiler/xla/service/gpu/tests/BUILD
Auto-merging tensorflow/compiler/xla/service/gpu/BUILD
Removing tensorflow/compiler/xla/service/cpu/runtime_matvec.h
Removing tensorflow/compiler/xla/service/cpu/disassembler.h
Removing tensorflow/compiler/xla/service/cpu/disassembler.cc
Auto-merging tensorflow/compiler/xla/service/BUILD
Removing tensorflow/compiler/xla/python/xrt_test.py
Removing tensorflow/compiler/xla/python/xrt.py
Removing tensorflow/compiler/xla/python/xrt.cc
Auto-merging tensorflow/compiler/xla/client/lib/BUILD
Auto-merging tensorflow/compiler/xla/BUILD
Auto-merging tensorflow/compiler/tests/BUILD
Auto-merging tensorflow/compiler/mlir/tensorflow/BUILD
Removing tensorflow/compiler/mlir/g3doc/tfl_ops.md
Removing tensorflow/compiler/mlir/g3doc/tf_ops.md
Removing tensorflow/compiler/mlir/g3doc/overview.md
Removing tensorflow/compiler/mlir/g3doc/images/mlir-infra.svg
Removing tensorflow/compiler/mlir/g3doc/dialects.md
Removing tensorflow/compiler/mlir/g3doc/_project.yaml
Removing tensorflow/compiler/mlir/g3doc/_index.yaml
Removing tensorflow/compiler/mlir/g3doc/_book.yaml
Removing tensorflow/compiler/mlir/g3doc/README.md
Auto-merging configure.py
Auto-merging README.md
Automatic merge failed; fix conflicts and then commit the result.
```

### CODE REVIEW

**Comment by parallelo** [comment]
Testing `run_py3_core.sh` on a local machine with `rocm/tensorflow-autobuilds:rocm2.8-0d1893f` shows this:
```
//tensorflow/python:file_io_test                                         FAILED in 3 out of 3 in 4.9s
//tensorflow/python/debug:debugger_cli_common_test                       FAILED in 3 out of 3 in 4.0s

Executed 1246 out of 1246 tests: 1244 tests pass and 2 fail locally.
INFO: Build completed, 2 tests FAILED, 22076 total actions
```
However, the CI for `rocm` shows a different story:
```
Executed 1201 out of 1242 tests: 2 tests pass, 41 fail to build and 1199 fail locally.
```

Need to investigate the differences here..

**Comment by parallelo** [comment]
jenkins: retest this please

**Comment by parallelo** [comment]
Just merged PR https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/pull/698 into `develop-upstream` which should take care of all the post-merge build errors we've been seeing for this upstream-sync.

**Comment by parallelo** [comment]
Current status --

[**rocm**](http://ml-ci.amd.com:21096/job/develop-upstream-unit-tests/job/tensorflow-upstream-unit-tests/1470/console)
```
Executed 1248 out of 1248 tests: 1248 tests pass.
```

[**rocm-cpp**](http://ml-ci.amd.com:21096/job/develop-upstream-unit-tests/job/tensorflow-upstream-unit-tests-rocm-cpp/41/)
```
Executed 860 out of 860 tests: 860 tests pass.
```

[**rocm-xla**](http://ml-ci.amd.com:21096/job/develop-upstream-unit-tests/job/tensorflow-upstream-unit-tests-rocm-xla/806/)
```
Executed 791 out of 808 tests: 646 tests pass,17 fail to build and 145 fail locally
```
[**cuda**](http://ml-ci.amd.com:21096/job/develop-upstream-unit-tests/job/tensorflow-upstream-unit-tests-nvidia/1204)
```
Executed 1309 out of 1309 tests: 1309 tests pass.
```

**Comment by parallelo** [comment]
New experimental results:  The `rocm-xla` errors are specific to this PR's branch, as opposed to the widespread previous (now fixed) errors which were related to the merging of this PR's branch into `develop-upstream`.

**Comment by parallelo** [comment]
Pretty sure all of these missing symbol errors are related to this commit:  https://github.com/tensorflow/tensorflow/commit/f58c9f835c32e02895bdd629c7660567ae011001

Some recent similar observations are here:  https://github.com/tensorflow/tensorflow/issues/33959

**Comment by parallelo** [comment]
For the only remaining failures (i.e. in `rocm-xla`), this https://github.com/tensorflow/tensorflow/commit/d8325fafd45ab8efdf6ffd99a01b3c50b85d629a is needed to avoid undefined symbol errors.  Now waiting on CI results..

**Comment by parallelo** [comment]
After the last fix for the undefined symbol, `rocm-xla` is now in much better shape:
```
Executed 807 out of 808 tests: 804 tests pass, 1 fails to build, 3 fail locally
```
```
//tensorflow/compiler/xla/tests:dot_operation_single_threaded_runtime_test_gpu FAILED in 3 out of 3 in 241.6s
//tensorflow/compiler/xla/tests:dot_operation_test_autotune_disabled_gpu FAILED in 3 out of 3 in 238.1s
//tensorflow/compiler/xla/tests:dot_operation_test_gpu FAILED in 3 out of 3 in 238.1s
```

The last change shouldn't have any effect on the others (`rocm`, `rocm-cpp`, `cuda`).  They should still pass.

**Comment by parallelo** [comment]
String-related build errors are fixed with newest commit.  

The only 3 remaining errors are related to `//tensorflow/compiler/xla/tests:dot_operation*`

**Comment by parallelo** [comment]
Newest local results show only 2 failures:
```
//tensorflow/compiler/xla/tests:dot_operation_single_threaded_runtime_test_gpu FAILED in 3 out of 3 in 223.1s
//tensorflow/compiler/xla/tests:dot_operation_test_autotune_disabled_gpu FAILED in 3 out of 3 in 222.7s
```
This float16 error signature occurs on both:
```
[==========] 941 tests from 21 test suites ran. (220806 ms total)
[  PASSED  ] 933 tests.
[  FAILED  ] 8 tests, listed below:
[  FAILED  ] DotTests/ParametricDotTestWithoutLayoutAssignment.TestF16/130x290x1_MajorToMinorTTT, where GetParam() = 16-byte object <82-00 00-00 22-01 00-00 01-00 00-00 01-01 01-01>
[  FAILED  ] DotTests/ParametricDotTestWithoutLayoutAssignment.TestF16/130x290x1_MajorToMinorTT, where GetParam() = 16-byte object <82-00 00-00 22-01 00-00 01-00 00-00 01-01 00-01>
[  FAILED  ] DotTests/ParametricDotTestWithoutLayoutAssignment.TestF16/130x290x1_MajorToMinorTFT, where GetParam() = 16-byte object <82-00 00-00 22-01 00-00 01-00 00-00 01-00 01-01>
[  FAILED  ] DotTests/ParametricDotTestWithoutLayoutAssignment.TestF16/130x290x1_MajorToMinorTF, where GetParam() = 16-byte object <82-00 00-00 22-01 00-00 01-00 00-00 01-00 00-01>
[  FAILED  ] DotTests/ParametricDotTestWithoutLayoutAssignment.TestF16/130x290x1_MajorToMinorFTT, where GetParam() = 16-byte object <82-00 00-00 22-01 00-00 01-00 00-00 00-01 01-01>
[  FAILED  ] DotTests/ParametricDotTestWithoutLayoutAssignment.TestF16/130x290x1_MajorToMinorFT, where GetParam() = 16-byte object <82-00 00-00 22-01 00-00 01-00 00-00 00-01 00-01>
[  FAILED  ] DotTests/ParametricDotTestWithoutLayoutAssignment.TestF16/130x290x1_MajorToMinorFFT, where GetParam() = 16-byte object <82-00 00-00 22-01 00-00 01-00 00-00 00-00 01-01>
[  FAILED  ] DotTests/ParametricDotTestWithoutLayoutAssignment.TestF16/130x290x1_MajorToMinorFF, where GetParam() = 16-byte object <82-00 00-00 22-01 00-00 01-00 00-00 00-00 00-01>

 8 FAILED TESTS
  YOU HAVE 2 DISABLED TESTS
```

**Comment by deven-amd** [comment]
hmm....`rocm-xla` now has a new failure in it

```
//tensorflow/compiler/xla/tests:dot_operation_test_gpu                   FAILED in 3 out of 3 in 248.4s
```

the more surpsising part is that this test did not fail in the previous run. This test and the two that I add the `no_rocm` tag on, are all using the same file for testing. 

Anyway, I will add the `no_rocm` tag to the third test, and kcik off CI again.

Failing `rocm-xla` run link for future reference : 
http://ml-ci.amd.com:21096/job/develop-upstream-unit-tests/job/tensorflow-upstream-unit-tests-rocm-xla/811/ 
(the link from within the red x, will go away, since I will force push the next commit )

**Pull request merged**
