### PR TITLE
Change rocdl path to /opt/rocm/lib 

### PR DESCRIPTION
**Pull request by sumesh13**
With updated hcc, this wont be needed

### CODE REVIEW

**Comment by deven-amd** [comment]
the error in `rocm-v2` is due to package install error for `grpcio` , and can be ignored.

I will be adding a commit to this PR to remove tests that start passing after this fix, please wait for that before excepting this PR. thanks

**Comment by sumesh13** [comment]
retest this please

**Comment by deven-amd** [comment]
jenkins : retest this please

**Comment by deven-amd** [comment]
jenkins : retest this please

**Comment by deven-amd** [comment]
jenkins : retest this please

**Comment by deven-amd** [comment]
jenkins : retest this please

**Comment by deven-amd** [comment]
finally a green check mark on `rocm-xla`....this PR is good to go!

**Pull request merged**
