### PR TITLE
Upstream merge  sync 190225

### PR DESCRIPTION
**Pull request by sumesh13**
Upstream merge 190225

### CODE REVIEW

**Comment by ROCm-Apps-Test** [comment]
Can one of the admins verify this patch?

**Comment by ROCm-Apps-Test** [comment]
Can one of the admins verify this patch?

**Comment by whchung** [comment]
Jenkins: ok to test

**Comment by whchung** [comment]
jenkins: retest this please

**Comment by whchung** [comment]
@sumesh13 It seems the PR is not ready yet and fails the build:
http://ml-ci.amd.com:21096/job/tensorflow-upstream-unit-tests/680/consoleFull

Have you verified it locally before submitting the PR?

**Comment by sumesh13** [comment]
> @sumesh13 It seems the PR is not ready yet and fails the build:
> http://ml-ci.amd.com:21096/job/tensorflow-upstream-unit-tests/680/consoleFull
> 
> Have you verified it locally before submitting the PR?

I verified the build, not the unit tests. How do I access the path ?

**Comment by whchung** [comment]
@sumesh13 The logic credentials have been sent to you separately. As I explained in the online chat, the log seems to suggest we are failing due to StreamExecutor trying to load HIP runtime dynamically. Dynamic loading ROCm components is NOT in stock ROCm release yet (planned in ROCm 2.3), so you might need to tune those corresponding SE logic so we still using dynamic linking.

**Comment by whchung** [comment]
@sumesh13 any updates on this PR?

**Comment by sumesh13** [comment]
> @sumesh13 any updates on this PR?

I have pushed fixes to enable only dynamic linking. Am running some local verification - some tests I tried seem fine.

**Comment by whchung** [comment]
Jenkins: retest this please

**Comment by whchung** [comment]
@sumesh13 how’s the PR looking now?

**Comment by sumesh13** [comment]
> @sumesh13 how’s the PR looking now?

Am looking through some fails...there are bunch of tests like //tensorflow/tools/docs:build_docs_test

that fail with 

/org_tensorflow/tensorflow/python/summary/summary.py", line 48, in <module>
    from tensorflow.python.summary.writer.writer import FileWriter
ImportError: cannot import name 'FileWriter'


Am looking into it ...

**Comment by deven-amd** [comment]
> > @sumesh13 how’s the PR looking now?
> 
> Am looking through some fails...there are bunch of tests like //tensorflow/tools/docs:build_docs_test
> 
> that fail with
> 
> /org_tensorflow/tensorflow/python/summary/summary.py", line 48, in
> from tensorflow.python.summary.writer.writer import FileWriter
> ImportError: cannot import name 'FileWriter'
> 
> Am looking into it ...

That sounds familiar...think I ran into the same in a previous merge. 

https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/pull/326/commits/92eca877547c8ace466b3754b7d562310b925bd0

There is circular import dependency that gets introduced on the ROCm side somewhere, and we need to break it. Look at the entire error message, and you should be able to see what the circular import dependency.

**Comment by whchung** [comment]
Jenkins: retest this please

**Comment by sumesh13** [comment]
Am down to following fails..the first 4 are new tests and the fifth one is assertion on bazel rules some python init files. While I do have fix for the assertion, wary if they will cause other fails. 

These are the fails - can we add these to whitelist 

//tensorflow/python/keras:convolutional_recurrent_test
//tensorflow/python:nn_test      
//tensorflow/python:nn_test_gpu 
//tensorflow/python/keras:training_arrays_test
//tensorflow/python/tools/api/generator:output_init_files_test

**Comment by whchung** [comment]
@sumesh13 thanks for staying on top of this. Let’s put these tests into the whitelist

**Comment by sumesh13** [comment]
Updated the white list

**Comment by whchung** [comment]
Jenkins: retest this please

**Comment by whchung** [comment]
@sumesh13 thanks for getting this PR finally merged. time to start another round? ;)

**Comment by sumesh13** [comment]
Let me come back after a bit for the next round... :) ..

**Comment by whchung** [comment]
@sumesh13 ping. could you help advise when a new PR for upstream sync be in place?

**Comment by sumesh13** [comment]
Am hoping today...have 2 things remaining 
1. About 10  run fails - some may be new tests
2. Rebase for the recent merge

**Pull request merged**
