### PR TITLE
Develop upstream sync 221226

### PR DESCRIPTION
**Pull request by jayfurmanek**

### CODE REVIEW

**Comment by jayfurmanek** [comment]
retest Ubuntu-GPU-single please

**Comment by jayfurmanek** [comment]
retest Ubuntu-CPU please

**Comment by jayfurmanek** [comment]
retest Ubuntu-CPU please

**Comment by jayfurmanek** [comment]
retest Ubuntu-sanity please

**Comment by jayfurmanek** [comment]
retest Ubuntu-CPU please

**Comment by jayfurmanek** [comment]
retest Ubuntu-GPU-multi please

**Comment by jayfurmanek** [comment]
please Ubuntu-GPU-single please

**Comment by jayfurmanek** [comment]
retest Ubuntu-sanity please

**Comment by jayfurmanek** [comment]
retest Ubuntu-CPU please

**Comment by jayfurmanek** [comment]
retest Ubuntu-sanity please

**Comment by jayfurmanek** [comment]
retest Ubuntu-GPU-single please

**Comment by jayfurmanek** [comment]
retest Ubuntu-GPU-multi please

**Review by rsanthanam-amd — APPROVED** [review]

**Comment by i-chaochen** [comment]
retest Ubuntu-CPU please

retest Ubuntu-GPU-single please


retest Ubuntu-GPU-multi please


retest Ubuntu-sanity please

**Pull request merged**
