### PR TITLE
Bumping up TESTS_PER_GPU from 1 to 4

### PR DESCRIPTION
**Pull request by deven-amd**

### CODE REVIEW

**Comment by ROCm-Apps-Test** [comment]
Can one of the admins verify this patch?

**Comment by deven-amd** [comment]
`rocm-cpp` run has one failure
```
//tensorflow/c/eager:c_api_cluster_test                                  FAILED in 3 out of 3 in 21.5s
```

failing `rocm-cpp` run
http://ml-ci.amd.com:21096/job/develop-upstream-unit-tests/job/tensorflow-upstream-unit-tests-rocm-cpp/628/

**Comment by deven-amd** [comment]
jenkins : retest rocm-cpp please

**Comment by deven-amd** [comment]
links to passing logs - round 1

http://ml-ci.amd.com:21096/job/develop-upstream-unit-tests/job/tensorflow-upstream-unit-tests/2056/
http://ml-ci.amd.com:21096/job/develop-upstream-unit-tests/job/tensorflow-upstream-unit-tests-rocm-cpp/629/
http://ml-ci.amd.com:21096/job/develop-upstream-unit-tests/job/tensorflow-upstream-unit-tests-rocm-xla/1419/

**Comment by deven-amd** [comment]
jenkins : retest this please

**Comment by deven-amd** [comment]
links to passing logs - round 2

http://ml-ci.amd.com:21096/job/develop-upstream-unit-tests/job/tensorflow-upstream-unit-tests/2057/
http://ml-ci.amd.com:21096/job/develop-upstream-unit-tests/job/tensorflow-upstream-unit-tests-rocm-cpp/630/
http://ml-ci.amd.com:21096/job/develop-upstream-unit-tests/job/tensorflow-upstream-unit-tests-rocm-xla/1420/

**Comment by deven-amd** [comment]
jenkins : retest this please

**Comment by deven-amd** [comment]
`rocm` run has two fails
```
//tensorflow/python/kernel_tests:linalg_grad_test_gpu                    FAILED in 3 out of 3 in 915.0s
//tensorflow/python/kernel_tests/linalg/sparse:csr_sparse_matrix_sparse_mat_mul_grad_test FAILED in 3 out of 3 in 110.5s
```
failing `rocm` run
http://ml-ci.amd.com:21096/job/develop-upstream-unit-tests/job/tensorflow-upstream-unit-tests/2058/console

**Comment by deven-amd** [comment]
jenkins : retest rocm please

**Comment by deven-amd** [comment]
links to passing logs - round 3

http://ml-ci.amd.com:21096/job/develop-upstream-unit-tests/job/tensorflow-upstream-unit-tests/2059/
http://ml-ci.amd.com:21096/job/develop-upstream-unit-tests/job/tensorflow-upstream-unit-tests-rocm-cpp/631/
http://ml-ci.amd.com:21096/job/develop-upstream-unit-tests/job/tensorflow-upstream-unit-tests-rocm-xla/1421/

**Comment by deven-amd** [comment]
jenkins : retest rocm please

**Comment by deven-amd** [comment]
jenkins : retest this please

**Comment by deven-amd** [comment]
two failures in `rocm` this time

```
//tensorflow/python/keras/distribute:keras_premade_models_test          TIMEOUT in 3 out of 3 in 915.0s
//tensorflow/python/kernel_tests/linalg/sparse:csr_sparse_matrix_sparse_mat_mul_grad_test_gpu FAILED in 3 out of 3 in 101.2s
```

link to failing run
http://ml-ci.amd.com:21096/job/develop-upstream-unit-tests/job/tensorflow-upstream-unit-tests/2062/

**Comment by deven-amd** [comment]
jenkins : retest rocm please

**Comment by deven-amd** [comment]
links to passing logs - round 4

http://ml-ci.amd.com:21096/job/develop-upstream-unit-tests/job/tensorflow-upstream-unit-tests/2066/
http://ml-ci.amd.com:21096/job/develop-upstream-unit-tests/job/tensorflow-upstream-unit-tests-rocm-cpp/636/
http://ml-ci.amd.com:21096/job/develop-upstream-unit-tests/job/tensorflow-upstream-unit-tests-rocm-xla/1425/

**Comment by deven-amd** [comment]
one failure in rocm
```
//tensorflow/python/kernel_tests/linalg/sparse:csr_sparse_matrix_sparse_mat_mul_grad_test FAILED in 3 out of 3 in 89.6s
```
http://ml-ci.amd.com:21096/job/develop-upstream-unit-tests/job/tensorflow-upstream-unit-tests/2073/console

**Comment by deven-amd** [comment]
jenkins : retest rocm please

**Comment by deven-amd** [comment]
links to passing logs - round 5

http://ml-ci.amd.com:21096/job/develop-upstream-unit-tests/job/tensorflow-upstream-unit-tests/2074/
http://ml-ci.amd.com:21096/job/develop-upstream-unit-tests/job/tensorflow-upstream-unit-tests-rocm-cpp/643/
http://ml-ci.amd.com:21096/job/develop-upstream-unit-tests/job/tensorflow-upstream-unit-tests-rocm-xla/1432/

**Comment by deven-amd** [comment]
jenkins : retest this please

**Comment by deven-amd** [comment]
rocm failures
```
//tensorflow/python/kernel_tests:tensordot_op_test_gpu                   FAILED in 3 out of 3 in 137.6s
```
http://ml-ci.amd.com:21096/job/develop-upstream-unit-tests/job/tensorflow-upstream-unit-tests/2075/

------------------------------------

rocm-cpp failures
```
//tensorflow/c/eager:c_api_cluster_test                                  FAILED in 3 out of 3 in 22.1s
//tensorflow/c/eager:c_api_distributed_test                              FAILED in 3 out of 3 in 19.6s
```
http://ml-ci.amd.com:21096/job/develop-upstream-unit-tests/job/tensorflow-upstream-unit-tests-rocm-cpp/644

**Comment by deven-amd** [comment]
jenkins : retest this please

**Comment by deven-amd** [comment]
rocm failures
```
//tensorflow/python/keras/distribute:saved_model_save_load_test_gpu     TIMEOUT in 3 out of 3 in 915.0s
```
http://ml-ci.amd.com:21096/job/develop-upstream-unit-tests/job/tensorflow-upstream-unit-tests/2077


-------------------

rocm-xla failures

```
//tensorflow/compiler/tests:special_math_test_gpu                       TIMEOUT in 3 out of 3 in 915.0s
```
http://ml-ci.amd.com:21096/job/develop-upstream-unit-tests/job/tensorflow-upstream-unit-tests-rocm-xla/1435

**Comment by deven-amd** [comment]
jenkins : retest this please

**Comment by deven-amd** [comment]
rocm failures
```
//tensorflow/python/kernel_tests:tensordot_op_test                       FAILED in 3 out of 3 in 131.4s
```
http://ml-ci.amd.com:21096/job/develop-upstream-unit-tests/job/tensorflow-upstream-unit-tests/2080


rocm-xla failures
```
//tensorflow/compiler/tests:image_ops_test_gpu                           FAILED in 3 out of 3 in 22.2s
```

http://ml-ci.amd.com:21096/job/develop-upstream-unit-tests/job/tensorflow-upstream-unit-tests-rocm-xla/1437

**Comment by deven-amd** [comment]
jenkins : retest this please

**Comment by deven-amd** [comment]
closing this PR as there still seems to be some flakiness when running more than 1 test per GPU.

will attempt to do this again, once ROCm 3.7 is out

**Pull request closed without merging**
