### PR TITLE
Updating the build and CI scripts to take ROCM_PATH as the first positional argument

### PR DESCRIPTION
**Pull request by deven-amd**

### CODE REVIEW

**Comment by ROCm-Apps-Test** [comment]
Can one of the admins verify this patch?

**Comment by deven-amd** [comment]
two failures in `rocm-xla` 
( http://ml-ci.amd.com:21096/job/develop-upstream-unit-tests/job/tensorflow-upstream-unit-tests-rocm-xla/1515/console)

```
//tensorflow/compiler/tests:image_ops_test_gpu                           FAILED in 3 out of 3 in 21.7s
//tensorflow/compiler/tests:image_ops_test_gpu_mlir_bridge_test          FAILED in 3 out of 3 in 24.6s

```

the return of flakiness?

**Comment by deven-amd** [comment]
jenkins : retest rocm-xla please

**Comment by deven-amd** [comment]
this CI flakiness is painful

one failure in `rocm`
(http://ml-ci.amd.com:21096/job/develop-upstream-unit-tests/job/tensorflow-upstream-unit-tests/2163/console)
```
//tensorflow/python/keras/distribute:keras_rnn_model_correctness_test    FAILED in 3 out of 3 in 915.0s
```

**Comment by deven-amd** [comment]
jenkins : retest rocm please

**Pull request merged**
