### PR TITLE
enable QR_op

### PR DESCRIPTION
**Pull request by micmelesse**
This PR enables the QR_op

### CODE REVIEW

**Comment by stevenireeves** [comment]
Jenkins : retest Ubuntu-GPU-single please

**Comment by stevenireeves** [comment]
Jenkins : retest Ubuntu-GPU-multi please

**Comment by stevenireeves** [comment]
@micmelesse can you sync with develop-upstream? It might solve ci-job failures.

**Comment by micmelesse** [comment]
Jenkins : retest Ubuntu-GPU-single please
Jenkins : retest Ubuntu-GPU-multi please

**Comment by micmelesse** [comment]
@stevenireeves It is already synced.

**Comment by stevenireeves** [comment]
@micmelesse check Reza's weekly sync, it may have the same failures.

**Review by stevenireeves — APPROVED** [review]
@micmelesse LGTM

**Pull request merged**
