### PR TITLE
Create rocm-community-build-plan.md

### PR DESCRIPTION
**Pull request by parallelo**
Initial placeholder for the ROCm-specific community supported build plan

### CODE REVIEW

**Comment by parallelo** [comment]
jenkins: retest this please

[using this PR as a vehicle to test the new `rocm-xla` CI build]

**Comment by parallelo** [comment]
jenkins: retest this please

[using this PR as a vehicle to test the new rocm-xla CI build]

**Comment by parallelo** [comment]
jenkins: retest this please

[using this PR as a vehicle to test the new rocm-xla CI build]

**Comment by kobrica** [comment]
Please recheck on CUDA

**Comment by sunway513** [comment]
@parallelo , can we merge the PR now?

**Pull request merged**
