### PR TITLE
[DO NOT MERGE] Porting ROCm hipclang support to mater-rocm-enhanced

### PR DESCRIPTION
**Pull request by deven-amd**
This PR is to port the ROCm hipclang support from the `develop-upstream` to the `master-rocm-enhanced` branch.

We need to have a few pre-reqs in place before we can take this PR
- [ ] identify a commit on the `upstream/master` branch for which all ROCm CI jobs (`rocm`, `rocm-cpp`, `rocm-xla`)  are passing, aka the ROCm CI qualified commit
- [ ] rebase the `master-rocm-enhanced` branch to the ROCm CI qualified commit
- [ ] Setup ROCm CI jobs to run on PRs filed on the `master-rocm-enhanced` branch

The purpose of filing this PR now is to assist with filtering out the changes in this PR, from the set of diffs in `develop-upstream` that we need to triage before we abandon that branch

### CODE REVIEW

**Comment by sunway513** [comment]
Hi @deven-amd , from my understanding, hipclang support should not be maintained in `enhanced` branches -- we shall ensure the master mirror (and upstream master) has full hipclang compatibility.

**Comment by deven-amd** [comment]
agreed on where this should go.

for now lets simple use this PR as a holding place for hipclang related changes that have not yet been upstreamed. I will add more commits to this PR if I find any other hipclang specific change.

We will close out this PR without merging it, once all the corresponding changes have been upstreamed

**Comment by sunway513** [comment]
@yxsamliu , can we assign the issue to you?

**Review by yxsamliu — APPROVED** [review]

**Comment by ROCm-Apps-Test** [comment]
Can one of the admins verify this patch?

**Pull request closed without merging**
