### PR TITLE
rocPRIM v1.0.0

### PR DESCRIPTION
**Pull request by iotamudelta**

### CODE REVIEW

**Comment by iotamudelta** [comment]
jenkins: retest this please

**Comment by whchung** [comment]
@parallelo @iotamudelta look like configuration issue:

```
[91mgpg: requesting key 828AB726 from hkp server keyserver.ubuntu.com
[0mgpgkeys: key 084ECFC5828AB726 can't be retrieved
[91mgpg: no valid OpenPGP data found.
gpg: Total number processed: 0
gpg: keyserver communications error: keyserver helper general error
gpg: keyserver communications error: unknown pubkey algorithm
gpg: keyserver receive failed: unknown pubkey algorithm
[0mThe command '/bin/sh -c /install/install_deb_packages.sh' returned a non-zero code: 2
```

**Comment by parallelo** [comment]
The Jenkins master node's OS went into a funky state on Friday, and it needed a reboot.  Ping me if you notice other strangeness, and we'll get it figured out.

**Comment by iotamudelta** [comment]
@whchung passed - can we merge? :-)

**Pull request merged**
