### PR TITLE
adjust nonpip test params, add nonpipROCM

### PR DESCRIPTION
**Pull request by jayfurmanek**

### CODE REVIEW

**Comment by jayfurmanek** [comment]
retest code-check please

**Comment by jayfurmanek** [comment]
retest code-check please

**Comment by jayfurmanek** [comment]
retest code-check please

**Comment by jayfurmanek** [comment]
retest code-check please

**Comment by jayfurmanek** [comment]
retest code-check please

**Comment by jayfurmanek** [comment]
retest code-check please

**Comment by jayfurmanek** [comment]
retest code-check please

**Comment by jayfurmanek** [comment]
retest code-check please

**Comment by jayfurmanek** [comment]
retest code-check please

**Comment by jayfurmanek** [comment]
retest code-check please

**Comment by jayfurmanek** [comment]
retest code-check please

**Comment by jayfurmanek** [comment]
retest code-check please

**Comment by jayfurmanek** [comment]
retest code-check please

**Review by i-chaochen — APPROVED** [review]

**Pull request merged**
