### PR TITLE
Enable FFT operations on the GPU for ROCm

### PR DESCRIPTION
**Pull request by iotamudelta**
With the rocFFT 0.8.4 release as contained in ROCm 1.8.2, we can enable
FFT operations on the GPU.

Note: unless the docker for CI is updated to 1.8.2, this is expected to fail.

### CODE REVIEW

**Comment by whchung** [comment]
@sunway513 Shall the PR be merged, we need to cherry-pick it into `r1.8-rocm` release branch.

**Comment by sunway513** [comment]
@whchung well received.

**Comment by whchung** [comment]
@iotamudelta oops build failed:

```
tensorflow/stream_executor/rocm/rocm_fft.cc:51:22: error: cannot convert 'hipFloatComplex*' to 'float (*)[2]' for argument '2' to 'hipfftResult hipfftExecC2C(hipfftHandle, float (*)[2], float (*)[2], int)'
```

**Comment by iotamudelta** [comment]
@whchung it will fail until CI is on 1.8.2 (w/ the newer rocFFT)

**Comment by whchung** [comment]
Ok then let's keep this open until CI nodes picking up 1.8.2 release.

**Comment by sunway513** [comment]
@iotamudelta , you can actually change your branch to build the correct rocFFT from source. We can change this back when ROCm1.8.2 is out.

**Comment by whchung** [comment]
@iotamudelta CI node has been upgraded to 1.8.2. time to respin this PR?

**Comment by iotamudelta** [comment]
@whchung works fine now - can we integrate?

**Pull request merged**
