### PR TITLE
Develop upstream sync 190528

### PR DESCRIPTION
**Pull request by parallelo**
Merge log:  
```
$ git merge upstream/master --no-edit
Auto-merging tools/tf_env_collect.sh
Auto-merging third_party/toolchains/preconfig/win_1803/bazel_025/BUILD
Removing third_party/toolchains/preconfig/win_1803/bazel_018/CROSSTOOL
Removing third_party/toolchains/preconfig/ubuntu14.04/gcc-nvcc/windows/msvc_wrapper_for_nvcc.py
Removing third_party/toolchains/preconfig/ubuntu14.04/gcc-nvcc/windows/msvc_wrapper_for_nvcc.bat
Removing third_party/toolchains/preconfig/ubuntu14.04/gcc-nvcc/clang/bin/crosstool_wrapper_driver_is_not_gcc
Removing third_party/toolchains/preconfig/ubuntu14.04/gcc-nvcc/CROSSTOOL
Removing third_party/toolchains/preconfig/ubuntu14.04/gcc-nvcc/BUILD
Auto-merging tensorflow/workspace.bzl
Auto-merging tensorflow/tools/compatibility/BUILD
Auto-merging tensorflow/tools/api/tests/BUILD
Auto-merging tensorflow/tensorflow.bzl
Auto-merging tensorflow/stream_executor/rocm/rocm_dnn.h
CONFLICT (content): Merge conflict in tensorflow/stream_executor/rocm/rocm_dnn.h
Auto-merging tensorflow/stream_executor/rocm/BUILD
Auto-merging tensorflow/stream_executor/BUILD
Auto-merging tensorflow/python/training/tracking/BUILD
CONFLICT (content): Merge conflict in tensorflow/python/training/tracking/BUILD
Auto-merging tensorflow/python/tools/api/generator/BUILD
Auto-merging tensorflow/python/saved_model/BUILD
Auto-merging tensorflow/python/kernel_tests/signal/fft_ops_test.py
Auto-merging tensorflow/python/kernel_tests/signal/BUILD
Removing tensorflow/python/kernel_tests/einsum_op_test.py
Auto-merging tensorflow/python/kernel_tests/control_flow_ops_py_test.py
Auto-merging tensorflow/python/kernel_tests/BUILD
CONFLICT (content): Merge conflict in tensorflow/python/kernel_tests/BUILD
Auto-merging tensorflow/python/keras/optimizer_v2/BUILD
Auto-merging tensorflow/python/keras/engine/base_layer_test.py
Auto-merging tensorflow/python/keras/BUILD
Auto-merging tensorflow/python/eager/backprop_test.py
Auto-merging tensorflow/python/eager/BUILD
CONFLICT (content): Merge conflict in tensorflow/python/eager/BUILD
Auto-merging tensorflow/python/distribute/BUILD
Auto-merging tensorflow/python/data/kernel_tests/BUILD
Auto-merging tensorflow/python/compiler/xla/BUILD
Auto-merging tensorflow/python/compiler/tensorrt/BUILD
Auto-merging tensorflow/python/BUILD
CONFLICT (content): Merge conflict in tensorflow/python/BUILD
Removing tensorflow/lite/tools/accuracy/accuracy_eval_stage.h
Auto-merging tensorflow/lite/python/BUILD
Removing tensorflow/lite/experimental/objc/apis/module.modulemap
Auto-merging tensorflow/lite/delegates/flex/whitelisted_flex_ops.h
Auto-merging tensorflow/lite/delegates/flex/whitelisted_flex_ops.cc
Auto-merging tensorflow/examples/tutorials/mnist/BUILD
Auto-merging tensorflow/examples/speech_commands/BUILD
Auto-merging tensorflow/examples/saved_model/integration_tests/BUILD
Auto-merging tensorflow/core/util/gpu_kernel_helper.h
CONFLICT (content): Merge conflict in tensorflow/core/util/gpu_kernel_helper.h
Removing tensorflow/core/util/einsum_op_util.cc
Auto-merging tensorflow/core/kernels/transpose_op.cc
Auto-merging tensorflow/core/kernels/tile_ops_gpu_impl.h
CONFLICT (content): Merge conflict in tensorflow/core/kernels/tile_ops_gpu_impl.h
Auto-merging tensorflow/core/kernels/tile_ops.cc
CONFLICT (content): Merge conflict in tensorflow/core/kernels/tile_ops.cc
Auto-merging tensorflow/core/kernels/tile_functor_gpu.h
CONFLICT (content): Merge conflict in tensorflow/core/kernels/tile_functor_gpu.h
Auto-merging tensorflow/core/kernels/split_lib_gpu.cu.cc
CONFLICT (content): Merge conflict in tensorflow/core/kernels/split_lib_gpu.cu.cc
Auto-merging tensorflow/core/kernels/spacetodepth_op.cc
Auto-merging tensorflow/core/kernels/softmax_op_gpu.cu.cc
Auto-merging tensorflow/core/kernels/scatter_nd_op.cc
Auto-merging tensorflow/core/kernels/resize_bilinear_op_gpu.cu.cc
CONFLICT (content): Merge conflict in tensorflow/core/kernels/resize_bilinear_op_gpu.cu.cc
Auto-merging tensorflow/core/kernels/random_op_gpu.h
CONFLICT (content): Merge conflict in tensorflow/core/kernels/random_op_gpu.h
Auto-merging tensorflow/core/kernels/logging_ops.h
Auto-merging tensorflow/core/kernels/gather_op.cc
Removing tensorflow/core/kernels/einsum_op.cc
Auto-merging tensorflow/core/kernels/eigen_contraction_kernel.h
Removing tensorflow/core/kernels/data/filter_by_component_dataset_op_test.cc
Removing tensorflow/core/kernels/data/filter_by_component_dataset_op.cc
Auto-merging tensorflow/core/kernels/cudnn_rnn_ops.cc
Auto-merging tensorflow/core/kernels/concat_lib_gpu_impl.cu.cc
CONFLICT (content): Merge conflict in tensorflow/core/kernels/concat_lib_gpu_impl.cu.cc
Auto-merging tensorflow/core/kernels/bias_op.cc
Auto-merging tensorflow/core/kernels/adjust_hsv_gpu.cu.h
Auto-merging tensorflow/core/kernels/BUILD
Auto-merging tensorflow/core/grappler/optimizers/remapper.cc
CONFLICT (content): Merge conflict in tensorflow/core/grappler/optimizers/remapper.cc
Auto-merging tensorflow/core/grappler/optimizers/layout_optimizer.cc
Removing tensorflow/core/distributed_runtime/rpc/eager/grpc_eager_service.cc
Auto-merging tensorflow/core/common_runtime/gpu/gpu_device.cc
Removing tensorflow/core/api_def/python_api/api_def_Einsum.pbtxt
Removing tensorflow/core/api_def/base_api/api_def_TPUReplicate.pbtxt
Removing tensorflow/core/api_def/base_api/api_def_Einsum.pbtxt
Auto-merging tensorflow/core/BUILD
Auto-merging tensorflow/contrib/makefile/Makefile
Removing tensorflow/contrib/distribute/python/estimator_training_test.py
Removing tensorflow/contrib/distribute/python/estimator_integration_test.py
Auto-merging tensorflow/contrib/BUILD
Auto-merging tensorflow/compiler/xrt/tests/BUILD
Auto-merging tensorflow/compiler/xrt/client/BUILD
Auto-merging tensorflow/compiler/xla/tests/BUILD
Auto-merging tensorflow/compiler/xla/service/platform_util.cc
Auto-merging tensorflow/compiler/xla/service/hlo_evaluator_test.cc
Auto-merging tensorflow/compiler/xla/service/gpu/tests/BUILD
Auto-merging tensorflow/compiler/xla/service/gpu/nvptx_compiler.cc
Auto-merging tensorflow/compiler/xla/service/gpu/llvm_gpu_backend/BUILD
Auto-merging tensorflow/compiler/xla/service/gpu/kernel_thunk.cc
Auto-merging tensorflow/compiler/xla/service/gpu/gpu_executable.cc
Auto-merging tensorflow/compiler/xla/service/gpu/gemm_thunk.cc
Auto-merging tensorflow/compiler/xla/service/gpu/custom_call_thunk.cc
Auto-merging tensorflow/compiler/xla/service/gpu/BUILD
CONFLICT (content): Merge conflict in tensorflow/compiler/xla/service/gpu/BUILD
Auto-merging tensorflow/compiler/xla/service/BUILD
Auto-merging tensorflow/compiler/tf2xla/BUILD
Auto-merging tensorflow/compiler/tf2tensorrt/utils/calibration_resource.h
Auto-merging tensorflow/compiler/tf2tensorrt/utils/calibration_resource.cc
Auto-merging tensorflow/compiler/tf2tensorrt/ops/get_calibration_data_op.cc
Removing tensorflow/compiler/tf2tensorrt/kernels/get_serialized_resource_op_test.cc
Auto-merging tensorflow/compiler/tf2tensorrt/kernels/get_calibration_data_op.cc
Auto-merging tensorflow/compiler/tests/BUILD
Auto-merging tensorflow/compiler/jit/xla_gpu_device.cc
Auto-merging tensorflow/compiler/jit/BUILD
Auto-merging configure.py
Automatic merge failed; fix conflicts and then commit the result.
```

### CODE REVIEW

**Comment by parallelo** [comment]
#### Summary of the first round of unit tests ####
**rocm**
```
```

**rocm-v2**
```
Build timed out (after 240 minutes). Marking the build as aborted.
Failed: //tensorflow/python/keras:training_dataset_test 
Failed: //tensorflow/python/keras:convolutional_test_gpu 
Failed: //tensorflow/python/eager:ops_test
```

**rocm-xla**
```
Executed 521 out of 522 tests: 521 tests pass and 1 fails to build.
Failed: //tensorflow/compiler/xla/tests:iota_test_gpu
```

**cuda**
```
Executed 1199 out of 1199 tests: 1198 tests pass and 1 fails locally.
Failed: //tensorflow/python/kernel_tests:unique_op_test
```

**Comment by parallelo** [comment]
Jenkins: retest rocm-v2 please

**Comment by parallelo** [comment]
The Keras tests (most of the failures) all appear to have the same failure signature:  
```
tensorflow.python.framework.errors_impl.NotFoundError: No registered 'Assert' OpKernel for GPU devices compatible with node {{node Assert}}
        .  Registered:  device='XLA_CPU_JIT'; T in [DT_FLOAT, DT_DOUBLE, DT_INT32, DT_UINT8, DT_INT8, ..., DT_COMPLEX128, DT_HALF, DT_UINT32, DT_UINT64, DT_STRING]
  device='XLA_GPU_JIT'; T in [DT_FLOAT, DT_DOUBLE, DT_INT32, DT_UINT8, DT_INT8, ..., DT_BFLOAT16, DT_HALF, DT_UINT32, DT_UINT64, DT_STRING]
  device='XLA_CPU'
  device='XLA_GPU'
  device='CPU'
 [Op:Assert] name: EagerVariableNameReuse
```
Still digging...

**Comment by parallelo** [comment]
@whchung - Yeah, that commit should fix most of the unit test failures in this merge.  On my local machine, we've gone from 87 failures down to 5 (unrelated) failures.

**Comment by parallelo** [comment]
Here are those 5 remaining failures:
```
//tensorflow/python/keras/distribute:keras_dnn_correctness_test         TIMEOUT in 5 out of 5 in 915.0s
//tensorflow/python/keras/distribute:keras_image_model_correctness_test TIMEOUT in 5 out of 5 in 915.0s
//tensorflow/python/keras/distribute:keras_lstm_model_correctness_test   FAILED in 5 out of 5 in 453.4s
//tensorflow/python/keras/distribute:keras_lstm_model_correctness_test_gpu FAILED in 5 out of 5 in 187.7s
//tensorflow/python/kernel_tests:unique_op_test                          FAILED in 5 out of 5 in 2.9s
```
Looking into them now...

**Comment by whchung** [comment]
one failed case in `cuda` path seems to be related to this PR: https://github.com/tensorflow/tensorflow/pull/28795 . Although I have no idea why it's causing the failure.

**Comment by parallelo** [comment]
Here's a running list of remaining known error signatures:
```
tensorflow.python.framework.errors_impl.NotFoundError: No registered 'Qr' OpKernel for GPU devices compatible with node {{node Qr}}
```

**Comment by parallelo** [comment]
Regarding the `Qr`-related error, will be trying this possible fix:
```
diff --git a/tensorflow/core/kernels/qr_op_complex128.cc b/tensorflow/core/kernels/qr_op_complex128.cc
index 8a3e3dc..14412c8 100644
--- a/tensorflow/core/kernels/qr_op_complex128.cc
+++ b/tensorflow/core/kernels/qr_op_complex128.cc
@@ -19,7 +19,7 @@ namespace tensorflow {
 
 REGISTER_LINALG_OP("Qr", (QrOp<complex128>), complex128);
 
-#if GOOGLE_CUDA
+#if GOOGLE_CUDA || TENSORFLOW_USE_ROCM
 // We temporarily disable QR on GPU due to a bug in the QR implementation in
 // cuSolver affecting older hardware. The cuSolver team is tracking the issue
 // (https://partners.nvidia.com/bug/viewbug/2171459) and we will re-enable
diff --git a/tensorflow/core/kernels/qr_op_complex64.cc b/tensorflow/core/kernels/qr_op_complex64.cc
index 467fa6c..5deabc8 100644
--- a/tensorflow/core/kernels/qr_op_complex64.cc
+++ b/tensorflow/core/kernels/qr_op_complex64.cc
@@ -19,7 +19,7 @@ namespace tensorflow {
 
 REGISTER_LINALG_OP("Qr", (QrOp<complex64>), complex64);
 
-#if GOOGLE_CUDA
+#if GOOGLE_CUDA || TENSORFLOW_USE_ROCM
 // We temporarily disable QR on GPU due to a bug in the QR implementation in
 // cuSolver affecting older hardware. The cuSolver team is tracking the issue
 // (https://partners.nvidia.com/bug/viewbug/2171459) and we will re-enable
diff --git a/tensorflow/core/kernels/qr_op_double.cc b/tensorflow/core/kernels/qr_op_double.cc
index 05537a0..30672f1 100644
--- a/tensorflow/core/kernels/qr_op_double.cc
+++ b/tensorflow/core/kernels/qr_op_double.cc
@@ -19,7 +19,7 @@ namespace tensorflow {
 
 REGISTER_LINALG_OP("Qr", (QrOp<double>), double);
 
-#if GOOGLE_CUDA
+#if GOOGLE_CUDA || TENSORFLOW_USE_ROCM
 // We temporarily disable QR on GPU due to a bug in the QR implementation in
 // cuSolver affecting older hardware. The cuSolver team is tracking the issue
 // (https://partners.nvidia.com/bug/viewbug/2171459) and we will re-enable
diff --git a/tensorflow/core/kernels/qr_op_float.cc b/tensorflow/core/kernels/qr_op_float.cc
index 6aebd98..4ddf86a 100644
--- a/tensorflow/core/kernels/qr_op_float.cc
+++ b/tensorflow/core/kernels/qr_op_float.cc
@@ -19,7 +19,7 @@ namespace tensorflow {
 
 REGISTER_LINALG_OP("Qr", (QrOp<float>), float);
 
-#if GOOGLE_CUDA
+#if GOOGLE_CUDA || TENSORFLOW_USE_ROCM
 // We temporarily disable QR on GPU due to a bug in the QR implementation in
 // cuSolver affecting older hardware. The cuSolver team is tracking the issue
 // (https://partners.nvidia.com/bug/viewbug/2171459) and we will re-enable
```

**Comment by parallelo** [comment]
On my local machine, we've got 2 more `rocm` unit tests passing now.  That leaves 3 left.  
```
//tensorflow/python/keras/distribute:keras_dnn_correctness_test         TIMEOUT 
//tensorflow/python/keras/distribute:keras_image_model_correctness_test TIMEOUT 
//tensorflow/python/kernel_tests:unique_op_test                          FAILED
```

**Comment by parallelo** [comment]
On my local machine, `rocm-v2` looks to be in decent shape now:
```
//tensorflow/python/keras:training_dataset_test                 (cached) PASSED in 66.2s
//tensorflow/python/eager:ops_test                                       PASSED in 17.9s
//tensorflow/python/keras:convolutional_test_gpu                         PASSED in 84.2s
```

**Comment by parallelo** [comment]
And the lone failure on `rocm-xla` is in good shape now too:
```
//tensorflow/compiler/xla/tests:iota_test_gpu                            PASSED in 579.0s
```

**Comment by whchung** [comment]
`iota_test_gpu` tends to take quite some time as it populates a big array. perhaps the size category of the test may have to be changed.

**Comment by parallelo** [comment]
Status after the last round of unit tests:
* rocm - jenkins reported network connectivity issue
* rocm-v2 - jenkins aborted on slow `array_ops_test`
* rocm-xla - 1 remaining failing test
* cuda - 1 remaining failing test

Re-runs: 
* jenkins: retest rocm please
* jenkins: retest rocm-v2 please

**Comment by parallelo** [comment]
Updated status after last night's re-runs -- remaining failing unit tests:
* rocm: 1 failure, 2 timeouts
* rocm-v2: 1 failure, 2 timeouts
* rocm-xla: 1
* cuda: 1

Current list of failure signatures: 
* TIMEOUT: `//tensorflow/python/keras/distribute:keras_image_model_correctness_test`
* TIMEOUT: `//tensorflow/python/keras/distribute:keras_dnn_correctness_test`
* FAILED: `//tensorflow/python/kernel_tests:unique_op_test`
* ERROR: `/workspace/tensorflow/compiler/xla/BUILD:896:1: Couldn't build file tensorflow/compiler/xla/_objs/refcounting_hash_map_test/refcounting_hash_map_test.o`

**Comment by parallelo** [comment]
Regarding the `rocm-xla` build error:
```
tensorflow/compiler/xla/refcounting_hash_map_test.cc:80:3: error: 'int64' was not declared in this scope
   int64 count = 0;
   ^
tensorflow/compiler/xla/refcounting_hash_map_test.cc:80:3: note: suggested alternative:
In file included from ./tensorflow/core/platform/types.h:29:0,
                 from ./tensorflow/core/platform/test.h:24,
                 from ./tensorflow/compiler/xla/test.h:46,
                 from tensorflow/compiler/xla/refcounting_hash_map_test.cc:20:
./tensorflow/core/platform/default/integral_types.h:27:19: note:   'tensorflow::int64'
 typedef long long int64;
```

This seems like the fix:
```
diff --git a/tensorflow/compiler/xla/refcounting_hash_map.h b/tensorflow/compiler/xla/refcounting_hash_map.h
index 19b27d6..ffeb546 100644
--- a/tensorflow/compiler/xla/refcounting_hash_map.h
+++ b/tensorflow/compiler/xla/refcounting_hash_map.h
@@ -22,6 +22,7 @@ limitations under the License.
 #include "absl/container/node_hash_map.h"
 #include "absl/memory/memory.h"
 #include "absl/synchronization/mutex.h"
+#include "tensorflow/compiler/xla/types.h"
 
 namespace xla {
 ```

**Comment by parallelo** [comment]
There are actually multiple errors within `refcounting_hash_map_test.cc`.  I don't know why upstream would even push out that test.  

Here are the likely fixes I'm trying on my local machine:
```
diff --git a/tensorflow/compiler/xla/refcounting_hash_map_test.cc b/tensorflow/compiler/xla/refcounting_hash_map_test.cc
index 65120ba..0e4b532 100644
--- a/tensorflow/compiler/xla/refcounting_hash_map_test.cc
+++ b/tensorflow/compiler/xla/refcounting_hash_map_test.cc
@@ -17,7 +17,9 @@ limitations under the License.
 
 #include <functional>
 
+#include "tensorflow/compiler/xla/types.h"
 #include "tensorflow/compiler/xla/test.h"
+#include "tensorflow/core/platform/logging.h"
 
 namespace xla {
 namespace {
@@ -79,7 +81,7 @@ TEST(RefcountingHashMapTest, ForEachEmpty) {
   RefcountingHashMap<int, int> m;
   int64 count = 0;
   m.ForEach([&](const int&, std::shared_ptr<int>) { ++count; });
-  EXPECT_EQ(count, 0);
+  EXPECT_EQ(count, (int64) 0);
 }
```

**Pull request merged**
