### PR TITLE
Modify Dockerfile.rocm to not explicitly pull in HIP PR#457

### PR DESCRIPTION
**Pull request by whchung**
HIP PR#457 has been merged into HIP mainline. So we only need to build HIP
from source.

### CODE REVIEW

**Comment by parallelo** [comment]
Looks like we're still seeing `Invalid function passed to hipLaunchKernelGGL` even with the merged HIP PR#457?

**Comment by whchung** [comment]
This is weird indeed. Notice when we explicitly pull in HIP PR#457 we don't see such issue which means the PR itself must be effective.

How to access the docker instances on CI so we can be sure we are actually cloning the right HIP source codes?

**Comment by parallelo** [comment]
This should work:  
```
# run bash inside the container
CI_DOCKER_EXTRA_PARAMS='-it --rm' tensorflow/tools/ci_build/ci_build.sh ROCM /bin/bash
```

**Comment by parallelo** [comment]
Actually, let me connect with you on Slack regarding how to access the actual Docker image/container for this PR.

**Comment by whchung** [comment]
jenkins: retest this please

**Comment by whchung** [comment]
@parallelo / @sunway513 / @AlexVlx Now it seems the tip of `HIP` is indeed somehow broken. I'll try amend `Dockerfile.rocm` so we pick the last known good commit of `HIP` for TF CI.

```
Generating AMD GCN kernel failed in llc for target: gfx900
LLVM ERROR: Cannot select: 0x159b7708: i32,ch = AtomicLoad<(volatile load monotonic 4 from %ir.61, addrspace 3)> 0x48d9b98, 0x1525b180
  0x1525b180: i32 = shl 0x1587b458, Constant:i32<2>
    0x1587b458: i32 = and 0x142aa798, Constant:i32<31>
      0x142aa798: i32 = AssertZext 0x159c54a0, ValueType:ch:i8
        0x159c54a0: i32,ch = CopyFromReg 0x48d9b98, Register:i32 %0
          0x13199b00: i32 = Register %0
      0x142a9448: i32 = Constant<31>
    0x132c7dc0: i32 = Constant<2>
In function: _ZN10tensorflow26BiasGradNCHW_SharedAtomicsIN5Eigen4halfEEEvPKT_PS3_iiii
```

**Comment by whchung** [comment]
1 failing test after the change: `//tensorflow/python:optimizer_test` . need to look into it. the test was always passing before.

**Comment by whchung** [comment]
Close as the PR has been superseded by #46

**Pull request closed without merging**
