### PR TITLE
Develop upstream sync 201116

### PR DESCRIPTION
**Pull request by jerryyin**

### CODE REVIEW

**Comment by sunway513** [comment]
jenkins: retest this please

**Comment by jerryyin** [comment]
jenkins: retest this please

**Comment by jerryyin** [comment]
jenkins: retest this please

**Comment by jerryyin** [comment]
jenkins: retest this please

**Comment by jerryyin** [comment]
All test passed:
 - tf-unit-tests: Test2306
 - tf-unit-tests-cpu: Test29
 - tf-unit-tests-gpu-multi: Test16
 - tf-unit-tests-gpu-single: Test19
 - tf-unit-tests-rocm-cpp: Test854
 - tf-unit-tests-rocm-xla: Test1644

**Pull request merged**
