### PR TITLE
Adding clang/20 to the list of include dirs

### PR DESCRIPTION
**Pull request by jayfurmanek**

### CODE REVIEW

**Comment by jayfurmanek** [comment]
retest cpu-pycpp please

**Comment by jayfurmanek** [comment]
retest gpu-non-pip-multi please

**Comment by jayfurmanek** [comment]
retest gpu-non-pip-multi please

**Comment by jayfurmanek** [comment]
retest gpu-non-pip-multi please

**Review by i-chaochen — APPROVED** [review]

**Pull request merged**
