### PR TITLE
Develop upstream sync 191014

### PR DESCRIPTION
**Pull request by sunway513**
Conflicts for this week merge:
        both modified:   tensorflow/compiler/mlir/lite/operator_converter_gen.cc                                                                            
        both modified:   tensorflow/compiler/xla/service/gpu/gpu_conv_algorithm_picker.cc                                                                   
        both modified:   tensorflow/python/eager/BUILD                                                                                                      
        both modified:   tensorflow/python/kernel_tests/conv_ops_3d_test.py                                                                                 
        both modified:   tensorflow/python/kernel_tests/linalg/BUILD                                                                                        
        both modified:   tensorflow/python/kernel_tests/pooling_ops_test.py                                                                                 
        both modified:   tensorflow/python/ops/special_math_ops_test.py

### CODE REVIEW

**Comment by sunway513** [comment]
jenkins: retest this please

**Comment by sunway513** [comment]
jenkins: retest rocm-xla please

**Comment by sunway513** [comment]
One failure for rocm-xla, however it would pass reliabily on my local test:
`//tensorflow/compiler/xla/tests:array_elementwise_ops_test_gpu `
One failed to build for rocm-xla, error message as follows:
```
tensorflow/compiler/xla/service/mlir_gpu/experimental/conv_emitter/conv_emitter.cc:585:40: error: could not convert '(& dim_nums)->xla::ConvolutionDimensionNumbers::input_spatial_dimensions()' from 'const google::protobuf::RepeatedField<long int>' to 'absl::Span<const long long int>'
       dim_nums.input_spatial_dimensions(), input, builder);
```

**Comment by sunway513** [comment]
ROCm/v2 path - one failure:
//tensorflow/lite/python:lite_mlir_test    
cuda path - two failures, investigating...

**Comment by sunway513** [comment]
@whchung @deven-amd  can you review the lite_mlir_test failure and see if we should disable it for this weekly merge?

**Comment by whchung** [comment]
@sunway513 don't worry about MLIR-related tests for now, just disable it. As my work getting MLIR hooked up with MIOpen reaching a milestone I can come back and look at them.

**Comment by sunway513** [comment]
The two CUDA path failed tests were also broken on upstream:
```
//tensorflow/python/eager:remote_cloud_tpu_test
//tensorflow/python/keras:saved_model_test
```
For results on upstream plz refer to this build: 
http://ml-ci.amd.com:21096/job/tensorflow-upstream-dev-nvidia-v2-nightly/12/
Therefore, we'll disable these two in this weekly merge. cc @deven-amd @whchung

**Pull request merged**
