### PR TITLE
[ROCm][XLA:GPU] Introduce ReduceRewriter to AMDGPU XLA backend

### PR DESCRIPTION
**Pull request by whchung**
Changed the following places in TensorFlow:

- Introduce ReduceRewriter, ReduceThunk in XLA
- Revise LLVM IR emitter to cope with kReduce in custom-call HLO
- Adopted ReduceWriter in AMDGPU XLA compiler backend
- Add ThenReduce() interface in StreamExecutor
- Hook ThenReduce() to DoReduce() in rocm_dnn module
- Hook DoReduce() to reduce_thunk_op custom TF op to launch rocPRIM kernels
- Relevant bazel script changes

### CODE REVIEW

**Comment by whchung** [comment]
@sunway513 do not merge yet. still working on ironing out differences between `r1.14-rocm`. The branch did change a lot between rc0 and rc1.

**Comment by whchung** [comment]
@sunway513 the branch now builds fine. please give it a shot.

**Comment by sunway513** [comment]
Thanks @whchung , let me try this out.

**Comment by whchung** [comment]
Performance for this branch has been studied. Closing this PR.

**Pull request closed without merging**
