### PR TITLE
Use gpu to generate random number and mask in dropout

### PR DESCRIPTION
**Pull request by jerryyin**
This PR update dropout_op to fix the performance regressions to generate random numbers and masks in CPU. This PR instesad:

- Generate random numbers on GPU
- Use hip kernel to generate mask from random results
- Updated dnn and rocm_dnn to cope with above changes

### CODE REVIEW

**Comment by jerryyin** [comment]
Retest rocm-xla please

**Comment by jerryyin** [comment]
retest rocm please

**Comment by jerryyin** [comment]
retest rocm-xla please

**Comment by parallelo** [comment]
retest rocm-xla please

(sorry Jerry, the node that was allocated to the most recent xla test should've been offline for system-level troubleshooting)

**Comment by jerryyin** [comment]
Only failing test in ROCm side is the compatibility test. Dropout in back-end is in functional state and has been fully regressed in BERT model.

Closing down this PR as it did not reach at the performance goal.

Will revert all dropout implementation in TF backend. FYI @whchung @deven-amd

**Pull request closed without merging**
