### PR TITLE
Develop upstream sync 200608

### PR DESCRIPTION
**Pull request by whchung**

### CODE REVIEW

**Comment by ROCm-Apps-Test** [comment]
Can one of the admins verify this patch?

**Comment by deven-amd** [comment]
@whchung , you will probably need to cherry-pick the commits in the following PRs

https://github.com/tensorflow/tensorflow/pull/40173
https://github.com/tensorflow/tensorflow/pull/40284

**Comment by whchung** [comment]
@deven-amd now we have 4 remaining failures in `rocm-xla`. Will discuss with you whether to fix them or skip them.

**Comment by whchung** [comment]
jenkins: retest rocm-xla please.

**Pull request merged**
