### PR TITLE
Enable XLA by default

### PR DESCRIPTION
**Pull request by whchung**
@deven-amd you might want to piggyback on this PR to tune whitelist for rocm path.

### CODE REVIEW

**Comment by parallelo** [comment]
LGTM.  Let's see how this changes the unit test results.

**Comment by deven-amd** [comment]
LGTM.

Please wait for my commit to ammend the whitelist before taking the merge. I have the build running locally, will push out the commit once it completes.

**Comment by deven-amd** [comment]
hmm....the two tests that I removed from the whitelist fail on the CUDA side. 
This means that either
* the CUDA build still does not have XLA enabled (doubt it, because the `configure.py` setting for XLA is not ROCM/CUDA specific) or
* somehow we have introduced a CUDA only bug in our fork :(

will dig into this later today / tomorrow...have a few other things I need to tend to first.

**Comment by whchung** [comment]
2 failed cases:
```
//tensorflow/python/eager:def_function_xla_test_gpu
//tensorflow/python/training/tracking:util_xla_test_gpu
```

Symptoms are all the same:
```
RuntimeError: Error copying tensor to device: /job:localhost/replica:0/task:0/device:XLA_GPU:0. /job:localhost/replica:0/task:0/device:XLA_GPU:0 unknown device.
```

**Comment by deven-amd** [comment]
hmm...looks like there was a hiccup in the CI nodes
```
+ docker system prune -a -f
Error response from daemon: a prune operation is already running
Build step 'Execute shell' marked build as failure
Setting status of 1d1c3ea181c52e14cfc45fa4e56fcbf46e30bb32 to FAILURE with url http://ml-ci.amd.com:21096/job/tensorflow-upstream-unit-tests-rocm-xla/64/ and message: 'Build finished. '
Using context: rocm-xla
```

**Comment by deven-amd** [comment]
jenkins : retest this please

**Comment by deven-amd** [comment]
same error again:...will kick off another run tomorrow morning...hoping third time's the charm!

```
+ docker system prune -a -f
Error response from daemon: a prune operation is already running
Build step 'Execute shell' marked build as failure
Setting status of 1d1c3ea181c52e14cfc45fa4e56fcbf46e30bb32 to FAILURE with url http://ml-ci.amd.com:21096/job/tensorflow-upstream-unit-tests-rocm-xla/65/ and message: 'Build finished. '
Using context: rocm-xla
Finished: FAILURE
```

@parallelo, just FYI

**Comment by deven-amd** [comment]
something is wonky with the CI...all tests pass on CUDA and ROCM but there is some other failure

```
Executed 1114 out of 1114 tests: 1114 tests pass.
[0m[31m[1mAll tests passed but there were other errors during the build.
[0m
[31m[1mFAILED:[0m Build did NOT complete successfully
[0mBuild step 'Execute shell' marked build as failure
Setting status of 1d1c3ea181c52e14cfc45fa4e56fcbf46e30bb32 to FAILURE with url http://ml-ci.amd.com:21096/job/tensorflow-upstream-unit-tests-nvidia/536/ and message: 'Build finished. '
Using context: cuda
Finished: FAILURE
```

```
Executed 1061 out of 1061 tests: 1061 tests pass.
[0m[31m[1mAll tests passed but there were other errors during the build.
[0m
[31m[1mFAILED:[0m Build did NOT complete successfully
[0mBuild step 'Execute shell' marked build as failure
Setting status of 1d1c3ea181c52e14cfc45fa4e56fcbf46e30bb32 to FAILURE with url http://ml-ci.amd.com:21096/job/tensorflow-upstream-unit-tests/769/ and message: 'Build finished. '
Using context: rocm
Finished: FAILURE
```

This is in addition to the failure in `rocm-xla` I mentioned above.

BTW, after the commits that have been added to this PR to whitelist all the XLA failures, the expectation is that the `rocm-xla` path should pass too.

**Comment by deven-amd** [comment]
nevermind....I see the cause of failure in `rocm` and `cuda`, will fix it

**Comment by whchung** [comment]
@deven-amd @parallelo @sumesh13 Finally we see a check mark on `rocm-xla` path!

**Pull request merged**
