### PR TITLE
Develop upstream sync 211101

### PR DESCRIPTION
**Pull request by stevenireeves**

### CODE REVIEW

**Comment by stevenireeves** [comment]
Jenkins : retest Ubuntu-GPU-multi please

**Comment by stevenireeves** [comment]
Jenkins : restest Ubuntu-GPU-single please

**Comment by deven-amd** [comment]
@stevenireeves 

w.r.t the "regex" failure...ran into the same failure when I did the r2.7 branch sync. the fix is the same as yours, but please see commit message below for the root cause

https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/pull/1481/commits/27c7d42d63503cfd3905cd5edc86fe21c68eae6f

**Comment by stevenireeves** [comment]
@deven-amd I thought I had disabled this test before. 
https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/pull/1464/commits/45ef09067d459a81a640582d4cf84f9a359009b5

But I think in the unit test reshuffle it was re-enabled.

**Comment by stevenireeves** [comment]
Jenkins : retest Ubuntu-GPU-multi please

**Comment by jayfurmanek** [comment]
We'll want to remember to upstream these:
a4b6b914ef476d4593529a581b6d719969546417
8951d875beb1cb85fc6a7c4527000f1cfe45be94

**Pull request merged**
