### PR TITLE
Develop upstream sync 180730

### PR DESCRIPTION
**Pull request by sunway513**
Weekly sync up, submit to check with CI.

### CODE REVIEW

**Comment by whchung** [comment]
@sunway513 in your latest commit you added one missing file. in order to retain the history of that particular file, I'm wondering would it be possible to revise this PR so the file is not deleted in the first place?

**Comment by sunway513** [comment]
@whchung done, please review.

**Comment by sunway513** [comment]
@deven-amd , could you rebase your commit with c7366c6 and submit your changes with -f ?

**Comment by whchung** [comment]
@sunway513 / @deven-amd please help assess if the 2 failed tests:

```
//tensorflow/python/distribute:distribute_coordinator_test
//tensorflow/python/keras:model_subclassing_test
```

are newly added or not, and edit CI whitelist accordingly. thx.

**Comment by whchung** [comment]
//tensorflow/python/feature_column:feature_column_v2_test ?

**Comment by whchung** [comment]
@sunway513 / @deven-amd seems `//tensorflow/python/estimator:dnn_linear_combined_test ` is kind of flaky. maybe whitelist it? it seems to be related to rocPRIM issue @deven-amd raised yesterday at https://github.com/ROCmSoftwarePlatform/rocPRIM/issues/18

**Comment by sunway513** [comment]
@whchung , done. Okay to merge or you want another CI check?

**Comment by whchung** [comment]
let's give CI another spin just to make sure then we'll take it. really want no surprises in `develop-upstream` branch

**Comment by whchung** [comment]
@deven-amd / @sunway513 I merged this PR even though there is still one failure on ROCm path. Please help check. Build log is at: http://205.234.28.200:21096/job/tensorflow-upstream-unit-tests/253/

**Comment by sunway513** [comment]
@whchung I think we missed the steps to add tags before/after merging to develop-upstream branch.
In case this PR cause further issues, we need the following command to revert:
`git checkout develop-upstream && git revert -m 1 c505257`

**Comment by whchung** [comment]
@sunway513 please help apply tags on `develop-upstream`.

**Comment by sunway513** [comment]
@whchung any idea to make up the "pre merge" tag?

**Comment by sunway513** [comment]
Thanks for the tricks @whchung , the flags are up to date.

**Pull request merged**
