### PR TITLE
Update rocprim commit for hip-clang

### PR DESCRIPTION
**Pull request by yxsamliu**

### CODE REVIEW

**Comment by whchung** [comment]
jenkins: ok to test

**Comment by whchung** [comment]
@yxsamliu sorry for being late on this PR. Now with `-fno-gpu-rdc` enabled by default the barrier to switch to hip-clang is much less. Therefore I'm testing this PR.

@sunway513 Functionality-wise I believe the PR looks fine. We might need to run a performance test before taking it.

**Comment by sunway513** [comment]
Checking the perf with this PR now.

**Comment by sunway513** [comment]
LGTM, no perf regression with this PR.

**Pull request merged**
