### PR TITLE
Develop upstream sync 190401

### PR DESCRIPTION
**Pull request by jerryyin**
Conflict file list:

> 
        tensorflow/core/kernels/bias_op_gpu.cu.cc.orig
        tensorflow/core/kernels/bucketize_op_gpu.cu.cc.orig
        tensorflow/core/kernels/concat_lib_gpu_impl.cu.cc.orig
        tensorflow/core/kernels/depthwise_conv_op_gpu.h.orig
        tensorflow/core/kernels/diag_op_gpu.cu.cc.orig
        tensorflow/core/kernels/dilation_ops_gpu.cu.cc.orig
        tensorflow/core/kernels/eye_functor_gpu.cu.cc.orig
        tensorflow/core/kernels/fused_batch_norm_op.cu.cc.orig
        tensorflow/core/kernels/lu_op_gpu.cu.cc.orig
        tensorflow/core/kernels/matrix_band_part_op_gpu.cu.cc.orig
        tensorflow/core/kernels/maxpooling_op_gpu.cu.cc.orig
        tensorflow/core/kernels/multinomial_op_gpu.cu.cc.orig
        tensorflow/core/kernels/pooling_ops_3d_gpu.cu.cc.orig
        tensorflow/core/kernels/relu_op_gpu.cu.cc.orig
        tensorflow/core/kernels/resize_nearest_neighbor_op_gpu.cu.cc.orig
        tensorflow/core/kernels/split_lib_gpu.cu.cc.orig
        tensorflow/core/kernels/svd_op_gpu.cu.cc.orig
        tensorflow/python/kernel_tests/matmul_op_test.py.orig

Rest of files are fast-forwarded

### CODE REVIEW

**Comment by whchung** [comment]
@jerryyin there are build errors in this PR. Please help fix it.

**Comment by jerryyin** [comment]
@whchung Working on it

**Comment by jerryyin** [comment]
Working on the cuda kernel launch failure at tensorflow/core/kernels/svd_op_gpu.cu.cc

**Comment by jerryyin** [comment]
jenkins: ok to test

**Comment by jerryyin** [comment]
According to the test log, the failure is in batch_matmul_op_test only. It is caused by a failed BLAS (xGEMMBatched) call from rocm_blas.cc.

Looking at the merge conflict, I didn't see any file related with batch_matmul yet. Will need to do local reproduce and debug.

**Comment by whchung** [comment]
@deven-amd for `rocm` path I agree with @jerryyin 's analysis. for `rocm-xla` path the only failing test is FLAKY and I think we can live with it. how do you think about `rocm-v2` path?

**Comment by deven-amd** [comment]
The `rocm-v2` has only the following failures that we need to worry about. 
(All other failures are "known" failures which were whitelisted in PR #388 )

```
//tensorflow/python/kernel_tests:batch_matmul_op_test                    FAILED in 3 out of 3 in 6.8s
//tensorflow/python/kernel_tests:batch_matmul_op_test_gpu                FAILED in 3 out of 3 in 6.9s
```

So I guess we have the same failure on `rocm-v2` as we have on `rocm`.  Resolve that and this PR should be good to go

**Comment by jerryyin** [comment]
@deven-amd Sounds like the same issue with rocm failure. Confirmed that I can reproduce the issue locally. Looking at the VLOG, nothing from inside tensorflow captured my eye. The only complaint being not able to launch xGEMMBatched kernel from rocBLAS. 

I will start with running the same setup in rocBLAS bench

**Comment by deven-amd** [comment]
For the `rocm-xla` path, there is a build failure we need to resolve
```
ERROR: /workspace/tensorflow/compiler/xla/service/gpu/BUILD:556:1: Couldn't build file tensorflow/compiler/xla/service/gpu/redzone_allocator_test: Linking of rule '//tensorflow/compiler/xla/service/gpu:redzone_allocator_test' failed (Exit 1): crosstool_wrapper_driver_rocm failed: error executing command                                                                                                                     
  (cd /home/jenkins/workspace/tensorflow-upstream-unit-tests-rocm-xla/bazel-ci_build-cache/.cache/bazel/_bazel_jenkins/eab0d61a99b6696edb3d2aff87b585e8/execroot/org_tensorflow && \                                                                                                                                                                                                                                                 
  exec env - \                                                                                                                                                                                                                                                                                                                                                                                                                       
    LD_LIBRARY_PATH='' \                                                                                                                                                                                                                                                                                                                                                                                                             
    PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin \                                                                                                                                                                                                                                                                                                                                                    
    PWD=/proc/self/cwd \                                                                                                                                                                                                                                                                                                                                                                                                             
    PYTHON_BIN_PATH=/usr/bin/python3 \                                                                                                                                                                                                                                                                                                                                                                                               
    PYTHON_LIB_PATH=/usr/local/lib/python3.5/dist-packages \                                                                                                                                                                                                                                                                                                                                                                         
    TF_DOWNLOAD_CLANG=0 \                                                                                                                                                                                                                                                                                                                                                                                                            
    TF_NEED_CUDA=0 \                                                                                                                                                                                                                                                                                                                                                                                                                 
    TF_NEED_OPENCL_SYCL=0 \                                                                                                                                                                                                                                                                                                                                                                                                          
    TF_NEED_ROCM=1 \                                                                                                                                                                                                                                                                                                                                                                                                                 
  external/local_config_rocm/crosstool/clang/bin/crosstool_wrapper_driver_rocm -o bazel-out/k8-opt/bin/tensorflow/compiler/xla/service/gpu/redzone_allocator_test '-Wl,-rpath,$ORIGIN/../../../../../_solib_local/' '-Wl,-rpath,$ORIGIN/../../../../../_solib_local/_U_S_Stensorflow_Scompiler_Sxla_Sservice_Sgpu_Credzone_Uallocator_Utest___Utensorflow' '-Wl,-rpath,$ORIGIN/../../../../../_solib_local/_U@local_Uconfig_Ucuda_S_\
Scuda_Ccudart___Uexternal_Slocal_Uconfig_Ucuda_Scuda_Scuda_Slib' -Lbazel-out/k8-opt/bin/_solib_local/_U_S_Stensorflow_Scompiler_Sxla_Sservice_Sgpu_Credzone_Uallocator_Utest___Utensorflow -Lbazel-out/k8-opt/bin/_solib_local -Lbazel-out/k8-opt/bin/_solib_local/_U@local_Uconfig_Ucuda_S_Scuda_Ccudart___Uexternal_Slocal_Uconfig_Ucuda_Scuda_Scuda_Slib '-Wl,-rpath,$ORIGIN/,-rpath,$ORIGIN/..,-rpath,$ORIGIN/../..,-rpath,$ORIG\
IN/../../..,-rpath,$ORIGIN/../../../..' -pthread -Wl,-rpath,../local_config_rocm/rocm/rocm/lib -pthread -pthread -Wl,-rpath,../local_config_cuda/cuda/lib64 -Wl,-rpath,../local_config_cuda/cuda/extras/CUPTI/lib64 -pthread -pthread -Wl,-no-as-needed -B/opt/rocm/hcc/compiler/bin -no-canonical-prefixes -pass-exit-codes '-Wl,--build-id=md5' '-Wl,--hash-style=gnu' -Wl,@bazel-out/k8-opt/bin/tensorflow/compiler/xla/service/g\
pu/redzone_allocator_test-2.params)                                                                                                                                                                                                                                                                                                                                                                                                  
Execution platform: @bazel_tools//platforms:host_platform                                                                                                                                                                                                                                                                                                                                                                            
bazel-out/k8-opt/bin/_solib_local/_U@local_Uconfig_Ucuda_S_Scuda_Ccudart___Uexternal_Slocal_Uconfig_Ucuda_Scuda_Scuda_Slib/libcudart.so: file not recognized: File truncated                                                                                                                                                                                                                                                         
collect2: error: ld returned 1 exit status                                                                                                                                                                                                                                                                                                                                                                                           
```

**Comment by jerryyin** [comment]
Giving an update here:

Thanks to Jack's suggestion in using "git blame", I narrowed the issue down to [this commit](https://github.com/tensorflow/tensorflow/commit/47ab68d265a96b6e7be06afd1b4b47e0114c0ee9) that makes relatively large update to batch_matmul_op_test.py. 

Can *almost be sure that this is an issue from rocBLAS side.

VLOG:

> E tensorflow/stream_executor/rocm/rocm_blas.cc:1936] Internal: failed BLAS call

Python error log:

> Blas xGEMMBatched launch failed : a.shape=[5,2,3], b.shape=[7,3,2], m=2, n=2, k=3, batch_size=35
     [[{{node MatMul}}]]

rocBLAS API used: 

> function: rocblas_hgemm_strided_batched
parameters: to be determined, will ping rocBLAS team once get all parameters

**Comment by whchung** [comment]
@jerryyin in case we are certain it’s caused by rocBLAS please file a ticket internally, and mark relevant tests as no_rocm

**Comment by jerryyin** [comment]
Giving another update here. It ends up being an issue from tf code base, because of an [assert](https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/blob/develop-upstream/tensorflow/stream_executor/rocm/rocm_blas.cc#L1893). Synced up with rocBLAS member that the assert is correct.

The issue is due to bsa (0) < lda (2) x k(2). bsa being 0 is wrong, this is cause by a_raw_ptrs holding similar addresses. Will look further into why the array is populated with similar addresses.

**Comment by jerryyin** [comment]
My brain hurts a little bit now, but finally figured out what is happening... 

I believe the root cause is that rocblas interface does not have gemm_batched() interface, and we use [gemm_strided_batched](https://rocblas.readthedocs.io/en/latest/api.html#rocblas-type-gemm-strided-batched) as a compromise. On the other hand, cuda has [gemm_batched interface](https://docs.nvidia.com/cuda/cublas/index.html#cublas-lt-t-gt-gemmbatched), so can avoid this problem. Explaination below:

The main issue is due to that we [rely on the pointer address to tell us the strides](https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/blob/develop-upstream/tensorflow/stream_executor/rocm/rocm_blas.cc#L1861). This logic is broken when the broadcasting feature is added, [in this commit](https://github.com/tensorflow/tensorflow/commit/47ab68d265a96b6e7be06afd1b4b47e0114c0ee9#diff-8157d290f5c74391c3c97d5694f001c2R477). When broadcasting feature is added, either a, b or c arrays is likely to have duplicated pointer elements as a result of broadcasting. In the [newly added else statement](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/batch_matmul_op_impl.h#L341), an a/b/c array can be obtained through broadcasting, making the whole array having similar address, duplicated from the element being broadcast on. Now, back to the [stride calculation based on pointer offset](https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/blob/develop-upstream/tensorflow/stream_executor/rocm/rocm_blas.cc#L1861). Not only can the strides being calculated entirely wrong (sda, sdb, sdc can be 0), but [neither can it pass the constant stride check](https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/blob/develop-upstream/tensorflow/stream_executor/rocm/rocm_blas.cc#L1905). I can't think of a way to obtain the stride information unless it is passed all the way through high level API. On the other hand, at this specific case, it really shouldn't try to use the strides version of the gemm call. Nor should the high level API give the stride information in this batch flavor of gemm call.

It looks like we need to do several things:

- Submit a PR to make [line 1905](https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/blob/develop-upstream/tensorflow/stream_executor/rocm/rocm_blas.cc#L1905) an assert on 1890, so that we immediately know what breaks our code base. It should also return a string claiming that rocm does not support broadcasting feature on batch_matmul
- Mark the test as no-rocm
- Submit a feature request to rocBLAS for them to support the gemm_batched interface
- Submit a feature request to us, such that when rocBLAS have the gemm_batched interface implemented, swap flawed implementation here

@whchung Let me know if my thoughts make sense. You may have a better understanding of rocblas on-development features.

**Comment by whchung** [comment]
@jerryyin I agree with your analysis.

**Comment by jerryyin** [comment]
Test continue to fail when I commented out the broadcasting test cases. Will need to take a further look tomorrow.

**Comment by jerryyin** [comment]
Giving another update here, fixed one issue in rocm_blas.cc, that caused test failures in previous update. Now all BatchMatmulOp tests are passing. Will post as an additional commit after figured out all issues with this test.

Seeing another crash from the reduction kernel, from [BatchMatmulGradient tests](https://github.com/tensorflow/tensorflow/commit/47ab68d265a96b6e7be06afd1b4b47e0114c0ee9#diff-e3344ed3f9b9adf6fe8f7d700d08ee48R174). Have started debugging it.

**Comment by whchung** [comment]
@jerryyin I want this PR merged ASAP. Please mark relevant tests as no_rocm. We can fix failed one later on.

**Comment by jerryyin** [comment]
@whchung Sure, will commit what I have, and get the last round of CI regression.

**Comment by jerryyin** [comment]
Now submitting an additional commit to fix the linker issue referenced from @deven-amd. 

CI status commit 49d30ab: 
- cuda is passing; 
- rocm-xla has a build failure;
- rocm has only flaky test failure; 
- rocm-v2 is passing;

@whchung Let's monitor the next CI result. It should run through without any other issues. Once the CI result is good and you are okay with it, I will either finish the result of the merge procedure in the weekend or first thing on monday.

**Comment by jerryyin** [comment]
jenkins: ok to test

**Comment by jerryyin** [comment]
jenkins: ok to test

**Comment by whchung** [comment]
I'm taking this PR. @jerryyin please being the next round.

**Comment by jerryyin** [comment]
@whchung Sounds good. I finished the rest of tasks: push the tag and sync the upstream branch. Now onto this week's upstreaming merge task

**Pull request merged**
