### PR TITLE
Fix for //tensorflow/python:stateful_random_ops_test

### PR DESCRIPTION
**Pull request by ekuznetsov139**

### CODE REVIEW

**Comment by ROCm-Apps-Test** [comment]
Can one of the admins verify this patch?

**Comment by ROCm-Apps-Test** [comment]
Can one of the admins verify this patch?

**Comment by ROCm-Apps-Test** [comment]
Can one of the admins verify this patch?

**Comment by deven-amd** [comment]
jenkins : retest this please

**Pull request merged**
