### PR TITLE
Develop upstream sync 220906

### PR DESCRIPTION
**Pull request by jayfurmanek**
https://github.com/ROCmSoftwarePlatform/frameworks-internal/issues/2445

### CODE REVIEW

**Comment by jayfurmanek** [comment]
retest Ubuntu-CPU please

**Comment by jayfurmanek** [comment]
retest Ubuntu-GPU-single please

**Comment by jayfurmanek** [comment]
retest Ubuntu-GPU-Multi please

**Review by rsanthanam-amd — APPROVED** [review]

**Comment by jayfurmanek** [comment]
retest Ubuntu-GPU-Multi please

**Comment by jayfurmanek** [comment]
retest Ubuntu-GPU-Multi please

**Comment by jayfurmanek** [comment]
retest Ubuntu-GPU-Multi please

**Pull request merged**
