### PR TITLE
[DO NOT MERGE] Enabling fp16 packet optimizations in Eigen

### PR DESCRIPTION
**Pull request by deven-amd**
/cc @ekuznetsov139 @jerryyin @whchung

### CODE REVIEW

**Comment by ROCm-Apps-Test** [comment]
Can one of the admins verify this patch?

**Comment by deven-amd** [comment]
@ekuznetsov139, how did you go about doing the per measurements for fp16 vs fp32 in issue #827 ? I want to see if using the TF built using the changes in this PR makes any improvements

**Comment by ekuznetsov139** [comment]
```
import tensorflow as tf
from tensorflow.keras.applications.densenet import DenseNet201
from tensorflow.keras.models import Model
from tensorflow.keras import backend as K
import numpy as np
import time

K.set_image_data_format('channels_last')

#uncomment to test in float16
#tf.keras.mixed_precision.experimental.set_policy('mixed_float16')
model = DenseNet201()

dim=tf.constant((100*224*224*3,), dtype=tf.int32)
x = tf.random.uniform(dim, dtype=tf.float32)
x=tf.reshape(x, (100,224,224,3))
model.summary()

runtimes=[]
for n in range(10):
	start = time.time()
	preds = model.predict(x,steps=1)
	t=(time.time()-start)
	print(t)
	if n!=0:
		runtimes.append(t)
	x=tf.sin(x*preds[0,0])

runtimes.sort()
print("Median", runtimes[len(runtimes)//2])

```

be advised that it takes quite a while to start up, especially the first time, when it's generating the MIOpen DB entries (could take 3-5 minutes)

**Comment by deven-amd** [comment]
hmm, when I try out Eugene's example

the run with Find Mode 
* is hanging (3 hours and still in the first run) for fp16 mode.
* took about 30 mins (for the first run) for fp32 mode.

If I switch to Immediate mode, I can see an improvement of about 10% with fp16. I get the same 10% improvement with and without the changes in this PR. That is kinda expected, since we have seen that Eigen kernels are typically memory bound, and enabling vector optimizations does not help their preformance.

As for this PR, I first need to upstream the workaround for `LeakyRelu` function. If that gets accepted, I will push out the PR to upstream the Eigen change. Once that gets accepted and shows up on the TF side, we can checkin the change to drop the extra header includes.

---------------------

A tangential observation to this PR. 
@daniellowell 

turns out that Immediate Mode rankings for the results returned are not necessarily accurate.
In a fresh container (in which we have not yet this test in Find DB mode), if we run with
* immediate mode enabled (set `TF_ROCM_USE_IMMEDIATE_MODE=1`)
* instruct immediate mode API to return only the best algo (set `TF_ROCM_RETURN_BEST_ALGO_ONLY=1`)
then fp32 run median time is approx 3.1 s

Now if you let immediate mode API return all algos and let TF code pick the best one by profiling them,  (unset `TF_ROCM_RETURN_BEST_ALGO_ONLY`), then the fp32 run median time is approx 1.3x. This implies that the best algo returned by immediate mode might not be best.

Note that once you run with Find Mode enabled, this experiment will no longer reproduce the results above, since the Find Mode run will populate the DB with the correct best algo.

**Comment by ekuznetsov139** [comment]
You can try to replace the two 100s with smaller numbers, that reduces the startup time proportionally but makes the timing less accurate. At least you'd be able to confirm it runs in fp16.

Re: immediate mode rankings, isn't that precisely what we discussed in a meeting a few weeks ago? With immediate mode enabled, it has no way of picking the "best" option for anything not in the DB, so it'll return GEMM for all misses. 

Your times are quite high, I'm seeing ~0.31 s with fp32 and ~0.27 s with fp16.

**Comment by deven-amd** [comment]
closing this PR out for now, as we need to fix get the Eigen changes upstreamed and then for TF to move the Eigen pointer beyond that point

**Pull request closed without merging**
