### PR TITLE
Replace hipBLAS with rocBLAS.

### PR DESCRIPTION
**Pull request by iotamudelta**
Along the way also enable more BLAS features implemented in rocBLAS.

There is more to do in the interface but this is a good milestone for merging.

### CODE REVIEW

**Comment by iotamudelta** [comment]
@whchung makes sense!

**Comment by whchung** [comment]
@parallelo now `ci_build` for TF 1.3 has been merged i guess we should also be expecting one for this repo?

**Comment by parallelo** [comment]
Yes, I can submit a `ci_build`-related pull request for `tensorflow-upstream` too.  Will do so this morning.

**Comment by parallelo** [comment]
@iotamudelta - Just added a webhook between `tensorflow-upstream` and our Jenkins server.  Would it be possible to `Close the pull request` and then `reopen the pull request` to test whether it can trigger a build+test cycle?  Thx.

**Comment by whchung** [comment]
@iotamudelta

**Comment by iotamudelta** [comment]
Looks like you did so already?

**Comment by parallelo** [comment]
Yes, but the trigger didn't work properly.  Looking through Jenkins/GitHub logs now..

**Comment by iotamudelta** [comment]
Feel free to close/open as much as you need! I may push a merge from develop-upstream here in an hour once TF is built...

**Comment by iotamudelta** [comment]
@parallelo once CI works, it'd be great if we could run a baseline w/ the current state so that I can also see if I cause regressions. Thanks!

**Comment by parallelo** [comment]
Can one of the admins verify this patch?

**Comment by whchung** [comment]
@parallelo by "verify" you mean "approve"?

**Comment by iotamudelta** [comment]
@whchung without CI?

**Comment by parallelo** [comment]
FYI - The CI job for this PR has been kicked off.  Looking through the Jenkins logs, our GitHub org needed to be whitelisted to allow our PR to trigger a job.  No further action necessary until we get the unit test results.

**Comment by whchung** [comment]
@parallelo I thought we should seeing a yellow light here when the CI job is running, and a check mark if things go well, or a X if anything ill happens?

**Comment by parallelo** [comment]
Jenkins:  retest this please

**Comment by whchung** [comment]
@iotamudelta / @parallelo check mark get!

**Pull request merged**
