### PR TITLE
The select_and_scatter GPU kernel was causing a large performance dro…

### PR DESCRIPTION
**Pull request by rsanthanam-amd**
…p for the MLPerf Resnet50 model on MI200.

The reason for the performance loss is that the AMD GPU compiler was inserting very high latency instructions into
the critical path of the CAS loop which was generated because atomic add is not supported for fp16.

These high latency instructions are specific to MI200 are emitted by the compiler to ensure system wide cache
coherency on the MI200 architecture.

The fix for the issue is to change the syncscope for the atomicCAS loop from 'system' (which is the default) to
'agent'.

This prevents the compiler from emitting the MI200 specific high latency instructions but still emits instructions which provide
adequate cache coherency guarantees in line with previous AMD GPU architectures.

### CODE REVIEW

**Comment by deven-amd** [comment]
LGTM

@whchung please review and approve...thanks

**Comment by rsanthanam-amd** [comment]
Note that I am merging this PR directly into develop-upstream-QA-rocm50 instead of develop-upstream.

Is this correct?

**Comment by rsanthanam-amd** [comment]
One of our kernel engineers helped me to understand the real reason for the CAS loop:  it is because atomic adds for fp16 did not exist in older AMD GPU architectures (I don't know if MI200 supports this now or not - will check).

If I generate LLVM IR for fp32, it clearly uses atomic fadd.

I saw the following comment pertaining to AMD GPU in the relevant source file:

// todo: implement for F16 via global_atomic_fadd_pk2f16

So it might be possible to fix this issue by simply enabling atomic add for fp16 in XLA.

That might be a better fix than the one captured in this PR.

Any opinions?

**Comment by deven-amd** [comment]
> Note that I am merging this PR directly into develop-upstream-QA-rocm50 instead of develop-upstream.

thanks for pointing that out. Please file PR to merge this into `develop-upstream` branch first (so that we run all the CI job and can verify that this change will not cause any regressions). Once that step is done, we can port this change to other branches (including `develop-upstream-QA-rocm50` )

> That might be a better fix than the one captured in this PR.  Any opinions?

ca we start an email thread to discuss this matter (include jack, eugene, the kernel engineer(s) you have been working with, and myself on it)...thanks

**Comment by rsanthanam-amd** [comment]
Closing this and merging the changes to develop-upstream.

**Pull request closed without merging**
