### PR TITLE
Develop upstream sync 230710

### PR DESCRIPTION
**Pull request by jayfurmanek**
https://github.com/ROCmSoftwarePlatform/frameworks-internal/issues/4922

### CODE REVIEW

**Comment by jayfurmanek** [comment]
retest Ubuntu-CPU please

**Comment by jayfurmanek** [comment]
retest Ubuntu-CPU please

**Comment by jayfurmanek** [comment]
retest Ubuntu-CPU please

**Comment by i-chaochen** [comment]
cpu test should be no problem because the failed one is my last week fix, and the fix is merged now https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/pull/2149

**Review by i-chaochen — APPROVED** [review]

**Comment by jayfurmanek** [comment]
retest Ubuntu-GPU-single please

**Pull request merged**
