### PR TITLE
Small test cleanup of third_party/xla

### PR DESCRIPTION
**Pull request by draganmladjenovic**

### CODE REVIEW

**Comment by i-chaochen** [comment]
does this PR can fix `dot_dimension_sorter_test` on xla side?

**Comment by i-chaochen** [comment]
retest gpu-pycpp please
retest cpu-pycpp please
retest gpu-non-pip-multi please

**Comment by draganmladjenovic** [comment]
> does this PR can fix `dot_dimension_sorter_test` on xla side?

It was passing for me, so I assumed it was fixed in the meantime. Will wait if it shows up in the logs.

**Comment by draganmladjenovic** [comment]
Retest gpu-pycpp please.

**Comment by i-chaochen** [comment]
> > does this PR can fix `dot_dimension_sorter_test` on xla side?
> 
> It was passing for me, so I assumed it was fixed in the meantime. Will wait if it shows up in the logs.

Great! please also create a PR to upstream into XLA (Although there is a build error in upstream XLA on our side for now https://github.com/ROCmSoftwarePlatform/frameworks-internal/issues/5869). 

Thanks for the fix!

**Review by i-chaochen — APPROVED** [review]

**Comment by draganmladjenovic** [comment]
Please retest Ubuntu-CPU

**Comment by i-chaochen** [comment]
retest Ubuntu-CPU please

**Comment by draganmladjenovic** [comment]
retest Ubuntu-CPU please

**Comment by draganmladjenovic** [comment]
retest Ubuntu-CPU please

**Comment by draganmladjenovic** [comment]
retest Ubuntu-CPU please

**Pull request merged**
