### PR TITLE
enable cholesky_op

### PR DESCRIPTION
**Pull request by micmelesse**
enables the cholesky_op.

### CODE REVIEW

**Comment by micmelesse** [comment]
jenkins: retest Ubuntu-CPU please

**Comment by micmelesse** [comment]
jenkins: retest Ubuntu-sanity

jenkins: retest Ubuntu-CPU

jenkins: retest Ubuntu-GPU-single please

jenkins: retest Ubuntu-GPU-multi please

**Comment by micmelesse** [comment]
jenkins: retest Ubuntu-sanity please

jenkins: retest Ubuntu-CPU please

jenkins: retest Ubuntu-GPU-single please

jenkins: retest Ubuntu-GPU-multi please

**Review by stevenireeves — APPROVED** [review]
LGTM

**Pull request merged**
