### PR TITLE
updating Dockerfile.rocm to use a newer MIOpen version that contains Fusion API updates/fixes

### PR DESCRIPTION
**Pull request by deven-amd**

### CODE REVIEW

**Comment by deven-amd** [comment]
@parallelo 

The following command (which I added in the commit) seems to error out 
```
 RUN cd $HOME/pkgs/MIOpen && wget http://tengu.amd.com/tf_miopen/ubuntu/MIOpen-HIP-1.5.0-f29af54-Linux.deb && dpkg -i *.deb 
```

error :
```
Resolving tengu.amd.com (tengu.amd.com)... [0m[91mfailed: No address associated with hostname.
wget: unable to resolve host address 'tengu.amd.com'
[0mThe command '/bin/sh -c cd $HOME/pkgs/MIOpen && wget http://tengu.amd.com/tf_miopen/ubuntu/MIOpen-HIP-1.5.0-f29af54-Linux.deb && dpkg -i *.deb' returned a non-zero code: 4
ERROR: docker build failed. Dockerfile is at /home/jenkins/workspace/tensorflow-upstream-unit-tests/tensorflow/tools/ci_build/Dockerfile.rocm
```

Why the address resolution failure? same command works from my local machine.

thanks

**Comment by parallelo** [comment]
Looks like that server isn't accessible from the CI node -- tested with the hostname and IP addr.  We don't really have control over this.  Can you grab that package from an alternative location?

**Comment by deven-amd** [comment]
> Looks like that server isn't accessible from the CI node -- tested with the hostname and IP addr. We don't really have control over this. Can you grab that package from an alternative location?

What would be a good+approved location to stick the package at?

**Comment by sunway513** [comment]
@deven-amd feel free to use dropbox and host it yourself, it's a temporary link anyway.

**Comment by deven-amd** [comment]
will do, this will give me an excuse to open a dropbox account :)

**Pull request merged**
