### PR TITLE
Develop upstream sync 230814

### PR DESCRIPTION
**Pull request by weihanmines**

### CODE REVIEW

**Comment by i-chaochen** [comment]
retest Ubuntu-GPU-single please

**Comment by i-chaochen** [comment]
retest Ubuntu-GPU-multi please

**Comment by weihanmines** [comment]
Jenkins: retest Ubuntu-GPU-multi please

**Review by i-chaochen — COMMENTED** [review]
memcpy for gpu.graph: https://github.com/ROCmSoftwarePlatform/frameworks-internal/issues/5458

**Comment by jayfurmanek** [comment]
retest gpu-non-pip-multi please

**Comment by weihanmines** [comment]
https://github.com/orgs/ROCmSoftwarePlatform/projects/22/views/1?pane=issue&itemId=36213023

**Comment by i-chaochen** [comment]
> https://github.com/orgs/ROCmSoftwarePlatform/projects/22/views/1?pane=issue&itemId=36213023

Could you at least put some descrption on this ticket and related unit tests?

**Comment by weihanmines** [comment]
Jenkins: retest Ubuntu-GPU-single please

**Comment by weihanmines** [comment]
retest Ubuntu-GPU-single please

**Comment by weihanmines** [comment]
retest Ubuntu-GPU-single please

**Comment by weihanmines** [comment]
retest Ubuntu-GPU-single please

**Comment by weihanmines** [comment]
retest Ubuntu-GPU-single please

**Comment by weihanmines** [comment]
retest Ubuntu-GPU-single please

**Comment by weihanmines** [comment]
retest Ubuntu-GPU-single please

**Review by i-chaochen — APPROVED** [review]
can we have a related ticket to trace thisconv_ops_test, please? Thanks!

**Comment by weihanmines** [comment]
> > https://github.com/orgs/ROCmSoftwarePlatform/projects/22/views/1?pane=issue&itemId=36213023
> 
> Could you at least put some descrption on this ticket and related unit tests?

A ticket has been created. I cannot reproduce this error on my dev node though. Everything works fine on my dev node.

**Comment by i-chaochen** [comment]
> > > https://github.com/orgs/ROCmSoftwarePlatform/projects/22/views/1?pane=issue&itemId=36213023
> > 
> > 
> > Could you at least put some descrption on this ticket and related unit tests?
> 
> A ticket has been created. I cannot reproduce this error on my dev node though. Everything works fine on my dev node.

This one? https://github.com/ROCmSoftwarePlatform/frameworks-internal/issues/5472

**Comment by weihanmines** [comment]
> > > > https://github.com/orgs/ROCmSoftwarePlatform/projects/22/views/1?pane=issue&itemId=36213023
> > > 
> > > 
> > > Could you at least put some descrption on this ticket and related unit tests?
> > 
> > 
> > A ticket has been created. I cannot reproduce this error on my dev node though. Everything works fine on my dev node.
> 
> This one? [ROCmSoftwarePlatform/frameworks-internal#5472](https://github.com/ROCmSoftwarePlatform/frameworks-internal/issues/5472)

https://github.com/orgs/ROCmSoftwarePlatform/projects/22/views/1?pane=issue&itemId=36568788

**Comment by weihanmines** [comment]
> > > > https://github.com/orgs/ROCmSoftwarePlatform/projects/22/views/1?pane=issue&itemId=36213023
> > > 
> > > 
> > > Could you at least put some descrption on this ticket and related unit tests?
> > 
> > 
> > A ticket has been created. I cannot reproduce this error on my dev node though. Everything works fine on my dev node.
> 
> This one? [ROCmSoftwarePlatform/frameworks-internal#5472](https://github.com/ROCmSoftwarePlatform/frameworks-internal/issues/5472)

https://github.com/orgs/ROCmSoftwarePlatform/projects/22/views/1?pane=issue&itemId=36568788#:~:text=to%20search-,frameworks%2Dinternal%20%235517,-%5BTF%5D%20The%20log

**Comment by i-chaochen** [comment]
> can we have a related ticket to trace thisconv_ops_test, please? Thanks!

https://github.com/ROCmSoftwarePlatform/frameworks-internal/issues/5517

**Pull request merged**
