### PR TITLE
Develop upstream sync 200210

### PR DESCRIPTION
**Pull request by jerryyin**

### CODE REVIEW

**Comment by ROCm-Apps-Test** [comment]
Can one of the admins verify this patch?

**Comment by jerryyin** [comment]
@deven-amd Could you help take a look at the `//tensorflow/python/debug:check_numerics_callback_test`? Does `MIOpen(HIP): Error [EuristicInit] All attempts failed` sounds familiar to you?

**Comment by deven-amd** [comment]
@jerryyin let me take a peek

**Comment by jerryyin** [comment]
Summary of test failures:

- //tensorflow/python/debug:check_numerics_callback_test: know issue [2379](https://github.com/AMDComputeLibraries/MLOpen/issues/2379)
- // tensorflow/python/eager:gradient_input_output_exclusions_test: upstream problem/pywrap_gradient_exclusions.cc needs to be updated
- //tensorflow/python/keras/layers/preprocessing:discretization_test: upstream/used wrong data type for discretization operator
- //tensorflow/python/keras/optimizer_v2:optimizer_v2_test: upstream/pass in v1, v2 syntax issue

Disabled tests failures due to upstream. cc/@deven-amd

**Pull request merged**
