### PR TITLE
Develop upstream sync 200511

### PR DESCRIPTION
**Pull request by parallelo**
Upstream sync for the week of 2020-05-11. Fixed merge conflicts.
```
$ git merge upstream/master --no-edit 2>&1 | tee out-sync.txt
Auto-merging tensorflow/tools/api/golden/v2/tensorflow.raw_ops.pbtxt
CONFLICT (content): Merge conflict in tensorflow/tools/api/golden/v2/tensorflow.raw_ops.pbtxt
Auto-merging tensorflow/tools/api/golden/v1/tensorflow.raw_ops.pbtxt
CONFLICT (content): Merge conflict in tensorflow/tools/api/golden/v1/tensorflow.raw_ops.pbtxt
Auto-merging tensorflow/tensorflow.bzl
Auto-merging tensorflow/python/ops/parallel_for/BUILD
Auto-merging tensorflow/python/ops/math_grad.py
Auto-merging tensorflow/python/kernel_tests/cwise_ops_test.py
Auto-merging tensorflow/python/keras/layers/preprocessing/image_preprocessing_test.py
Auto-merging tensorflow/python/keras/layers/preprocessing/BUILD
CONFLICT (content): Merge conflict in tensorflow/python/keras/layers/preprocessing/BUILD
Auto-merging tensorflow/python/keras/layers/BUILD
Removing tensorflow/python/keras/distribute/multi_worker_callback_tf1_test.py
Auto-merging tensorflow/python/framework/test_util_test.py
Auto-merging tensorflow/python/eager/function_test.py
CONFLICT (content): Merge conflict in tensorflow/python/eager/function_test.py
Auto-merging tensorflow/python/eager/forwardprop_test.py
Auto-merging tensorflow/python/distribute/collective_all_reduce_strategy_test.py
Auto-merging tensorflow/python/distribute/BUILD
Auto-merging tensorflow/python/BUILD
Removing tensorflow/lite/micro/examples/hello_world/sine_model_data.cc
Auto-merging tensorflow/lite/micro/examples/hello_world/model.h
Removing tensorflow/lite/micro/examples/hello_world/create_sine_model.ipynb
Auto-merging tensorflow/core/util/gpu_device_functions.h
Auto-merging tensorflow/core/profiler/internal/gpu/device_tracer_cuda.cc
Auto-merging tensorflow/core/platform/default/build_config.bzl
Auto-merging tensorflow/core/ops/ops.pbtxt
Auto-merging tensorflow/core/ops/math_ops.cc
Removing tensorflow/core/ops/compat/ops_history_v2/DatasetCardinalityV2.pbtxt
Auto-merging tensorflow/core/kernels/list_kernels.h
CONFLICT (content): Merge conflict in tensorflow/core/kernels/list_kernels.h
Auto-merging tensorflow/core/kernels/einsum_op_impl.h
Auto-merging tensorflow/core/kernels/bincount_op_gpu.cu.cc
Auto-merging tensorflow/core/kernels/batch_matmul_op_impl.h
CONFLICT (content): Merge conflict in tensorflow/core/kernels/batch_matmul_op_impl.h
Auto-merging tensorflow/core/kernels/BUILD
Auto-merging tensorflow/core/graph/BUILD
Auto-merging tensorflow/core/common_runtime/BUILD
Auto-merging tensorflow/core/BUILD
Auto-merging tensorflow/compiler/xla/service/gpu/gpu_compiler.cc
CONFLICT (content): Merge conflict in tensorflow/compiler/xla/service/gpu/gpu_compiler.cc
Auto-merging tensorflow/compiler/xla/service/cpu/runtime_pow.h
Auto-merging tensorflow/compiler/tests/unary_ops_test.py
Auto-merging tensorflow/compiler/tests/binary_ops_test.py
Auto-merging tensorflow/compiler/tests/BUILD
Auto-merging configure.py
Auto-merging RELEASE.md
Automatic merge failed; fix conflicts and then commit the result.
```

### CODE REVIEW

**Comment by ROCm-Apps-Test** [comment]
Can one of the admins verify this patch?

**Comment by parallelo** [comment]
Current status --

`rocm`:
```
Executed 1397 out of 1397 tests: 1394 tests pass and 3 fail locally.
```
`rocm-cpp`:
```
Executed 740 out of 740 tests: 740 tests pass.
```
`rocm-xla`:  
```
Executed 688 out of 941 tests: 688 tests pass and 253 fail to build.
```

**Comment by parallelo** [comment]
The XLA build errors generally look like these:
```
external/tf_runtime/lib/core_runtime/opdefs/core_runtime.cc:193:44: error: no matching function for call to 'mlir::OpAsmParser::parseOptionalAttrDict(llvm::SmallVector<std::pair<mlir::Identifier, mlir::Attribute>, 4u>&)'
       parser.parseOptionalAttrDict(op_attrs))
```
```
external/tf_runtime/lib/core_runtime/opdefs/core_runtime.cc:200:64: error: no matching function for call to 'mlir::OpAsmParser::parseAttribute(mlir::IntegerAttr&, const char [12], llvm::SmallVector<std::pair<mlir::Identifier, mlir::Attribute>, 1u>&)'
     if (failed(parser.parseAttribute(attr, "num_results", attrs)))
```

**Comment by parallelo** [comment]
The 3 `rocm` failures:
```
//tensorflow/python/kernel_tests:batch_gemm_op_test                      FAILED 
//tensorflow/python/kernel_tests:batch_gemm_op_test_gpu                  FAILED
//tensorflow/python/ops/parallel_for:control_flow_ops_test               FAILED
```
Looks like we'll need to dig into the recent batch_gemm_op changes..

**Comment by jerryyin** [comment]
Let me take a look at batch gemm test.

**Comment by parallelo** [comment]
This upstream-sync PR has been superseded by https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/pull/971.  

Very likely the pull from upstream was in a bad state.  It appeared that `tf-runtime` and `llvm-project` were out of sync in `workspace.bzl`, and this cause hundreds of build failures in `rocm-xla`.  

Closing this.

**Pull request closed without merging**
