### PR TITLE
Develop upstream sync 231002

### PR DESCRIPTION
**Pull request by draganmladjenovic**

### CODE REVIEW

**Comment by draganmladjenovic** [comment]
Retest Ubuntu-GPU-multi please
Retest Ubuntu-GPU-single please

**Comment by i-chaochen** [comment]
retest gpu-non-pip-multi please

**Review by i-chaochen — COMMENTED** [review]
I think you mean import this XLA PR (not tensorflow#6000) https://github.com/openxla/xla/pull/6000 there is another changes to remove unused code https://github.com/openxla/xla/pull/6000/commits/a202fc0f73701390ac273a20835ea2aeb58d37bd

**Comment by draganmladjenovic** [comment]
> I think you mean import this XLA PR (not tensorflow#6000) [openxla/xla#6000](https://github.com/openxla/xla/pull/6000) there is another changes to remove unused code [openxla/xla@a202fc0](https://github.com/openxla/xla/commit/a202fc0f73701390ac273a20835ea2aeb58d37bd)

Yup. That is the one.

**Comment by okakarpa** [comment]
Retest Ubuntu-GPU-multi please
Retest Ubuntu-GPU-single please

**Review by i-chaochen — APPROVED** [review]
LGTM

**Pull request merged**
