### PR TITLE
Develop upstream sync 230306

### PR DESCRIPTION
**Pull request by jayfurmanek**
https://github.com/ROCmSoftwarePlatform/frameworks-internal/issues/3844

There was a lot of auto-tuning code added this time in XLA, which is all CUDA at the moment as it relies on the redzone allocator. A fix was needed in one addition as the redzone allocator was being referenced in general code:
https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/pull/2012/commits/55c95c92f2a19106048f8a2d6eed02a40bbb630b

Some legacy Keras RNN features were removed. Notably `tensorflow/python/keras/layers/cudnn_recurrent.py`

### CODE REVIEW

**Comment by jayfurmanek** [comment]
retest Ubuntu-GPU-single please

**Review by i-chaochen — APPROVED** [review]

**Comment by i-chaochen** [comment]
```
Redzone allocator only for CUDA in conv.cc
```

I noticed this too when I was working on https://github.com/ROCmSoftwarePlatform/frameworks-internal/issues/3374

seems redzone is also for distributed training and memory sharing, maybe we shall create a ticket to investigate it further?

**Comment by jayfurmanek** [comment]
The redzone allocator is a specialization of the scratchAllocator, for CUDA (or more specifically for cudnn). It uses some canned PTX code to check for certain memory patterns I think, which makes it CUDA only.
The commit above is a fix for a place where the redzone allocator was being referenced outside of if_cuda_is_configured() stanza in the BUILD file.

**Comment by jayfurmanek** [comment]
> seems redzone is also for distributed training and memory sharing, maybe we shall create a ticket to investigate it further?

The redzone allocator itself will remain CUDA only, but we should investigate if the auto-tuning and algorithm picked can be better supported on ROCM.

**Comment by jayfurmanek** [comment]
retest gpu-non-pip-large please

**Pull request merged**
