### PR TITLE
[ROCm] use rocprim and hipcub from ROCm installation.

### PR DESCRIPTION
**Pull request by whchung**
In newer ROCm releases, rocprim and hipcub would be installed on ROCm stack
by default. Therefore it would no longer be necessary to pull them from source.

### CODE REVIEW

**Comment by whchung** [comment]
@sunway513  please help advise how Dockerfile shall be amended.

**Comment by whchung** [comment]
jenkins: retest rocm-xla please.

**Comment by sunway513** [comment]
Thanks @whchung , I'd suggest installing rocprim and hipcub packages in the Dockerfile.rocm for now. 
After rocm-libs meta-package is fixed, we can consolidate our doc and Dockerfiles to install with that, if we want more elegant installation steps...

**Comment by whchung** [comment]
@sunway513 could you give this PR another go? I added `hipcub` into Dockerfiles but not `rocprim` as it *IS* indirectly pulled by `rocm-libs` thru `rocalution`.

**Comment by whchung** [comment]
jenkins: retest rocm-xla please.

**Comment by whchung** [comment]
@sunway513  I'm merging this branch as CI tests are passing.

I'll hold off submitting it back to TF mainline until ROCm 2.8 is released.

**Comment by sunway513** [comment]
@whchung sure, we shall also review the changes in this PR after rocm-libs can properly include hipcub package as well.

**Pull request merged**
