### PR TITLE
updating Dockerfile.rocm to use the HCC with fix for issue812

### PR DESCRIPTION
**Pull request by deven-amd**
@parallelo: Adding an `hcc` build adds a few minutes to the time required to build the Docker image.

### CODE REVIEW

**Comment by deven-amd** [comment]
@whchung @parallelo 

I think this hcc build update to the Dockerfile will add a whopping 8GB to the docker image!

I had made the same update to the Dockerfile I have for generating the docker image for Eigen nightly testing, and the that image size jumped from 2GB to 10GB with the hcc update. My assumption is that the same will be true for the TF image as well. 

So few questions:

1. Anyway to check the CI logs (perhaps check the image sizes on the CI machine) to confirm this is true for the TF build. 
2. Is this jump in image size a cause for concern? If not, then the rest of the questions are a moot point!
3. What causes this jump in the image size? 
4. What can be done to limit this increase? Can we cleanup some hcc/hip build artifacts which will reduce the image size?

Thanks

deven

**Comment by sunway513** [comment]
@deven-amd , maybe you can build the HCC package, host it on Dropbox and wget that package inside the CI Dockerfile instead of building it every time.

**Comment by deven-amd** [comment]
building on the @sunway513 's idea, and using the Dockerfile mult-stage build feature, I have a solution that works for the Dockerfile I use for eigen nightly test image.

The change can be viewed here:
http://gitlab1.amd.com/deven/dockerfiles/commit/b87e8feacac95f9dcdfccba6b129847d2c48bc6c?view=parallel

The basic concept is to add an initial "build_hip_and_hcc" stage to the Dockerfile, and then only copy over the *.deb package artifacts from that stage into the next stage that does the actual TF image build.

@parallelo, do you think it is worth it to apply this multi-stage build update here, or is the image size not a concern, and we can merge this PR as is?

**Comment by deven-amd** [comment]
btw, using this solution the eigen image size drops from 10GB to 3.25GB (we started with 2GB prior to the hcc update)

**Comment by whchung** [comment]
I’m fine either way. Better to have @parallelo to weigh in still.

**Comment by deven-amd** [comment]
@parallelo I pushed out the multi-stage version for the Dockerfile. 

Was hoping to get a CI run in, so that we could have atleast one data point for comparison (for the impact of the multi-stage build on image size), but it seems that the `CUDA` build got triggered again :(

Please invoke the `ROCm` build for this PR when you get the chance.

**Comment by parallelo** [comment]
jenkins: retest this please

**Comment by parallelo** [comment]
LGTM.  (let's remove the `sudo` commands from the second stage and double-check for a successful rocm target build)

**Comment by whchung** [comment]
@parallelo 2 test targets now. nice :)

**Comment by sunway513** [comment]
LGTM as well, thanks @deven-amd. Just a heads up, by adding HCC/HIP build, it'll probably add 30+ mins per CI cycle.

**Pull request merged**
