### PR TITLE
Refactor rocm_dnn module to pave way for dynamically loading MIOpen

### PR DESCRIPTION
**Pull request by whchung**
- add move constructor to rocm_activation
- remove ROCMExecutor from most of the interfaces used by rocm_dnn
- remove ROCMExecutor from wrapper call to MIOpen API
- consolidate all miopeHandle_t ownership and access to 2 utility classes: MIOpenAccess / MIOpenHandle
- revise all call sites to MIOpen APIs:
  - largely abolish ROCMExecutor
  - use MIOpenAccess / MIOpenHandle to gain access and retrieve miopenHandle_t
- move MaybeTransformLayout to an utility function instead of a member function

The combined effect is to simplify macro `STREAM_EXECUTOR_MIOPEN_WRAP` where `ROCMExecutor` is no longer needed in MIOpen API calls. This would pave the way to make MIOpen be dynamically loaded instead of dynamically linked.

### CODE REVIEW

**Comment by sunway513** [comment]
jenkins: retest this please

**Comment by whchung** [comment]
@deven-amd Let's go through this PR today. I'd like your review before getting it merged.

**Comment by deven-amd** [comment]
LGTM

The only functional difference I see with the new code, is the introduction of new "miopenSetStream( , nullptr)" calls in certain places. (miopenSetStream is now called everytime we get the miopen handle...this was not the case before).

**Comment by whchung** [comment]
@deven-amd Could you help review if that causes any problem in multi-GPU situation? My assumption is not as we goes to the default HIP stream on the current GPU (set by ROCMExecutor via ROCMDriver). But it’d be good to be checked by an extra pair of eyes

**Comment by whchung** [comment]
@daniellowell could you also weigh in on the extra invocations of miopensetstream(nullptr) . Would it cause any undesirable side effects?

**Comment by whchung** [comment]
@deven-amd also as a heads up. I'm still working on getting the weekly merge for this week done. Working on resolving the differences between `develop-upstream` and PR #25011. Basically we need do revise ROCm SE impl so:

- bazel script goes back to dynamically linked for ROCm
- namespace / naming convention / class aliasing in header files
- DNN interface changes

I'll try finish the weekly merge today, *without* taking this PR.
And then take this PR after a retest.
Then resume working on PR #298 for dynamically loaded setup

**Comment by whchung** [comment]
@deven-amd Thanks for amending the PR. Maybe this one could land sooner than `develop-upstream-sync-190128`...

**Comment by deven-amd** [comment]
@whchung 

There was only 1 test failure in CUDA and even that seems to be a resource issue
```
2019-01-30 01:15:29.763315: W tensorflow/core/framework/op_kernel.cc:1412] OP_REQUIRES failed at save_restore_v2_ops.cc:132 : Resource exhausted: /home/ubuntu/workspace/tensorflow-upstream-unit-tests-nvidia/bazel-ci_build-cache/.cache/bazel/_bazel_ubuntu/eab0d61a99b6696edb3d2aff87b585e8/execroot/org_tensorflow/_tmp/b9fe2c23a90f46283bb3b2dcd86b2de221uttc_1/tmpy632nwuf/large_variable.data-00000-of-00001.tempstate9973761424813534739; No space left on device
```

I think it should be safe to merge this PR

**Comment by whchung** [comment]
@deven-amd thanks for getting this PR polished!

**Pull request merged**
