### PR TITLE
Implementing reduction for complex64 and complex128

### PR DESCRIPTION
**Pull request by ekuznetsov139**
This PR implements reduction for complex64 and complex128 on ROCm by casting the tensors to hipFloatComplex and hipDoubleComplex respectively.

### CODE REVIEW

**Comment by ROCm-Apps-Test** [comment]
Can one of the admins verify this patch?

**Review by deven-amd — APPROVED** [review]
LGTM

couple of minor suggestions.

1. it might be good idea to create a separate commit for the `TF_RED__WARPSIZE` to `WARPSIZE` renaming. Makes for less noise while reviewing, and can be easy to undo if the renaming is not to the G upstream reviewers liking

2. You are changing code within `GOOGLE_CUDA`. Has it been tested? Can we avoid making those changes?

Another thought I had was whether we can collect all the `ifdef TENSORFLOW_USE_ROCM` specific device functions we are adding within a common file + namespace? This may or may not be feasible, but is probably worth exploring.

**Comment by ekuznetsov139** [comment]
TF_RED_WARPSIZE  -> WARPSIZE is not just a rename. There's logic in there to set WARPSIZE to TF_RED_WARPSIZE/2 in some situations, because some kernels need ~WARPSIZE^2*sizeof(type) shared memory and that exceeds the available memory for ROCm with complex128. 

It can be separated into two commits: one with most other changes and enabling complex64, and one with the WARPSIZE change and enabling complex128.

You have a point re: GOOGLE_CUDA, it's simple code but it's not been tested. I'll test it and get back to you.

**Comment by ekuznetsov139** [comment]
I've confirmed that it builds and runs correctly with CUDA.

**Comment by jerryyin** [comment]
@ekuznetsov139 In case it got forgotten, could you help attach the corresponding upsteam PR# according to the new process requirement in our weekly meeting?

**Comment by ekuznetsov139** [comment]
There's no upstream PR for this yet

**Comment by jerryyin** [comment]
@ekuznetsov139 Sounds good. Please leave a comment once it is upstreamed.

**Comment by jerryyin** [comment]
@ekuznetsov139 It doesn't look like this PR got upstream properly. I found out while trying to resolve weekly merge conflict. Could you open a new upstream PR for this?

/cc @deven-amd

**Comment by ekuznetsov139** [comment]
It's been submitted upstream as #40329 and I'm waiting for them to respond.

**Comment by jerryyin** [comment]
Gotcha, thanks for clarifying. It's been two months already since you submitted the upstream PR. Wow, that's really slow to upstream these days.

**Pull request merged**
