### PR TITLE
Develop upstream sync 230123

### PR DESCRIPTION
**Pull request by rahulbatra85**
https://github.com/ROCmSoftwarePlatform/frameworks-internal/issues/3430

### CODE REVIEW

**Comment by i-chaochen** [comment]
```
[31m[1mERROR: [0m/workspace/tensorflow/compiler/xla/mlir_hlo/BUILD:1931:11: Compiling tensorflow/compiler/xla/mlir_hlo/tools/mlir_interpreter/framework/registration.cc failed: (Exit 1): gcc failed: error executing command 

```

something happened in mlir to hlo...

**Review by i-chaochen — APPROVED** [review]

**Comment by rahulbatra85** [comment]
retest Ubuntu-GPU-single please!

**Comment by i-chaochen** [comment]
I suggeste we can disable device_tracer_test, as Rohit is already investiging it and it's getting more and more frequent (my previous 2 PRs are failed many times with no pass).

**Comment by jayfurmanek** [comment]
> I suggeste we can disable device_tracer_test, as Rohit is already investiging it and it's getting more and more frequent (my previous 2 PRs are failed many times with no pass).

Agreed. Let's disable that one for now

**Comment by jayfurmanek** [comment]
https://github.com/ROCmSoftwarePlatform/frameworks-internal/issues/3430

**Pull request merged**
