### PR TITLE
Develop upstream sync 240603

### PR DESCRIPTION
**Pull request by mmakevic-amd**

### CODE REVIEW

**Comment by mmakevic-amd** [comment]
retest Ubuntu-GPU-single please
retest Ubuntu-CPU please

**Comment by mmakevic-amd** [comment]
retest Ubuntu-GPU-single please
retest Ubuntu-CPU please

**Comment by mmakevic-amd** [comment]
retest Ubuntu-GPU-single please

**Comment by mmakevic-amd** [comment]
retest Ubuntu-GPU-single please

**Comment by mmakevic-amd** [comment]
retest Ubuntu-GPU-single please

**Comment by mmakevic-amd** [comment]
retest Ubuntu-GPU-single please

**Comment by mmakevic-amd** [comment]
retest Ubuntu-GPU-single please

**Comment by mmakevic-amd** [comment]
retest Ubuntu-GPU-single please

**Review by i-chaochen — APPROVED** [review]

**Review by i-chaochen — APPROVED** [review]
this `"no_rocm", #TODO(rocm): TEMP, sync 24-06-03` is great! helps us to remove these skipped tag later on! let's do this way next time.

But I'm wondering what' happening on this `dot_algorithm_support_test` ? could you post the error message to https://github.com/ROCm/frameworks-internal/issues/8310 ? Thanks!

**Comment by mmakevic-amd** [comment]
> this `"no_rocm", #TODO(rocm): TEMP, sync 24-06-03` is great! helps us to remove these skipped tag later on! let's do this way next time.
> 
> But I'm wondering what' happening on this `dot_algorithm_support_test` ? could you post the error message to [ROCm/frameworks-internal#8310](https://github.com/ROCm/frameworks-internal/issues/8310) ? Thanks!

That test was failing on upstream at the time (https://github.com/ROCm/frameworks-internal/issues/8124#issuecomment-2161675648). I plan to re-enable everything in the next sync :)

**Pull request merged**
