### PR TITLE
Removing the "data_format" references from the LRN op implementation

### PR DESCRIPTION
**Pull request by deven-amd**
removing the data_format references from the LRN op implementation, as they seem to be dead/un-necessary code. This is in preparation for upstreaming ROCm support for the LRN op

### CODE REVIEW

**Comment by whchung** [comment]
Basically that's reverting this commit right:

```
commit 1953359292337d6a0563bf97ea7aabe88430b3b9
Author: Wen-Heng (Jack) Chung <whchung@gmail.com>
Date:   Tue May 15 15:03:42 2018 +0000

    Port MIOpen-specific logic for LRN and LRNGrad
```

**Comment by deven-amd** [comment]
@whchung

not quite. we still need the change that does the NHWC to NCHW conversion. only removing the part that checks whether the format is NHWC or NCHW, since that check was not working anyway.

**Comment by whchung** [comment]
Looking at `tensorflow.raw_ops.pbtxt` it seems indeed `LRN` and `LRNGrad` doesn't have `data_format` attribute so my earlier implementation was incorrect.

**Comment by deven-amd** [comment]
There is only one failure in `rocm-xla`

```
//tensorflow/compiler/mlir/tensorflow/tests:glob_lit_tests             FAILED in 5 out of 5 in 340.2s
```

I do not believe this failure is related to any change in this PR. I ran the test locally and it consistently passes for me.

I am going to retest the `rocm-xla` path, with the hope we get a pass 

link to failing `rocm-xla` log : 
http://ml-ci.amd.com:21096/job/tensorflow-upstream-unit-tests-rocm-xla/529/

**Comment by deven-amd** [comment]
jenkins : retest rocm-xla please

**Pull request merged**
