### PR TITLE
Switching Dockerfile.rocm to use python3.9

### PR DESCRIPTION
**Pull request by stevenireeves**
Added an additional helper script in the install directory.

### CODE REVIEW

**Comment by stevenireeves** [comment]
jenkins : retest Ubuntu GPU-multi please

**Comment by stevenireeves** [comment]
jenkins : retest Ubuntu-GPU-multi please

**Comment by stevenireeves** [comment]
@deven-amd can this PR be pulled or do I need to try and re-run the CI job on another node?

**Comment by deven-amd** [comment]
jenkins : retest Ubuntu-GPU-multi please

**Pull request merged**
