### PR TITLE
[r2.7-rocm-enhanced] fix for roctracer_next_record API on longer static

### PR DESCRIPTION
**Pull request by jayfurmanek**
Merge staging branch in for 5.3

### CODE REVIEW

**Comment by jayfurmanek** [comment]
retest Ubuntu-GPU-multi please

**Comment by jayfurmanek** [comment]
retest Ubuntu-GPU-multi please

**Comment by jayfurmanek** [comment]
retest Ubuntu-GPU-multi please

**Comment by jayfurmanek** [comment]
retest Ubuntu-GPU-single please

**Comment by jayfurmanek** [comment]
retest Ubuntu-GPU-single please

**Comment by jayfurmanek** [comment]
retest Ubuntu-GPU-multi please

**Comment by jayfurmanek** [comment]
retest Ubuntu-GPU-single please

**Comment by jayfurmanek** [comment]
retest Ubuntu-GPU-single please

**Comment by jayfurmanek** [comment]
retest Ubuntu-GPU-single please

**Comment by jayfurmanek** [comment]
retest Ubuntu-GPU-single please

**Comment by okakarpa** [comment]
retest Ubuntu-gpu-multi please

**Comment by okakarpa** [comment]
retest Ubuntu-sanity please

**Comment by okakarpa** [comment]
retest Ubuntu-GPU-single please

**Comment by okakarpa** [comment]
retest Ubuntu-GPU-multi please

**Comment by okakarpa** [comment]
retest Ubuntu-GPU-multi please

**Comment by okakarpa** [comment]
retest Ubuntu-GPU-multi please

**Comment by jayfurmanek** [comment]
retest Ubuntu-GPU-single please

**Comment by okakarpa** [comment]
retest Ubuntu-sanity please

**Comment by jayfurmanek** [comment]
retest Ubuntu-GPU-single please

**Comment by okakarpa** [comment]
retest Ubuntu-sanity please

**Comment by okakarpa** [comment]
retest Ubuntu-GPU-single please

**Comment by okakarpa** [comment]
retest Ubuntu-GPU-single please

**Comment by okakarpa** [comment]
retest Ubuntu-GPU-single please

**Comment by okakarpa** [comment]
retest Ubuntu-GPU-single please

**Comment by okakarpa** [comment]
retest Ubuntu-GPU-single please

**Comment by okakarpa** [comment]
retest Ubuntu-GPU-single please

**Comment by okakarpa** [comment]
retest Ubuntu-sanity please

**Comment by aspamidi** [comment]
retest Ubuntu-sanity please

**Comment by aspamidi** [comment]
ubuntu-sanity

**Comment by aspamidi** [comment]
retest-ubuntu-sanity

**Comment by aspamidi** [comment]
retest Ubuntu-sanity please

**Comment by okakarpa** [comment]
retest Ubuntu-GPU-single please

**Pull request merged**
