### PR TITLE
Fix Gemm related issues for r212 and r213

### PR DESCRIPTION
**Pull request by i-chaochen**
previous PR: https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/pull/2356

This one PASSED all unit tests without problem. Related issues are fixed and slightly increased tolerance compared to the original (0.003) on few tests due to denorm.

### CODE REVIEW

**Comment by jayfurmanek** [comment]
retest gpu-pycpp please

**Comment by i-chaochen** [comment]
> retest gpu-pycpp please

do we have gpu-pycpp CI for other branch rather than develop-upstream?

**Comment by jayfurmanek** [comment]
yes. This branch is protected. Not sure why the tests didn't run

**Review by wenchenvincent — APPROVED** [review]

**Comment by i-chaochen** [comment]
retest gpu-pycpp please

**Comment by i-chaochen** [comment]
retest cpu-non-pip please
retest gpu-non-pip-multi please
retest gpu-pycpp please

**Comment by i-chaochen** [comment]
retest cpu-non-pip please
retest gpu-non-pip-multi please
retest gpu-pycpp please

**Comment by i-chaochen** [comment]
retest gpu-pycpp please

**Comment by i-chaochen** [comment]
retest gpu-pycpp please

**Pull request merged**
