### PR TITLE
RCCL integration into develop-upstream

### PR DESCRIPTION
**Pull request by jeffdaily**
This assumes RCCL has been installed as a package.  Adds tensorflow.contrib.rccl.* collective ops.
```bash
git clone https://github.com/ROCmSoftwarePlatform/rccl.git
mkdir rccl_build
cd rccl_build
CXX=/opt/rocm/bin/hcc cmake ../rccl
make package
sudo dpkg -i *.deb
```

### CODE REVIEW

**Comment by jeffdaily** [comment]
To run the python test for RCCL ops, you must currently use LD_PRELOAD with librccl.so.  Otherwise, you will see the error:
```bash
terminate called recursively
terminate called after throwing an instance of 'std::runtime_error'
terminate called recursively
  what():  Invalid function passed to hipLaunchKernelGGL.
*** Received signal 6 ***
*** BEGIN MANGLED STACK TRACE ***
Aborted (core dumped)
```
Example run of python test:
```bash
LD_PRELOAD=/opt/rocm/lib/librccl.so python tensorflow/contrib/rccl/python/ops/rccl_ops_test.py
```
The C++ test does not require the work-around and should be run using bazel.
Example run of C++ test:
```bash
bazel test --config=opt --config=rocm //tensorflow/contrib/rccl:rccl_manager_test
```

**Comment by jeffdaily** [comment]
The rocm CI build is failing because it does not install RCCL.

**Comment by jeffdaily** [comment]
This PR was started prior to our CI upgrade to rocm 1.9.  Should I rebase this PR or cherry-pick the Dockerfile changes?

**Comment by whchung** [comment]
@jeffdaily whichever way works more easily with you

**Comment by whchung** [comment]
ROCm path is a success. I'll keep this PR open until we get to the bottom of LD_PRELOAD issue, and we can add RCCL unit tests into CI builds.

**Comment by whchung** [comment]
@jeffdaily a question for you: would RCCL test work fine on 1 GPU?

@parallelo a question for you: how many GPUs are configured on ROCm CI nodes as of now?

**Comment by jeffdaily** [comment]
@whchung the current RCCL tests assume 3 GPUs, but that doesn't mean we couldn't write a new test that works fine on 1 GPU.  RCCL supports running with 1 GPU.  I haven't tested the integration yet to see what it does in the case of 1 GPU.  Let me try that and report back.

**Comment by whchung** [comment]
@jeffdaily I mistakenly removed the branch. Let me reopen this PR.

**Comment by whchung** [comment]
jenkins: retest this please

**Comment by jeffdaily** [comment]
Is it a flaky test?  It succeeded in #182.

```
AlreadyExistsError (see above for traceback): Resource a/c/N10tensorflow12StubResourceE
	 [[node ResourceCreateOp_1 (defined at /usr/lib/python3.5/unittest/case.py:600)  = ResourceCreateOp[_device="/job:localhost/replica:0/task:0/device:CPU:0"](StubResourceHandleOp_1)]]
tensorflow/python/kernel_tests/array_ops_test.py", line 1157, in testConcatSlice
```
```
ERROR:tensorflow:Input tensor cannot be a resource variable handle.
	 [[node GuaranteeConst (defined at /usr/lib/python3.5/unittest/case.py:600)  = GuaranteeConst[T=DT_RESOURCE, _device="/job:localhost/replica:0/task:0/device:CPU:0"](resource_var)]]
tensorflow/python/kernel_tests/array_ops_test.py", line 1262, in testResourceRejectio
```
```
ERROR:tensorflow:'axis'[0] = -30 is out of valid range [0, 1
	 [[node ReverseV2 (defined at /usr/lib/python3.5/unittest/case.py:600)  = ReverseV2[T=DT_FLOAT, Tidx=DT_INT32, _device="/job:localhost/replica:0/task:0/device:CPU:0"](ReverseV2/tensor, _arg_Placeholder_0_0)]]
tensorflow/python/kernel_tests/array_ops_test.py", line 351, in testInvalid
```

**Comment by whchung** [comment]
@jeffdaily would you mind resolve the conflicts due to upstream changes and give the test another spin? `array_ops_test` should have nothing to do with this PR.

**Comment by jeffdaily** [comment]
I was having a difficult time resolving the conflicts so I decided to rebase this PR as a new branch and PR.

**Pull request closed without merging**
