### PR TITLE
Develop upstream sync 190708

### PR DESCRIPTION
**Pull request by jeffdaily**

### CODE REVIEW

**Comment by jeffdaily** [comment]
MLIR commit hash is out of sync with MLIR project changes.  See upstream commit 1375ad20ada92d99d8ee32b779dfe8b5f0185345 that changes TF to use LogicalResult instead of bool.  Corresponding change in MLIR was https://github.com/tensorflow/mlir/commit/aecbc1f06fe5d28c480d9767f2cc95e49fcee4ba.  Instead, TF's MLIR hash is 7 commits behind at https://github.com/tensorflow/mlir/commit/f69c871493a0d3168e8d04a4cc7f1104ac0c41c1.

**Comment by jeffdaily** [comment]
jenkins: retest rocm-v2 please

**Comment by jeffdaily** [comment]
jenkins: retest rocm-xla please

**Comment by jeffdaily** [comment]
@whchung Only XLA is failing now.

Executed 525 out of 533 tests: 522 tests pass, 8 fail to build and 3 fail locally.
- //tensorflow/compiler/tests:scatter_nd_op_test_gpu
- //tensorflow/compiler/tests:segment_reduction_ops_test_gpu
- //tensorflow/compiler/xla/tests:tuple_test_gpu

The build failures are due to the downloaded MLIR not matching the expected version of the MLIR integration code.  I fixed this locally (will push soon) by rolling back the selected commit hash for the downloaded MLIR.

In the failure cases, the error is `LLVM ERROR: unsupported libcall legalization`.

**Comment by whchung** [comment]
> In the failure cases, the error is `LLVM ERROR: unsupported libcall legalization`.

relevant logic in LLVM:
https://reviews.llvm.org/D50400

looks like XLA is producing some IR not accepted by AMDGPU backend now.

**Comment by jeffdaily** [comment]
Assuming my last commit fixes the MLIR-related build errors, how would you like to proceed with the XLA path?

**Comment by whchung** [comment]
> Assuming my last commit fixes the MLIR-related build errors, how would you like to proceed with the XLA path?

Let's see if we can understand what (potentially new) subtests are failing, and see if we can quickly fix them.

Doing so would require collecting LLVM IR dump. Refer to the codes at:
https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/blob/develop-upstream/tensorflow/compiler/xla/service/gpu/llvm_gpu_backend/nvptx_backend_lib.cc#L555

Shall they be too hard, we'll disable them with `DISABLED_ON_GPU_ROCM`
https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/blob/develop-upstream/tensorflow/compiler/xla/tests/test_macros.h#L61

**Comment by jeffdaily** [comment]
@whchung what happend to xla?  It was passing with https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/pull/546/commits/5002c729b09580ac2f2cb8525f2488e89792dbed and then it failed after making non-xla changes.

**Comment by jeffdaily** [comment]
jenkins: retest rocm-xla please

**Comment by whchung** [comment]
@jeffdaily could be environment issue. build 538 was good. let's wait for build 540.

**Pull request merged**
