### PR TITLE
develop upstream sync 190415

### PR DESCRIPTION
**Pull request by jerryyin**
Conflict file list:

        tensorflow/compiler/xla/service/gpu/BUILD.orig
        tensorflow/contrib/resampler/kernels/resampler_ops_gpu.cu.cc.orig
        tensorflow/core/grappler/optimizers/remapper.cc.orig
        tensorflow/core/kernels/conv_ops_fused_impl.h.orig
        tensorflow/core/kernels/cwise_op_div.cc.orig
        tensorflow/core/kernels/cwise_op_gpu_div.cu.cc.orig
        tensorflow/core/kernels/cwise_op_mul_1.cc.orig
        tensorflow/core/kernels/gather_nd_op.cc.orig
        tensorflow/core/util/gpu_device_functions.h.orig
        tensorflow/core/util/gpu_device_functions.h~google_upstream_master
        tensorflow/core/util/gpu_kernel_helper.h.orig
        tensorflow/core/util/gpu_kernel_helper.h~google_upstream_master
        tensorflow/core/util/gpu_launch_config.h.orig
        tensorflow/core/util/gpu_launch_config.h~google_upstream_master
        tensorflow/examples/adding_an_op/cuda_op_kernel.cu.cc.orig
        tensorflow/python/keras/BUILD.orig
        tensorflow/python/ops/init_ops_test.py.orig
        tensorflow/tools/ci_build/builds/user_ops/cuda_op_kernel.cu.cc.orig

Will split up the conflict file list as a separate commit in next weeks' merge task.

### CODE REVIEW

**Comment by jerryyin** [comment]
jenkins: retest

**Comment by jerryyin** [comment]
jenkins: ok to test

**Comment by jerryyin** [comment]
Onto looking at the following failures:
//tensorflow/python:auto_mixed_precision_test
//tensorflow/python/keras:integration_test

Just realized that this review ended up squashed into one commit. Not sure how it happened as I didn't use git squash. @whchung Would you suggest me redo the merge to keep the commit history?

**Comment by whchung** [comment]
We want to keep the commit history upstream

**Comment by jerryyin** [comment]
@whchung Sounds good, will fix commit history

**Comment by jerryyin** [comment]
cuda build has some environment related failures.

jenkins: ok to test

**Comment by jerryyin** [comment]
Current state:

- Cuda
   - Multiple build failures due to `tensorrt/include/NvInfer.h: No such file or directory`
   - My suspicion is that the the environment variable `GOOGLE_TENSORRT` set to 1 at some place, causing the header to be needed
   - Very likely introduced in this commit: 8e9ca6617b4637d759da395ad89e783a38ccd5ad. Nothing apparent catch my eye just yet

- rocm-xla
   - CI issue this time
   - Last run failed on `qr_op_test_gpu`

- rocm
   - Failed on flaky tests. Passed last time.  

- rocm-v2
   - Failed on flaky tests. Passed last time.

**Comment by jerryyin** [comment]
jenkins: ok to test

**Comment by jerryyin** [comment]
It kills me to figure out this typo... @Deven-amd FYI, this turns out to be the issue a79c0a2.

**Comment by deven-amd** [comment]
> It kills me to figure out this typo... @deven-amd FYI, this turns out to be the issue [a79c0a2](https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/commit/a79c0a264b8bd3e79f268b5b2f30e732bd357999).

@jerryyin good catch!

It is such a difficult to spot typo too...how did you it? Yet another example that leaves you wondering how good the G CI really is...this should have been spotted upstream!

**Comment by jerryyin** [comment]
@whchung [PR 27957](https://github.com/tensorflow/tensorflow/pull/27957) filed to upstream

**Comment by jerryyin** [comment]
@deven-amd I peeled it off layer by layer just as you suggested.

First use crosstool_wrapper instead of bazel   - issue still there
Then use gcc instead of crosstool_wrapper     - issue still there
Then add -v for verboase output from gcc      - all path looks correct, issue still there
Wait a second, let me look at what is actually in that generated path - Ooooops what is this "incude"!!!

**Comment by whchung** [comment]
@jerryyin 

on `rocm` path, `//tensorflow/python/kernel_tests:conv_ops_test_gpu` seems to timeout in the past few days. could you check if the test would pass locally? we may need to change timeout values.

same goes to `//tensorflow/compiler/tests:qr_op_test_gpu ` on `rocm-xla` path.

**Comment by jerryyin** [comment]
@whchung 

Thanks for reminding. On the `rocm` side, `//tensorflow/python/kernel_tests:conv_ops_test_gpu` is running fine locally (882s, on the edge between medium and large tests timeout). An alternative is to change the size to "large", [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/BUILD#L1488). I can update this if you are ok with it.

On the `rocm-xla` side, `//tensorflow/compiler/tests:qr_op_test_gpu` is failing both locally and in CI. I can confirm that it crashes when [execute on GPU](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/compiler/xla/service/executable.cc#L84). Something a little contradictory I have noticed is (CI node is prj47-rack-46): 

- testLarge2000x2000 doesn't crash in our CI, but is crashing in my local dev machine gfx900
- only testQR32 is crashing in our CI, but multiple testQR# is crashing on my dev machine

I'm not sure how to proceed from here. Any thoughts is welcomed.
 
Some notes below:
The full command for the crashing case in my machine is: 
`./bazel-bin/tensorflow/compiler/tests/qr_op_test_gpu --test_device=XLA_GPU --types=DT_HALF,DT_FLOAT,DT_DOUBLE,DT_UINT8,DT_QUINT8,DT_INT8,DT_QINT8,DT_INT32,DT_QINT32,DT_INT64,DT_BOOL,DT_COMPLEX64,DT_BFLOAT16 QrOpTest.testLarge2000x200`

**Comment by whchung** [comment]
@jerryyin let's change `//tensorflow/python/kernel_tests:conv_ops_test_gpu` to large.

and make `//tensorflow/compiler/tests:qr_op_test_gpu` `no_rocm` for now. I believe its IR emitter may have to be reviewed.

**Comment by whchung** [comment]
@jerryyin hmm.... now `//tensorflow/compiler/xla/tests:token_hlo_test_gpu` is failing on `rocm-xla`. could you do a local test? hope it's just flaky.

**Comment by jerryyin** [comment]
@whchung It crashed locally as well. It doesn't make sense to me as the complaint is `F ./tensorflow/stream_executor/rocm/rocm_driver_wrapper.h:126] Check failed: s.ok() could not find hipModuleGetGlobal in HIP DSO; dlerror: /opt/rocm/lib/libhip_hcc.so: undefined symbol: hipModuleGetGlobal
Aborted (core dumped)` 

My hip_hcc is `1.5.19093`. I might need a newer hip_hcc, though I'm surprised why the container is able to run everything else just fine.

**Comment by whchung** [comment]
thanks for the update. I think as long as `rocm` path is fine i can take this PR.

**Comment by deven-amd** [comment]
you can ignore the crash in `/tensorflow/compiler/xla/tests:token_hlo_test_gpu`.

We have a yet-to-be-diagnosed XLA bug, that will cause "dont-know-how-to-reproduce-locally-but-will-happen-very-rarely-on-CI" crash in a couple of testcases. I have seen it in this testcase, and the other one I have seen it in is `//tensorflow/compiler/xla/tests:xla_hlo_profile_test_gpu`.

**Comment by deven-amd** [comment]
on `//tensorflow/python/kernel_tests:conv_ops_test_gpu`, there seems to be significant variation in runtimes even locally. I had two runs last night, both of which took around 970s. Two runs this morning were both around 690s!  Same container, same node, same everything....only thing different being time of day...dont know what to make of it yet.

**Comment by jerryyin** [comment]
@deven-amd Is you test system also running something else? It can be tricky in the sense that it got stable run-time at the same period of time. 

On the other hand if there is a time-to-time variation like this, an approach to address this might be to profile the time it takes to run each unit and see which one got the biggest run-time variation first.

**Comment by deven-amd** [comment]
@jerryyin, agree with you on profiling. I think we need to profile this test + the CI runs in general...the time for `rocm` has crept upto 3+ hours, that is too high. Need to get a handle on functionality first though

**Comment by sunway513** [comment]
RPT is a good idea, but I would be surprised if the kernel execution time changed between runs to runs. 
Thermal won't be the primary cause of the run time variation, given the cooling condition not changed.  
I'd suggest we roll back the OpenCL package in the container (to ROCm2.2 base) and try to run the tests again. We see quite some perf drops due to OpenCL in ROCm2.3 on some selected configures.

**Comment by sunway513** [comment]
BTW, after reviewed the historical build time [here](http://ml-ci.amd.com:21096/job/tensorflow-upstream-unit-tests/buildTimeTrend), those seem increased to 3H+ after we enabled XLA by default in PR #374.

**Pull request merged**
