### PR TITLE
Fixes to enable the use of hipsolver_wrapper.h.

### PR DESCRIPTION
**Pull request by rsanthanam-amd**

### CODE REVIEW

**Comment by rsanthanam-amd** [comment]
jenkins: retest Ubunty-sanity please

**Comment by rsanthanam-amd** [comment]
jenkins: retest Ubuntu-sanity please

**Comment by rsanthanam-amd** [comment]
Ubuntu-CPU has been failing recently because of some weird keras problem which has nothing to do with this PR so I am going to ignore the failure.

**Review by stevenireeves — APPROVED** [review]
LGTM. 

How was the duplicate find_hipsolver artifact introduced in the weekly sync not breaking? Seems like it would break the builds. Thanks for the catch!

**Comment by stevenireeves** [comment]
> Ubuntu-CPU has been failing recently because of some weird keras problem which has nothing to do with this PR so I am going to ignore the failure.

Do we know if it's running on the same node?

**Comment by rsanthanam-amd** [comment]
> LGTM.
> 
> How was the duplicate find_hipsolver artifact introduced in the weekly sync not breaking? Seems like it would break the builds. Thanks for the catch!

Not sure but it must have been an artifact of an upstream sync merge error.

**Comment by rsanthanam-amd** [comment]
> > Ubuntu-CPU has been failing recently because of some weird keras problem which has nothing to do with this PR so I am going to ignore the failure.
> 
> Do we know if it's running on the same node?

It probably is but this was happening on multiple nodes with another PR that I recently closed without merging.

**Comment by stevenireeves** [comment]
@rsanthanam-amd looks like we're having issues loading the hipsolver datatypes:
From Ubuntu-GPU-multi:
`./tensorflow/core/util/gpu_solvers.h:138:23: error: 'hipsolverOperation_t' does not name a type; did you mean 'hipsparseOperation_t'?
 using gpuSolverOp_t = hipsolverOperation_t;`
 
 Can you verify that TF_ROCM_VERSION is defined in dso_loader?

**Comment by stevenireeves** [comment]
Jenkins : retest Ubuntu-GPU-single please

**Comment by stevenireeves** [comment]
Jenkins : retest Ubuntu-CPU please

**Comment by stevenireeves** [comment]
Jenkins : retest Ubuntu-CPU please

**Comment by rsanthanam-amd** [comment]
jenkins: retest Ubuntu-CPU please

**Comment by rsanthanam-amd** [comment]
jenkins: retest Ubuntu-GPU-single please

**Pull request merged**
