### PR TITLE
[DO NOT MERGE] This PR is solely for testing CI's PR builder

### PR DESCRIPTION
**Pull request by parallelo**

### CODE REVIEW

**Comment by ROCm-Apps-Test** [comment]
Can one of the admins verify this patch?

**Comment by parallelo** [comment]
Jenkins:  retest rocm please

**Comment by parallelo** [comment]
Jenkins: retest rocm please

**Comment by parallelo** [comment]
Jenkins: retest rocm-cpp please

**Comment by parallelo** [comment]
Jenkins: retest rocm-xla please

**Pull request closed without merging**
