### PR TITLE
Weekly Merge 190513

### PR DESCRIPTION
**Pull request by sunway513**
Conflict files:       
        both modified:   tensorflow/compiler/tf2xla/BUILD
        both modified:   tensorflow/compiler/xla/service/gpu/BUILD
        both modified:   tensorflow/compiler/xla/service/gpu/elemental_ir_emitter.cc
        both modified:   tensorflow/core/BUILD
        both modified:   tensorflow/core/kernels/avgpooling_op_gpu.cu.cc
        both modified:   tensorflow/core/kernels/bias_op_gpu.cu.cc
        both modified:   tensorflow/core/kernels/bucketize_op_gpu.cu.cc
        both modified:   tensorflow/core/kernels/compare_and_bitpack_op_gpu.cu.cc
        both modified:   tensorflow/core/kernels/conv_2d_gpu.h
        both modified:   tensorflow/core/kernels/conv_ops.cc
        both modified:   tensorflow/core/kernels/crop_and_resize_op_gpu.cu.cc
        both modified:   tensorflow/core/kernels/cuda_solvers.h
        both modified:   tensorflow/core/kernels/cwise_op_clip_gpu.cu.cc
        both modified:   tensorflow/core/kernels/depthtospace_op_gpu.cu.cc
        both modified:   tensorflow/core/kernels/depthwise_conv_grad_op.cc
        both modified:   tensorflow/core/kernels/depthwise_conv_op.cc
        both modified:   tensorflow/core/kernels/depthwise_conv_op_gpu.h
        both modified:   tensorflow/core/kernels/determinant_op_gpu.cu.cc
        both modified:   tensorflow/core/kernels/diag_op_gpu.cu.cc
        both modified:   tensorflow/core/kernels/dilation_ops_gpu.cu.cc
        both modified:   tensorflow/core/kernels/dynamic_partition_op_gpu.cu.cc
        both modified:   tensorflow/core/kernels/eye_functor_gpu.cu.cc
        both modified:   tensorflow/core/kernels/fused_batch_norm_op.cu.cc
        both modified:   tensorflow/core/kernels/gather_functor_gpu.cu.h
        both modified:   tensorflow/core/kernels/gather_nd_op_gpu.cu.cc
        both modified:   tensorflow/core/kernels/inplace_ops_functor_gpu.cu.cc
        both modified:   tensorflow/core/kernels/lrn_op.cc
        both modified:   tensorflow/core/kernels/lu_op_gpu.cu.cc
        both modified:   tensorflow/core/kernels/matmul_op.cc
        both modified:   tensorflow/core/kernels/matrix_band_part_op_gpu.cu.cc
        both modified:   tensorflow/core/kernels/matrix_set_diag_op_gpu.cu.cc
        both modified:   tensorflow/core/kernels/maxpooling_op.cc
        both modified:   tensorflow/core/kernels/maxpooling_op_gpu.cu.cc
        both modified:   tensorflow/core/kernels/maxpooling_op_gpu.h
        both modified:   tensorflow/core/kernels/multinomial_op_gpu.cu.cc
        both modified:   tensorflow/core/kernels/parameterized_truncated_normal_op_gpu.cu.cc
        both modified:   tensorflow/core/kernels/pooling_ops_3d_gpu.cu.cc
        both modified:   tensorflow/core/kernels/pooling_ops_common.cc
        both modified:   tensorflow/core/kernels/population_count_op_gpu.cu.cc
        both modified:   tensorflow/core/kernels/reduction_gpu_kernels.cu.h
        both modified:   tensorflow/core/kernels/relu_op_gpu.cu.cc
        both modified:   tensorflow/core/kernels/resize_bilinear_op_gpu.cu.cc
        both modified:   tensorflow/core/kernels/resize_nearest_neighbor_op_gpu.cu.cc
        both modified:   tensorflow/core/kernels/scan_ops_gpu.h
        both modified:   tensorflow/core/kernels/scatter_functor_gpu.cu.h
        both modified:   tensorflow/core/kernels/scatter_nd_op_gpu.cu.cc
        both modified:   tensorflow/core/kernels/searchsorted_op_gpu.cu.cc
        both modified:   tensorflow/core/kernels/segment_reduction_ops_gpu.cu.cc
        both modified:   tensorflow/core/kernels/spacetobatch_functor_gpu.cu.cc
        both modified:   tensorflow/core/kernels/spacetodepth_op_gpu.cu.cc
        both modified:   tensorflow/core/kernels/sparse_tensor_dense_matmul_op_gpu.cu.cc
        both modified:   tensorflow/core/kernels/split_lib_gpu.cu.cc
        both modified:   tensorflow/core/kernels/stateful_random_ops_gpu.cu.cc
        both modified:   tensorflow/core/kernels/svd_op_gpu.cu.cc
        both modified:   tensorflow/core/kernels/tile_functor_gpu.h
        both modified:   tensorflow/core/kernels/transpose_functor_gpu.cu.cc
        both modified:   tensorflow/core/kernels/tridiagonal_solve_op_gpu.cu.cc
        both modified:   tensorflow/core/kernels/where_op_gpu.cu.h
        both added:      tensorflow/core/util/gpu_cuda_alias.h
        both modified:   tensorflow/core/util/gpu_kernel_helper.h
        both modified:   tensorflow/core/util/gpu_launch_config.h
        both modified:   tensorflow/examples/adding_an_op/BUILD
        both modified:   tensorflow/examples/saved_model/integration_tests/BUILD
        both modified:   tensorflow/python/kernel_tests/BUILD

### CODE REVIEW

**Comment by whchung** [comment]
@sunway513 It seems the merge for this week is quite challenging:

- bazel-related errors on `cuda`
- certain interfaces in StreamExecutor were changed which breaks `rocm` build.
- and on `rocm-v2` and `rocm-xla` builds it seems we crash at hcc compiler frontend.

**Comment by sunway513** [comment]
@whchung yes, you can also feel the challenges by just looking at the long list of merge conflicts ;-)
I've seen a similar HCC frontend crash on P47 system while it can compile fine on SMC nodes. Let me dig deeper and see.

**Comment by sunway513** [comment]
rocm-v2 path error:
`Execution platform: @bazel_tools//platforms:host_platform
### HCC STATUS_CHECK Error: HSA_STATUS_ERROR_OUT_OF_RESOURCES (0x1008) at file:mcwamp_hsa.cpp line:1220`
It can build correctly on my local node.

**Comment by whchung** [comment]
@sunway513:

- `cuda` and `rocm` paths are correct now.
- let's ignore `rocm-v2` runtime errors for now provided it works fine on your local node.

- for `rocm-xla` path, your latest commit 07049e2 is incorrect. please remove it.

I don't know what exactly is causing the compile error yet. It could be missing this header file inclusion.
#include "tensorflow/compiler/xla/test_helpers.h"

**Comment by whchung** [comment]
My earlier comment was incorrect.
```
#include "tensorflow/compiler/xla/test_helpers.h"
```
didn't help.

According to:
https://github.com/google/googletest/blob/master/googlemock/docs/CheatSheet.md

`::testing::IsEmpty()` should work, but turns out it does not for some unknown reason.
`::testing::SizeIs(0)` on the other hand works fine.

**Comment by sunway513** [comment]
Thanks @whchung , updated it per your suggested, let's see how CI goes.

**Comment by whchung** [comment]
use http://ml-ci.amd.com:21096/job/tensorflow-upstream-unit-tests-rocm-xla/311/ as the CI log for `rocm-xla`

**Comment by whchung** [comment]
@sunway513 `rocm-xla` CI build 311 is a success. The latest build 313 fails but we don't need to worry about it. Build 311 contained exactly the same logic from me, while you made 2 forced updates to trigger 312 / 313. Please go ahead and merge the PR.

**Pull request merged**
