### PR TITLE
Switch to use ROCm 3.1 - Take 2

### PR DESCRIPTION
**Pull request by deven-amd**
Note that starting with ROCm 3.1, we need to account for "relocatable rocm" support.

Starting with ROCm 3.1 and going forward, everytime we change the ROCm version we will need to
* in `Dockerfile.rocm` 
  * update the pointer to ROCm repo (we already do this)
  * set ROCM_PATH to `/opt/rocm-<version>/` 
* in all the scripts that invoke `configure.py`
  * explicitly set `ROCM_PATH=/opt/rocm-<version>/`, before calling `configure.py`

### CODE REVIEW

**Comment by ROCm-Apps-Test** [comment]
Can one of the admins verify this patch?

**Comment by sunway513** [comment]
LGTM, thanks @deven-amd

**Comment by deven-amd** [comment]
jenkins : retest rocm-xla please

**Comment by deven-amd** [comment]
capturing the discussion in Teams here for future reference

this is w.r.t. the `rocm` CI failure for the test `//tensorflow/python:stateful_random_ops_test_gpu`

-------------------------------

Kuznetsov, Eugene, can I request you to reproduce what I am seeing? Want to make sure my observation is reproducable/accurate before getting the HIP team involved.
 
focus on the subtest testFunctionArg within that test.
It essentially
* creates two RNGs with the same seed,
* calls each one once, and then compares their output from the call (which matches)
* compares the internal state after the call (which mismatches )

 
The internal state is updated by this line here : https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/blob/develop-upstream/tensorflow/core/kernels/stateful_random_ops_gpu.cu.cc#L56
 
The if condition guarding that line relies out the thread counter being set to 0, before the kernel is launched here :
https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/blob/develop-upstream/tensorflow/core/kernels/stateful_random_ops_gpu.cu.cc#L88
 
In the failing scenario, it seems as it the counter never gets zeroed out, and hence the if condition always fails. I can say that for certain, because if I change the if condition to check for (counter % total_thread_count ) == ..., the testcase works.
 ```
diff --git a/tensorflow/core/kernels/stateful_random_ops_gpu.cu.cc b/tensorflow/core/kernels/stateful_random_ops_gpu.cu.cc
index 804a2fd..59509e8 100644
--- a/tensorflow/core/kernels/stateful_random_ops_gpu.cu.cc
+++ b/tensorflow/core/kernels/stateful_random_ops_gpu.cu.cc
@@ -52,8 +52,10 @@ __global__ void FillKernel(
   // The last thread updates the state.
   auto total_thread_count = gridDim.x * blockDim.x;
   auto old_counter_value = atomicAdd(&tensorflow_philox_thread_counter, 1);
-  if (old_counter_value == total_thread_count - 1) {
-    UpdateMemWithPhiloxRandom(*philox, output_size, state_data);
+  // if (old_counter_value == total_thread_count - 1) {
+  if ((old_counter_value % total_thread_count) == total_thread_count - 1) {
+    // UpdateMemWithPhiloxRandom(*philox, output_size, state_data);
+    UpdateMemWithPhiloxRandom(*philox, (old_counter_value + 1) / total_thread_count, state_data);
   }
 }
```
running with HIP_TRACE_API indicates that both calls to hipMemcpyToSymbol are invoked and return without error.
 
running with HIP_LAUNCH_BLOCKING makes the testcase pass.
 
Note that the two kernels (to generate the random numbers) are launched in different threads in this testcase (one is in eager mode, other is within tf.function).
 
Wondering how to recreate this behaviour in a smaller TF independent testcase.

-------------------------------

**Comment by deven-amd** [comment]
pushed out a commit that "fixes" the failure in `//tensorflow/python:stateful_random_ops_test_gpu` by removing the need to call `hipMemcpyToSymbol`.

/cc @whchung @ekuznetsov139 @mvermeulen @jerryyin @sunway513 

please review the last commit in this PR for functional correctness. See my previous update in this PR for context.

thanks

**Pull request merged**
