### PR TITLE
Develop upstream sync 190819

### PR DESCRIPTION
**Pull request by deven-amd**

### CODE REVIEW

**Comment by deven-amd** [comment]
all the `rocm-xla` tests are passing, but there seems to be a build failure....looking into it

**Comment by deven-amd** [comment]
this blows...test that was passing the previous two `rocm-xla` CI runs, is now failing and I cannot reproduce the failure locally :(

the test in question is `//tensorflow/compiler/xla/tests:tuple_test_gpu` 

going to ask jenkins to run `rocm-xla` again in hopes of getting a clean run. If it fails again, will put a `no_rocm` tag on it.

**Comment by deven-amd** [comment]
jenkins : retest rocm-xla please

**Comment by whchung** [comment]
@deven-amd I suggest we look twice on `tuple_test_gpu`. Tuples are used literally everywhere in XLA so we shall better not put a `no_rocm` tag on it.

**Comment by deven-amd** [comment]
I looked at the failure log in CI...no functional failures, just a "Segementation fault" in the script that launches the test. I have seen this before in other tests, but have never been able to reproduce this crash locally. They seem to occur only on the CI serves.

```
==================== Test output for //tensorflow/compiler/xla/tests:tuple_test_gpu:                                                                                                                             
Running test /home/jenkins/workspace/tensorflow-upstream-unit-tests-rocm-xla/bazel-ci_build-cache/.cache/bazel/_bazel_jenkins/eab0d61a99b6696edb3d2aff87b585e8/execroot/org_tensorflow/bazel-out/k8-opt/bin/tens\
orflow/compiler/xla/tests/tuple_test_gpu.runfiles/org_tensorflow/tensorflow/compiler/xla/tests/tuple_test_gpu  on GPU 0                                                                                          
[==========] Running 23 tests from 2 test suites.                                                                                                                                                                
[----------] Global test environment set-up.                                                                                                                                                                     
[----------] 21 tests from TupleTest                                                                                                                                                                             
[ RUN      ] TupleTest.TupleConstant                                                                                                                                                                             
2019-08-20 13:16:31.127647: I tensorflow/compiler/xla/service/platform_util.cc:85] platform Host present but no XLA compiler available: could not find registered compiler for platform Host -- check target lin\
kage (hint: try linking in tensorflow/compiler/jit:xla_cpu_jit)                                                                                                                                                  
2019-08-20 13:16:31.130286: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libhip_hcc.so                                                                    
2019-08-20 13:16:31.967534: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x11389e0 initialized for platform ROCM (this does not guarantee that XLA will be used). Devices:                      
2019-08-20 13:16:31.967708: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Vega 10 [Radeon Instinct MI25], AMDGPU ISA version: gfx900                                            
2019-08-20 13:16:31.967934: I tensorflow/compiler/xla/service/platform_util.cc:85] platform Host present but no XLA compiler available: could not find registered compiler for platform Host -- check target lin\
kage (hint: try linking in tensorflow/compiler/jit:xla_cpu_jit)                                                                                                                                                  
2019-08-20 13:16:31.985573: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x122e7d0 initialized for platform Interpreter (this does not guarantee that XLA will be used). Devices:               
2019-08-20 13:16:31.985634: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Interpreter, <undefined>                                                                              
[       OK ] TupleTest.TupleConstant (1948 ms)                                                                                                                                                                   
[ RUN      ] TupleTest.TupleScalarConstant                                                                                                                                                                       
2019-08-20 13:16:33.073801: I tensorflow/compiler/xla/service/platform_util.cc:85] platform Host present but no XLA compiler available: could not find registered compiler for platform Host -- check target lin\
kage (hint: try linking in tensorflow/compiler/jit:xla_cpu_jit)                                                                                                                                                  
2019-08-20 13:16:33.073836: I tensorflow/compiler/xla/service/platform_util.cc:85] platform Host present but no XLA compiler available: could not find registered compiler for platform Host -- check target lin\
kage (hint: try linking in tensorflow/compiler/jit:xla_cpu_jit)                                                                                                                                                  
[       OK ] TupleTest.TupleScalarConstant (174 ms)            
...
...
[       OK ] TupleHloTest.BitcastAfterGTE (231 ms)                                                                                                                                                               
[ RUN      ] TupleHloTest.NonAmbiguousTopLevelAllocation                                                                                                                                                         
2019-08-20 13:16:37.419844: I tensorflow/compiler/xla/service/platform_util.cc:85] platform Host present but no XLA compiler available: could not find registered compiler for platform Host -- check target lin\
kage (hint: try linking in tensorflow/compiler/jit:xla_cpu_jit)                                                                                                                                                  
2019-08-20 13:16:37.419873: I tensorflow/compiler/xla/service/platform_util.cc:85] platform Host present but no XLA compiler available: could not find registered compiler for platform Host -- check target lin\
kage (hint: try linking in tensorflow/compiler/jit:xla_cpu_jit)                                                                                                                                                  
/home/jenkins/workspace/tensorflow-upstream-unit-tests-rocm-xla/bazel-ci_build-cache/.cache/bazel/_bazel_jenkins/eab0d61a99b6696edb3d2aff87b585e8/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/compil\
er/xla/tests/tuple_test_gpu.runfiles/org_tensorflow/tensorflow/tools/ci_build/gpu_build/parallel_gpu_execute: line 63: 52278 Segmentation fault      (core dumped) "$TEST_BINARY" $@   
```

**Pull request merged**
