### PR TITLE
updates to fix CUDA compile errors and get CUDA CI passing again

### PR DESCRIPTION
**Pull request by deven-amd**

### CODE REVIEW

**Comment by deven-amd** [comment]
@whchung 

> Must we use CudaLaunchKernel for those ops?

Not really, but it will have to do for now.

The CudaLaunchKernel definition plus all its references are currently within GOOGLE_CUDA, which is why this compiles on the ROCm side.

We need to first change `CudaLaunchKernel` to `GpuLaunchKernel` (which has ROCm support) and then replace all references to GPU_LAUNCH_KERNEL  with GpuLaunchKernel. 

Upstream code has been introducing `TF_CHECK_OK(CudaLaunchKernel(...` everywhere. 

We use GPU_LAUNCH_KERNEL  in ROCm, which is a macro that does not return "Status", so our code has started diverging at these call sites (upstream has `TF_CHECK_OK(CudaLaunchKernel(...`, we have `GPU_LAUNCH_KERNEL(... `)

Anyway this is a much bigger change, which we need to get to, but is outside the scope of this PR.

**Comment by deven-amd** [comment]
@parallelo 

There are some "No space left on device" errors in the CUDA CI log....can we run out of space in our AWS containers?

**Comment by deven-amd** [comment]
jenkins: retest this please

**Comment by parallelo** [comment]
Our AWS setup has been upgraded to have more disk space (along with a newer AMI).  

The most recent job isn't finished yet, but -- so far, so good.  Let me know if see any out of disk space errors, or anything else strange.

**Comment by whchung** [comment]
@deven-amd It seems the PR now executes till completion on CUDA now. Could you help check those 5 fails and shed some lights whether to worry about them?

**Comment by deven-amd** [comment]
The 5 failures seems to be XLA related(?)
```
FAILED: //tensorflow/python/training/tracking:util_xla_test_gpu
FAILED: //tensorflow/python/training/tracking:util_xla_test_cpu
FAILED: //tensorflow/python/eager:def_function_xla_test_gpu 
FAILED: //tensorflow/python/eager:def_function_xla_test_cpu
ERROR: package contains errors: tensorflow/compiler/xla/service/gpu
```

looking into them now

**Comment by deven-amd** [comment]
@whchung 

I have pushed out a commit that should fix the one build failure. It is a one-liner, please review.

Dont know how to fix the other 4 test failures. The following error occurs in those failures
```
RuntimeError: Error copying tensor to device: /job:localhost/replica:0/task:0/device:XLA_CPU:0. /job:localhost/replica:0/task:0/device:XLA_CPU:0 unknown device.
```

But the build is being done with XLA turned off...so why would the device `XLA_CPU` be present to being with?

**Comment by deven-amd** [comment]
doh!..the CUDA fix breaks the ROCm build

**Comment by whchung** [comment]
@deven-amd is the failure on ROCm paths really caused by the last commit to fix CUDA path? from the log I can't be so sure about it, or you are seeing it locally?

**Comment by deven-amd** [comment]
@whchung I have not looked at the log...assumed that the last commit was the cause. 

will look into it later tonight

**Comment by whchung** [comment]
ok I'll keep the CUDA path running, and issue a retest after it's done. I suspect it's a environment issue on ROCm side.

**Comment by deven-amd** [comment]
The rocm failure does seem to be due to some env/network issue. Hoping it does away with the rerun

from the rocm failure log:
```
gpg: keyserver communications error: keyserver helper general error
gpg: keyserver communications error: unknown pubkey algorithm
gpg: keyserver receive failed: unknown pubkey algorithm
[0mFailed to add key.
The command '/bin/sh -c add-apt-repository -y ppa:openjdk-r/ppa &&     add-apt-repository -y ppa:george-edison55/cmake-3.x' returned a non-zero code: 1
```

The cuda BUILD now finishes without error, but still has the following 5 failures
```
//tensorflow/python/eager:def_function_xla_test_cpu                      FAILED in 3 out of 3 in 4.3s
//tensorflow/python/eager:def_function_xla_test_gpu                      FAILED in 3 out of 3 in 4.6s
//tensorflow/python/training/tracking:util_xla_test_cpu                  FAILED in 3 out of 3 in 4.3s
//tensorflow/python/training/tracking:util_xla_test_gpu                  FAILED in 3 out of 3 in 4.5s
//tensorflow/python/keras:convolutional_recurrent_test                  TIMEOUT in 3 out of 6 in 465.0s
```

The 4 XLA tests (2 really coz they are cpu/gpu) are whitelisted on the `rocm` side. I am guessing they either do not work at all, or we have command CUDA + ROCm bug there.
As for the 5th one, I am hoping it is an intermittent timeout issue.

I am going to issue a retest after this append.

If on the re-run, `rocm` passes and the `cuda` failures are the same, then I think we should accept this PR. I will file a follow up PR to put the `cuda` failures on the whitelist. I want to file a separate PR as there are a couple of other whitelist related updates that I need to make.

**Comment by deven-amd** [comment]
jenkins: retest this please

**Comment by deven-amd** [comment]
In the rerun
* `cuda` has the same 5 failures
* `rocm` passes
* `rocm-xla` has failures, but I do not think there are any regressions. 

I think we should merge this PR, and whitelist the 5 `cuda` failures (PR for that coming later today)

@whchung, let me know if you agree, and if you do please proceed with the merge :)

**Pull request merged**
