### PR TITLE
fixed an invalid assertion check in the unit test - utils_test.cc

### PR DESCRIPTION
**Pull request by mshivama**
Fixed an invalid assertion check in the unit test - utils_test.cc

### CODE REVIEW

**Comment by ROCm-Apps-Test** [comment]
Can one of the admins verify this patch?

**Comment by ROCm-Apps-Test** [comment]
Can one of the admins verify this patch?

**Comment by ROCm-Apps-Test** [comment]
Can one of the admins verify this patch?

**Comment by ROCm-Apps-Test** [comment]
Can one of the admins verify this patch?

**Comment by whchung** [comment]
@mshivama please help specify which bazel tests are affected by this PR.

**Comment by mshivama** [comment]
Hi Jack,

We are working on bringing-up TF on HIP/VDI/PAL (Linux), and this test case is failing in our nightly build and test. And when I had taken a look at the test case, I noticed that we are querying a non-existing GPU device with device no -100, and hence the device name returned should be "UNKNOWN". I could see the similar assertion for CUDA just few lines above the line where I made a fix. Hence, I thought it is a wrong test case, and we should fix it.

**Comment by mshivama** [comment]
And, the test case failed due to this error is:
 //tensorflow/core/grappler/clusters:utils_test

**Comment by whchung** [comment]
@mshivama Thanks for clarification.

**Comment by whchung** [comment]
jenkins: ok to test

**Pull request merged**
