### PR TITLE
Develop upstream sync 180820

### PR DESCRIPTION
**Pull request by sunway513**
Weekly merge from upstream.

### CODE REVIEW

**Comment by parallelo** [comment]
jenkins: retest this please

**Comment by whchung** [comment]
@sunway513 quite a few tests failed due to errors like:

```
2018-08-21 01:14:53.880488: E tensorflow/core/common_runtime/executor.cc:630] Executor failed to create kernel. Not found: No registered 'Const' OpKernel for GPU devices compatible with node {{node Laplace/sample/concat}} = Const[dtype=DT_INT32, value=Tensor<type: int32 shape: [3] values: 10000 10 100>, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()
	 (OpKernel was found, but attributes didn't match)
	.  Registered:  device='XLA_CPU_JIT'; dtype in [DT_FLOAT, DT_DOUBLE, DT_INT32, DT_COMPLEX64, DT_INT64, DT_BOOL, DT_HALF, DT_UINT32, DT_UINT64, DT_STRING]
  device='XLA_GPU_JIT'; dtype in [DT_FLOAT, DT_DOUBLE, DT_INT32, DT_COMPLEX64, DT_INT64, DT_BOOL, DT_BFLOAT16, DT_HALF, DT_UINT32, DT_UINT64, DT_STRING]
  device='XLA_CPU'; dtype in [DT_INT32, DT_INT64, DT_HALF, DT_FLOAT, DT_DOUBLE, DT_COMPLEX64, DT_BOOL]
  device='XLA_GPU'; dtype in [DT_INT32, DT_INT64, DT_HALF, DT_FLOAT, DT_DOUBLE, DT_COMPLEX64, DT_BOOL, DT_BFLOAT16]
  device='CPU'
  device='GPU'; dtype in [DT_VARIANT]
  device='GPU'; dtype in [DT_BOOL]
  device='GPU'; dtype in [DT_COMPLEX128]
  device='GPU'; dtype in [DT_COMPLEX64]
  device='GPU'; dtype in [DT_UINT64]
  device='GPU'; dtype in [DT_INT64]
  device='GPU'; dtype in [DT_QINT32]
  device='GPU'; dtype in [DT_UINT32]
  device='GPU'; dtype in [DT_QUINT16]
  device='GPU'; dtype in [DT_QINT16]
  device='GPU'; dtype in [DT_INT16]
  device='GPU'; dtype in [DT_UINT16]
  device='GPU'; dtype in [DT_QINT8]
  device='GPU'; dtype in [DT_INT8]
  device='GPU'; dtype in [DT_UINT8]
  device='GPU'; dtype in [DT_DOUBLE]
  device='GPU'; dtype in [DT_FLOAT]
  device='GPU'; dtype in [DT_BFLOAT16]
  device='GPU'; dtype in [DT_HALF]
```

this suggests `constant_op.cc` might need to be looked at

**Comment by whchung** [comment]
from http://205.234.28.200:21096/job/tensorflow-upstream-unit-tests/311/console it looks like the issue with `Const` op is still there.

**Comment by sunway513** [comment]
Yes, I've reviewed the `constant_op.cc` but didn't spot issues there, trying something else.

**Comment by sunway513** [comment]
jenkins: retest this please

**Comment by whchung** [comment]
@sunway513 I'll take this PR but could you check the 1 failing case on CUDA path?

**Comment by sunway513** [comment]
@whchung , yep, will look into that.

**Pull request merged**
