### PR TITLE
Switch to ROCm 5.4.0

### PR DESCRIPTION
**Pull request by jayfurmanek**

### CODE REVIEW

**Review by rsanthanam-amd — APPROVED** [review]

**Review by i-chaochen — APPROVED** [review]

**Comment by jayfurmanek** [comment]
retest Ubuntu-sanity please

**Comment by jayfurmanek** [comment]
retest Ubuntu-sanity please

**Comment by jayfurmanek** [comment]
retest Ubuntu-CPU please

**Comment by jayfurmanek** [comment]
retest Ubuntu-GPU-single please

**Comment by jayfurmanek** [comment]
retest Ubuntu-GPU-multi please

**Pull request merged**
