### PR TITLE
Develop upstream sync 211129

### PR DESCRIPTION
**Pull request by rsanthanam-amd**

### CODE REVIEW

**Comment by rsanthanam-amd** [comment]
@deven-amd Please review commit 3e2d7bff0254d3a7e140ad363e3c4efb5fc85674

**Comment by deven-amd** [comment]
> @deven-amd Please review commit [3e2d7bf](https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/commit/3e2d7bff0254d3a7e140ad363e3c4efb5fc85674)

LGTM

**Comment by jayfurmanek** [comment]
Reminder: we'll want to upstream https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/commit/3e2d7bff0254d3a7e140ad363e3c4efb5fc85674 as well.

**Comment by rsanthanam-amd** [comment]
https://github.com/tensorflow/tensorflow/pull/53252

**Comment by jayfurmanek** [comment]
That was fast! :)

**Pull request merged**
