### PR TITLE
Develop upstream sync 200812

### PR DESCRIPTION
**Pull request by jerryyin**
Conflicts:
> tensorflow/compiler/mlir/tools/kernel_gen/gpu_binary_creator.cc
tensorflow/compiler/xla/service/gpu/tests/gpu_noalias_test.cc
tensorflow/compiler/xla/service/mlir_gpu/kernel_lowering.cc
tensorflow/core/kernels/BUILD
tensorflow/python/BUILD
tensorflow/python/eager/def_function_xla_jit_test.py
tensorflow/python/kernel_tests/BUILD
third_party/gpus/rocm_configure.bzl

### CODE REVIEW

**Comment by ROCm-Apps-Test** [comment]
Can one of the admins verify this patch?

**Comment by jerryyin** [comment]
rest rocm-cpp please

**Comment by jerryyin** [comment]
jenkins retest rocm-cpp please

**Comment by jerryyin** [comment]
Jenkins retest rocm please

**Comment by jerryyin** [comment]
Retest rocm please

**Comment by jerryyin** [comment]
For record, ROCm has all pass on this PR [here](http://ml-ci.amd.com:21096/job/develop-upstream-unit-tests/job/tensorflow-upstream-unit-tests/2158/). It altered its result for unknown reasons.

**Pull request merged**
