### PR TITLE
update RCCL tarball to 0.6.0-rc2

### PR DESCRIPTION
**Pull request by jeffdaily**

### CODE REVIEW

**Comment by whchung** [comment]
@jeffdaily could you confirm if this PR goes to `r1.11-rocm-rccl` instead of `develop-upstream`?

**Comment by jeffdaily** [comment]
This PR goes to `r1.11-rocm-rccl`.  @sunway513 asked for it.

**Comment by sunway513** [comment]
@whchung , we eventually need this PR to go to `develop-upstream`, after CQE verifies it can resolve the build issue they've observed on roc-master.

**Comment by whchung** [comment]
Got it. Please submit the PR against `develop-upstream` when we have a green light from CQE.

**Pull request merged**
