### PR TITLE
Develop upstream sync 180911

### PR DESCRIPTION
**Pull request by jeffdaily**

### CODE REVIEW

**Comment by jeffdaily** [comment]
retest this please

**Comment by whchung** [comment]
jenkins: retest this please

@jeffdaily need to add `jenkins`

**Comment by whchung** [comment]
@jeffdaily in this PR, there are additional 17 failures on ROCm path. wondering have you been able to reproduce them locally?

**Comment by whchung** [comment]
jenkins: retest this please

**Comment by whchung** [comment]
@jeffdaily thanks for chasing down the issue. hope this fix from upstream get the issue resolved J

**Comment by whchung** [comment]
@jeffdaily on CUDA path there are terminology errors:

```
tensorflow/contrib/tensorrt/convert/convert_graph.cc:783:7: error: 'CudaGpuId' was not declared in this scope
       CudaGpuId cuda_gpu_id;
       ^
tensorflow/contrib/tensorrt/convert/convert_graph.cc:784:18: error: 'TfToCudaGpuId' is not a member of 'tensorflow::GpuIdManager'
       Status s = GpuIdManager::TfToCudaGpuId(tf_gpu_id, &cuda_gpu_id);
                  ^
tensorflow/contrib/tensorrt/convert/convert_graph.cc:784:58: error: 'cuda_gpu_id' was not declared in this scope
       Status s = GpuIdManager::TfToCudaGpuId(tf_gpu_id, &cuda_gpu_id);
```

Please refer to https://github.com/tensorflow/tensorflow/pull/21000/files for how to change them properly. Unfortunately this PR was not yet merged upstream.

**Comment by whchung** [comment]
@jeffdaily we are almost there, according to the latest available test log ( http://205.234.28.200:21096/job/tensorflow-upstream-unit-tests/376/console ) on ROCm path there is only 1 failure due to timeout now:

```
//tensorflow/python/kernel_tests:cwise_ops_test                         [0m[31m[1mTIMEOUT[0m in 465.0s
```

please check whether it's due to newly added ops on GPU

**Pull request merged**
