### PR TITLE
Updates for ROCm6.0

### PR DESCRIPTION
**Pull request by jayfurmanek**

### CODE REVIEW

**Comment by jayfurmanek** [comment]
retest code-check please

**Comment by jayfurmanek** [comment]
retest Ubuntu-GPU-single please

**Comment by jayfurmanek** [comment]
retest Ubuntu-CPU please

**Comment by jayfurmanek** [comment]
retest gpu-pycpp please

**Comment by jayfurmanek** [comment]
retest Ubuntu-GPU-single please

**Comment by jayfurmanek** [comment]
retest gpu-non-pip-multi please

**Comment by jayfurmanek** [comment]
retest Ubuntu-GPU-multi please

**Comment by jayfurmanek** [comment]
retest gpu-non-pip-multi

**Comment by jayfurmanek** [comment]
retest gpu-non-pip-multi please

**Comment by jayfurmanek** [comment]
retest code-check please

**Comment by jayfurmanek** [comment]
retest Ubuntu-GPU-single please

**Comment by jayfurmanek** [comment]
retest Ubuntu-GPU-single please

**Comment by jayfurmanek** [comment]
retest Ubuntu-CPU please

**Review by i-chaochen — APPROVED** [review]

**Pull request merged**
