### PR TITLE
Develop upstream sync 220725

### PR DESCRIPTION
**Pull request by jayfurmanek**
https://github.com/ROCmSoftwarePlatform/frameworks-internal/issues/2202

### CODE REVIEW

**Comment by jayfurmanek** [comment]
retest Ubuntu-GPU-single please

**Comment by jayfurmanek** [comment]
retest Ubuntu-GPU-multi

**Comment by jayfurmanek** [comment]
retest Ubuntu-GPU-multi please

**Comment by jayfurmanek** [comment]
retest Ubuntu-GPU-single please

**Review by rsanthanam-amd — APPROVED** [review]

**Pull request merged**
