### PR TITLE
QA script for XLA under tensorflow-develop-upstream

### PR DESCRIPTION
**Pull request by i-chaochen**
QA team can use this to test XLA 

```
./tensorflow/tools/ci_build/linux/rocm/run_xla.sh
```

### CODE REVIEW

**Review by jayfurmanek — APPROVED** [review]

**Comment by jayfurmanek** [comment]
Can you also add to: https://github.com/ROCm/tensorflow-upstream/tree/develop-upstream-QA-rocm62

**Comment by i-chaochen** [comment]
done https://github.com/ROCm/tensorflow-upstream/pull/2495

**Comment by i-chaochen** [comment]
retest Ubuntu-GPU-multi please
retest Ubuntu-GPU-single please

**Comment by i-chaochen** [comment]
retest Ubuntu-GPU-single please

**Comment by i-chaochen** [comment]
retest Ubuntu-GPU-single please

**Comment by i-chaochen** [comment]
retest Ubuntu-GPU-single please

**Comment by i-chaochen** [comment]
retest Ubuntu-GPU-single please

**Comment by i-chaochen** [comment]
retest Ubuntu-GPU-single please

**Comment by i-chaochen** [comment]
retest Ubuntu-GPU-single please

**Comment by i-chaochen** [comment]
retest Ubuntu-GPU-single please

**Comment by i-chaochen** [comment]
retest Ubuntu-GPU-single please

**Comment by i-chaochen** [comment]
retest Ubuntu-GPU-single please

**Comment by i-chaochen** [comment]
retest Ubuntu-GPU-single please

**Comment by i-chaochen** [comment]
retest Ubuntu-GPU-single please

**Comment by i-chaochen** [comment]
retest Ubuntu-GPU-single please

**Comment by i-chaochen** [comment]
retest Ubuntu-GPU-single please

**Pull request merged**
