### PR TITLE
Develop upstream sync 191120

### PR DESCRIPTION
**Pull request by sunway513**
Merge conflicts:    
        both modified:   tensorflow/compiler/tests/BUILD
        both modified:   tensorflow/compiler/tf2xla/BUILD
        both modified:   tensorflow/core/kernels/fused_batch_norm_op.cc
        both modified:   tensorflow/python/grappler/auto_mixed_precision_test.py
        both modified:   tensorflow/tensorflow.bzl
        both modified:   tensorflow/tools/ci_build/install/install_bazel.sh
        both modified:   third_party/gpus/crosstool/hipcc_cc_toolchain_config.bzl.tpl

### CODE REVIEW

**Comment by apivovarov** [comment]
XLA build failed

**Comment by sunway513** [comment]
@deven-amd ,I've confirmed the bazel version bumped to 1.1.0 in this weekly merge. However, in the cuda CI run we still observed the "undefined symbol" issue, hence quite some tests are failed there.

**Comment by sunway513** [comment]
rocm-xla path has one MLIR test failure:
`//tensorflow/compiler/mlir/xla/tests:legalize-tf-full-conversion.mlir.test`
Error message:
```
/home/pensun/tensorflow-upstream/bazel-ci_build-cache/.cache/bazel/_bazel_root/eab0d61a99b6696edb3d2aff87b585e8/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/compiler/mlir/xla/tests/legalize-tf-full-conversion.mlir.test.runfiles/org_tensorflow/tensorflow/compiler/mlir/xla/tests/legalize-tf-full-conversion.mlir:17:6: error: expected error "failed to legalize operation 'tf.OpA'" was not produced
  // expected-error@+1 {{failed to legalize operation 'tf.OpA'}}
```

**Comment by parallelo** [comment]
Picking up this upstream-sync from Peng's initial work.  

Current status:  
* rocm: pass
* rocm-cpp: pass
* rocm-xla: 2 unit test failures
* cuda: 52 fail to build, 28 unit test failures

Working on further triage now.

**Comment by parallelo** [comment]
Looking at the rocm-xla failures, there are some reports of `HSA_STATUS_ERROR_OUT_OF_RESOURCES` and also `Failed to memset memory: HIP_ERROR_InvalidValue`.  Need to check whether these are repeatable, or if this was a sporadic platform issue.

Jenkins: retest rocm-xla please

**Comment by parallelo** [comment]
In terms of the XLA side, I see 1 MLIR failure locally:
```
//tensorflow/compiler/mlir/xla/tests:legalize-tf-full-conversion.mlir.test
```
```
Command Output (stderr):
--
/root/.cache/bazel/_bazel_root/86706540226bed5af3f7ba9c1699e357/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/compiler/mlir/xla/tests/legalize-tf-full-conversion.mlir.test.runfiles/org_tensorflow/tensorflow/compiler/mlir/xla/tests/legalize-tf-full-conversion.mlir:17:6: error: expected error "failed to legalize operation 'tf.OpA'" was not produced
  // expected-error@+1 {{failed to legalize operation 'tf.OpA'}}
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

This recent commit looks like a potential culprit:  https://github.com/tensorflow/tensorflow/commit/612a496602a0c4d166152cc1ba5a2b4cdd9414c2

**Comment by parallelo** [comment]
The 2+ types of build errors we are seeing on `cuda` appear related to these reported Issues in the official repo:
https://github.com/tensorflow/tensorflow/issues/34538
https://github.com/tensorflow/tensorflow/issues/34439

**Comment by deven-amd** [comment]
abandoning this PR, as it is superseded by PR #720

**Comment by parallelo** [comment]
We found significant issues with building on CUDA targets that originate from the upstream repo.  

Upstream [CUDA build](http://ml-ci.amd.com:21096/job/tensorflow-cuda/1/console):  
```
Executed 1290 out of 1340 tests: 1248 tests pass, 50 fail to build, 42 fail locally.
Build did NOT complete successfully
```
Error signature:  
```
ImportError: /home/ubuntu/workspace/tensorflow-cuda/bazel-ci_build-cache/.cache/bazel/_bazel_ubuntu/eab0d61a99b6696edb3d2aff87b585e8/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_2_tf_python_api_gen_v2.runfiles/org_tensorflow/tensorflow/compiler/tf2tensorrt/_wrap_py_utils.so: undefined symbol: _ZN10tensorflowlsERSoRKNS_6StatusE
----------------
Note: The failure of target //tensorflow:create_tensorflow.python_api_2_tf_python_api_gen_v2 (with exit code 1) may have been caused by the fact that it is a Python 2 program that was built in the host configuration, which uses Python 3. You can change the host configuration (for the entire build) to instead use Python 2 by setting --host_force_python=PY2.
If this error started occurring in Bazel 0.27 and later, it may be because the Python toolchain now enforces that targets analyzed as PY2 and PY3 run under a Python 2 and Python 3 interpreter, respectively. See https://github.com/bazelbuild/bazel/issues/7899 for more information.
```
 
Undefined symbols:
* `_ZTIN10tensorflow6DeviceE` (82 undefined symbol errors)
* `_ZN10tensorflowlsERSoRKNS_6StatusE` (91 undefined symbol errors)
* `_ZTIN6google8protobuf7MessageE` (6 undefined symbol errors)

We'll be submitting an Issue to upstream, temporarily disabling our CUDA PR builder, and also tracking the upstream status of CUDA.  It is likely that upstream devs started using a new build setting after they transitioned to Bazel 1.x.  Our tests with `--host_force_python` did not seem to have an effect.

This upstream-sync is now stale and is being closed.

**Pull request closed without merging**
