### PR TITLE
enable hipOccupancyMaxPotentialBlockSize

### PR DESCRIPTION
**Pull request by jeffdaily**

### CODE REVIEW

**Comment by jeffdaily** [comment]
This PR will fail until our CI moves to ROCm 2.7.

**Comment by jeffdaily** [comment]
@whchung I do not see `hipOccupancyMaxActiveBlocksPerMultiprocessor` as part of HIP ROCm 2.7.   But it will be part of ROCm 2.8.

When I run our test suite on a ROCm 2.7 system (since our CI is still on 2.6), there aren't many tests that actually exercise this new code.  I added a `VLOG(0)` output to indicate when this new code is exercised, and how it might change the resulting `block_count` and `thread_per_block`.  These are the affected tests:

- tensorflow/python/kernel_tests/neon_depthwise_conv_op_test/test.log
- tensorflow/python/nn_grad_test/test.log
- tensorflow/python/nn_grad_test_gpu/test.log
- tensorflow/python/image_ops_test_gpu/test.log
- tensorflow/python/keras/convolutional_test_gpu/test.log
- tensorflow/python/keras/convolutional_test/test.log
- tensorflow/python/keras/backend_test/test.log
- tensorflow/python/image_ops_test/test.log

I don't have any info on which kernels are being launched differently, only a high level view of whether this code change has an impact.  Of the tests above that are affected, I have the following stats:

- total kernel invocations using new API: 2009
- new block_count value with change: 1781
- new thread_per_block value with change: 493

It seems `block_count`, at least for the affected tests, is frequently different from what our original code calculates.

**Comment by jeffdaily** [comment]
jenkins retest please

**Comment by jerryyin** [comment]
jenkins retest this please

**Comment by jeffdaily** [comment]
jenkins retest rocm-xla please

**Comment by jeffdaily** [comment]
`//tensorflow/compiler/xla/tests:conditional_test_gpu` is failing.  I cannot reproduce locally.  Is it just flaky?

**Comment by sunway513** [comment]
IIRC this is one of the internment failures I've seen.

**Comment by sunway513** [comment]
Hi @jeffdaily , just discussed with @deven-amd , you can disable those XLA unit tests that would fail intermittently on CI.

**Comment by deven-amd** [comment]
jenkins: retest this please

**Comment by deven-amd** [comment]
@jeffdaily, now that we have moved up to ROCm 2.8, can we take this PR?

**Comment by jeffdaily** [comment]
@deven-amd yes, we can take this PR now.

**Pull request merged**
