### PR TITLE
Updating Dockerfile.rocm to install/use Python 3.6 by default

### PR DESCRIPTION
**Pull request by deven-amd**
/cc @parallelo @ekuznetsov139

### CODE REVIEW

**Comment by ROCm-Apps-Test** [comment]
Can one of the admins verify this patch?

**Comment by deven-amd** [comment]
so simply replacing 
```
RUN /install/install_pip_packages.sh
```
with
```
RUN /install/install_python3.6_pip_packages.sh
```
in `Dockerfile.rocm` does not work.

need to figure out something more intelligent

**Comment by deven-amd** [comment]
After the commit to update the CI scripts to explicitly set the PYTHON_BIN_PATH to python3.6, we get the following 2 failures in `rocm`

```
//tensorflow/python/keras/tests:convert_to_constants_test                FAILED in 3 out of 3 in 42.7s
//tensorflow/tools/api/tests:module_test                                 FAILED in 3 out of 3 in 5.4s
```

The failure in `convert_to_constants_test` is a crash and is not reproducible locally...do not know what is going on there.

The failure in `module_test` is

```
======================================================================                                                                                          
ERROR: testSummaryMerged (__main__.ModuleTest)                                                                                                                  
testSummaryMerged (__main__.ModuleTest)                                                                                                                         
----------------------------------------------------------------------                                                                                          
Traceback (most recent call last):                                                                                                                              
  File "/home/jenkins/workspace/develop-upstream-unit-tests/tensorflow-upstream-unit-tests/bazel-ci_build-cache/.cache/bazel/_bazel_jenkins/eab0d61a99b6696edb3$
    tf.summary.image                                                                                                                                            
AttributeError: module 'tensorflow._api.v2.summary' has no attribute 'image'                                                                                    
                                                                                                                                                                
```

This I am able to reproduce locally, though I have not yet looked into why switching to Python3.6 will cause this error to show up.

**Comment by deven-amd** [comment]
The cause of the failure in `module_test` turned out be that the `tensorboard` package was not installed for python3.6. So added a commit to update in the `install_python3.6_pip_packages.sh` script to install tensorboard.

Also pushed out another commit to update the `build_rocm_python3` and `build_rocm_xla_python3` scripts to explicitly use python3.6

**Comment by deven-amd** [comment]
jenkins: retest rocm please

**Comment by deven-amd** [comment]
@parallelo @sunway513 

Please review the PR and merge it in, when you deem appropriate.

Note that once this PR is merged, some on the CI jobs (that have shell scripts the assume the presence of the line `RUN /install/install_pip_packages.sh` in `Dockerfile.rocm`) will need to be updated. So those changes will need to be made immediately after this PR is merged.

**Comment by sunway513** [comment]
@deven-amd , is it possible to set the docker environment and let python3 to point to python3.6?

**Comment by deven-amd** [comment]
> @deven-amd , is it possible to set the docker environment and let python3 to point to python3.6?

We should be able to do it. What would we gain by doing do?

**Comment by sunway513** [comment]
> We should be able to do it. What would we gain by doing do?

From my naive thinking, this would touch fewer parts of the script and make the build script easier to port to other python3 variants. Also, if we could keep python3 as an option, then most of the scripts we draft for QA and other teams wouldn't need to be updated.

**Comment by deven-amd** [comment]
@sunway513 what you are suggesting make sense.

let's try that change out. I will push out a commit to 
* make python3 point to python3.6
* undo the changes to `build_rocm*` + CI scripts that explicitly refer to Python 3.6

**Comment by deven-amd** [comment]
@parallelo this PR is good to go. Can I go ahead with the merge?

Asking permission because it may break any CI jobs we have, that build wheel packages for different python versions, if they rely on the presence of the `RUN /install/install_pip_packages.sh` line in `Dockerfile.rocm`

Once this PR is in, we will need to monitor all the CI jobs, find the ones that are affected by this, and fix them (unless ofcourse you have a list of all such jobs and we can pro-actively fix them)

**Comment by deven-amd** [comment]
@parallelo ... see comment above

**Comment by parallelo** [comment]
This is going to take some coordination.  Offline, let's come up with a list of all our essential CI projects that we need to immediately monitor and potentially fix after this type of change.

**Comment by deven-amd** [comment]
closing this PR since with the switch to using Ubuntu 18.04, this PR is no longer needed. 
Default python version is 3.6 in Ubuntu 18.04

**Pull request closed without merging**
