### PR TITLE
ROCm 4.3.1 compat for the self_adjoin_eig_op.

### PR DESCRIPTION
**Pull request by stevenireeves**

### CODE REVIEW

**Comment by deven-amd** [comment]
LGTM

**Comment by stevenireeves** [comment]
jenkins : retest Ubuntu-GPU-multi please

**Comment by stevenireeves** [comment]
jenkins : retest Ubuntu-GPU-multi please

**Comment by stevenireeves** [comment]
jenkins : retest Ubuntu-GPU-multi please

**Pull request merged**
