### PR TITLE
CUDA target-related updates to facilitate upstreaming

### PR DESCRIPTION
**Pull request by parallelo**

### CODE REVIEW

**Comment by parallelo** [comment]
FYI - Consider this PR as a placeholder -- some further updates are required

**Comment by whchung** [comment]
Is it possible to add NV nodes to the Jenkins build cluster, and have the PR be tested on those nodes?

**Comment by whchung** [comment]
From the look of it there are still some places missing:
- `cupti-wrapper`

**Comment by parallelo** [comment]
Still at least one more unresolved issue w.r.t. `gpu_transfer_manager.cc`

**Comment by whchung** [comment]
@parallelo Almost there. I’ve notified you how the file shall be changed via Slack.

**Comment by parallelo** [comment]
With the last few commits (plus the uncommitted mod below), we're now able to build and run unit tests successfully on a CUDA system (with just two failing unit tests).
```
Executed 535 out of 535 tests: 533 tests pass and 2 fail locally
```
The only other missing piece is regarding the `cupti_wrapper`.  The below mod is necessary in order to build successfully with a CUDA target.  So, we need to think about how to handle this on both ROCm and CUDA.  
```
diff --git a/tensorflow/core/platform/default/gpu/BUILD b/tensorflow/core/platform/default/gpu/BUILD
index 23744af..5494aa1 100644
--- a/tensorflow/core/platform/default/gpu/BUILD
+++ b/tensorflow/core/platform/default/gpu/BUILD
@@ -4,19 +4,19 @@ load(
     "tf_gpu_library",
 )
 
-#tf_gpu_library(
-#    name = "cupti_wrapper",
-#    srcs = [
-#        "cupti_wrapper.cc",
-#    ],
-#    hdrs = [
-#        "cupti_wrapper.h",
-#    ],
-#    copts = tf_copts(),
-#    gpu_deps = [
-#        "//tensorflow/core:stream_executor",
-#        "@local_config_cuda//cuda:cupti_headers",
-#    ],
-#    data = ["@local_config_cuda//cuda:cupti_dsos"],
-#    visibility = ["//visibility:public"],
-#)
+tf_gpu_library(
+    name = "cupti_wrapper",
+    srcs = [
+        "cupti_wrapper.cc",
+    ],
+    hdrs = [
+        "cupti_wrapper.h",
+    ],
+    copts = tf_copts(),
+    gpu_deps = [
+        "//tensorflow/core:stream_executor",
+        "@local_config_cuda//cuda:cupti_headers",
+    ],
+    data = ["@local_config_cuda//cuda:cupti_dsos"],
+    visibility = ["//visibility:public"],
+)
```

**Comment by whchung** [comment]
@parallelo Let's try make `cupti_wrapper` an empty target on ROCm. consult `tensorflow/core/kernels/BUILD`

```
load("@local_config_rocm//rocm:build_defs.bzl", "if_rocm_is_configured")
```
Use `if_rocm_is_configured` to drive contents inside `cupti_wrapper` target.

**Comment by whchung** [comment]
The client for `cupti_wrapper`, `device_tracer.cc` is already a dummy guarded by C macro `GOOGLE_CUDA`, and its corresponding target `device_tracer` in `core/BUILD` has also be guarded by bazel function `if_cuda_is_configured()`.

**Comment by whchung** [comment]
jenkins: retest this please

**Pull request merged**
