### PR TITLE
Develop upstream sync 181008

### PR DESCRIPTION
**Pull request by jeffdaily**

### CODE REVIEW

**Comment by jeffdaily** [comment]
If I ROCm-enable cwise_op_xlogy, then the linker fails with:
```
INFO: From Linking tensorflow/python/_pywrap_tensorflow_internal.so [for host]:
Generating AMD GCN kernel failed in ld.lld for target: gfx900
/opt/rocm/hcc/bin/ld.lld: error: relocation R_AMDGPU_REL32_LO cannot be used against symbol clog; recompile with -fPIC
>>> defined in /tmp/tmp.rKRyxlPaLE/kernel-gfx900.hsaco.isabin
>>> referenced by /tmp/tmp.rKRyxlPaLE/kernel-gfx900.hsaco.isabin:(void Eigen::internal::EigenMetaKernel<Eigen::TensorEvaluator<Eigen::TensorAssignOp<Eigen::TensorMap<Eigen::Tensor<std::complex<double>, 1, 1, int>, 16, Eigen::MakePointer>, Eigen::TensorCwiseUnaryOp<Eigen::internal::scalar_left<std::complex<double>, std::complex<double>, Eigen::internal::xlogy_op<std::complex<double> > >, Eigen::TensorMap<Eigen::Tensor<std::complex<double> const, 1, 1, int>, 16, Eigen::MakePointer> const> const> const, Eigen::GpuDevice>, int>(Eigen::TensorEvaluator<Eigen::TensorAssignOp<Eigen::TensorMap<Eigen::Tensor<std::complex<double>, 1, 1, int>, 16, Eigen::MakePointer>, Eigen::TensorCwiseUnaryOp<Eigen::internal::scalar_left<std::complex<double>, std::complex<double>, Eigen::internal::xlogy_op<std::complex<double> > >, Eigen::TensorMap<Eigen::Tensor<std::complex<double> const, 1, 1, int>, 16, Eigen::MakePointer> const> const> const, Eigen::GpuDevice>, int))

/opt/rocm/hcc/bin/ld.lld: error: relocation R_AMDGPU_REL32_HI cannot be used against symbol clog; recompile with -fPIC
>>> defined in /tmp/tmp.rKRyxlPaLE/kernel-gfx900.hsaco.isabin
>>> referenced by /tmp/tmp.rKRyxlPaLE/kernel-gfx900.hsaco.isabin:(void Eigen::internal::EigenMetaKernel<Eigen::TensorEvaluator<Eigen::TensorAssignOp<Eigen::TensorMap<Eigen::Tensor<std::complex<double>, 1, 1, int>, 16, Eigen::MakePointer>, Eigen::TensorCwiseUnaryOp<Eigen::internal::scalar_left<std::complex<double>, std::complex<double>, Eigen::internal::xlogy_op<std::complex<double> > >, Eigen::TensorMap<Eigen::Tensor<std::complex<double> const, 1, 1, int>, 16, Eigen::MakePointer> const> const> const, Eigen::GpuDevice>, int>(Eigen::TensorEvaluator<Eigen::TensorAssignOp<Eigen::TensorMap<Eigen::Tensor<std::complex<double>, 1, 1, int>, 16, Eigen::MakePointer>, Eigen::TensorCwiseUnaryOp<Eigen::internal::scalar_left<std::complex<double>, std::complex<double>, Eigen::internal::xlogy_op<std::complex<double> > >, Eigen::TensorMap<Eigen::Tensor<std::complex<double> const, 1, 1, int>, 16, Eigen::MakePointer> const> const> const, Eigen::GpuDevice>, int))
```

@deven-amd any ideas if this is related to Eigen?

**Comment by whchung** [comment]
@jeffdaily I believe it has something to do with how complex values are handled in Eigen. can you try remove `complex64, complex128` from `cwise_op_gpu_xlogy.cu.cc`?

**Comment by deven-amd** [comment]
@jeffdaily will look into this today...have kicked off a build locally to replicate the issue

**Comment by deven-amd** [comment]
no reference to `clog` in the Eigen code...need to first figure out where the clog reference is getting in
```
rocm-user@prj47-rack-10:~/ROCM_GIT_MIRROR/eigen$ pwd
/home/rocm-user/ROCM_GIT_MIRROR/eigen
rocm-user@prj47-rack-10:~/ROCM_GIT_MIRROR/eigen$ grep clog -r .
rocm-user@prj47-rack-10:~/ROCM_GIT_MIRROR/eigen$ 
```

**Comment by deven-amd** [comment]
interesting .... build succeeds for me when I build using the `build_rocm_python3` script

**Comment by jeffdaily** [comment]
You rocm-enabled the xlogy in your local build?

**Comment by deven-amd** [comment]
I thought that was already in the commits

**Comment by whchung** [comment]
@deven-amd `clog` is inside C++ library, used inside Eigen by `numext::log` which calls `std::log`, and the implementation of `std::log` calls `clog`. So that's why I recommended disabling complex support on GPU for `xlogy` operator in my earlier comment.

**Comment by jeffdaily** [comment]
No, sorry.  When it failed, I rolled it back and enabled the other new ops individually until I found the one that was failing.
Files:
- tensorflow/core/kernels/cwise_op_gpu_xlogy.cu.cc
- tensorflow/core/kernels/cwise_op_xlogy.cc

**Comment by deven-amd** [comment]
ok enabled it, and kicked off the build again

**Pull request merged**
