### PR TITLE
Develop upstream sync 190408

### PR DESCRIPTION
**Pull request by jerryyin**
Comflict file list:
        tensorflow/compiler/xla/service/gpu/ir_emitter_nested.cc.orig
        tensorflow/core/kernels/depthwise_conv_op_gpu.h.orig

Targets able to build locally:
        //tensorflow/tools/pip_package:build_pip_package
        //tensorflow/compiler/xla:all

### CODE REVIEW

**Comment by whchung** [comment]
@jerryyin let's fix the build errors first. i'll swing by later today to give you some hints.

**Comment by jerryyin** [comment]
@whchung Strangely enough, the other way around doesn't work. Compilation issue remain to be 

> 'Eigen::internal::UseCustomContractionKernels':  no overloaded function has restriction specifiers that are compatible with the ambient context 'packLhs'
...

My code change below
> // tensorflow/core/kernels/eigen_contraction_kernel.cc
EIGEN_DEVICE_FUNC EIGEN_DONT_INLINE bool UseCustomContractionKernels() {
#if (defined(\_\_NVCC\_\_)) || (defined(\_\_HIP_DEVICE_COMPILE\_\_))
  return true;
#else
  ...
#endif
}

I can't fully explain why, just just went ahead with updating the `eigen_contraction_kernel_with_mkl` build target as in the previous commit.

**Comment by whchung** [comment]
> I can't fully explain why, just just went ahead with updating the `eigen_contraction_kernel_with_mkl` build target as in the previous commit.

Did you change the declaration as well?

**Comment by jerryyin** [comment]
@whchung Oooops! You are right. I forget to change the declaration is the reason. I did a quick check offline, and confirmed that the code change work as well. Let me know if you prefer the other way.

**Comment by whchung** [comment]
I'm fine either way. But considering the effort to get the implementation upstreamed, maybe source-level changes may be better.

**Comment by jerryyin** [comment]
@whchung Sounds good to me

**Comment by whchung** [comment]
@jerryyin per discussion it's likely some failures are caused in upstream TF, ` //tensorflow/python/kernel_tests:cwise_ops_test` is a good example.

please check `git blame` of upstream TF and see have these tests been revised upstream since yesterday. Also please compare the logs between `cuda` and `rocm` to determine if those failures share the same behavior (likely an upstream issue), or they have platform-specific traits (likely an issue in the port).

**Comment by whchung** [comment]
@jerryyin now we only need to look at the remaining two in XLA:

```
//tensorflow/compiler/xla/tests:convolution_test_autotune_disabled_gpu
//tensorflow/compiler/xla/tests:dot_operation_test_autotune_disabled_gpu
```

**Comment by jerryyin** [comment]
@whchung Thanks for reminding!

**Comment by whchung** [comment]
@jerryyin some quick analysis. For `//tensorflow/compiler/xla/tests:dot_operation_test_autotune_disabled_gpu` it seems the failures are due to 2 categories:

- rocBLAS does not support `complex<float>` : I think we have no choice but to disable such tests or modify them so complex numbers are not used on ROCm path
- rocBLAS does not currently support the DoBlasGemmStridedBatched operation for the "Eigen::half" dataype : we were just talking about fixing this in `rocm_blas.cc`. We can disable them first in this PR and fix later in subsequent PRs, or we fix them here if a fix is easy to attain. I think it's up to.

**Comment by whchung** [comment]
jenkins: retest this please

**Comment by whchung** [comment]
jenkins: retest this please

**Comment by whchung** [comment]
jenkins: retest this please

**Comment by whchung** [comment]
@parallelo it seems `prj47-rack-13` is somehow acting funky. all jobs submitted to the node would always result in failure in `docker prune`. I just hit its `reboot` job, but it doesn't seem to be back online.

**Comment by whchung** [comment]
jenkins: retest this please

**Comment by jerryyin** [comment]
> I checked upstream commit which introduced these 2 commits. I believe they have no affect on ROCm path, and since we are keeping `dot_operation_test` and `convolution_test` as `no_rocm` I think we can just do the same for these 2, and fix them in subsequent PRs. I just pushed a new commit to address this.

@whchung Agreed, it does look like those two are a step forward of the original  `dot_operation_test` and `convolution_test`. I double checked the xla test result and confirmed that those 2 are only ones left. Now seems that this weeks upstream task is a good lesson to me on how upstream could break us in different ways.

**Comment by jerryyin** [comment]
@whchung @parallelo I was looking at [this link](https://stackoverflow.com/questions/49024987/docker-prune-stuck-in-a-prune-operation-is-already-running) for the fix of `docker system prune` issues. I wonder next time if when this happens again, we might be able to manually go over the sequence to verify the fixing sequence works as described. 

If it does works, we could script up a loop to do `docker inspect <container id>`, on the ids returned by `docker ps -a -q`, then kill the container ids that returns nothing.

**Comment by parallelo** [comment]
Hi @jerryyin - Been looking into the dreaded docker prune hang.  I'm pretty sure docker also hangs when trying to kill the bad container.  Our next step is to try restarting the docker service before doing a prune.

**Comment by whchung** [comment]
`rocm` build seems to have some environment issue:
http://ml-ci.amd.com:21096/job/tensorflow-upstream-unit-tests/860/console 

I'm taking this PR based on the fact other 3 paths are passing.

**Pull request merged**
