### PR TITLE
Develop upstream sync 180903

### PR DESCRIPTION
**Pull request by jeffdaily**
Weekly sync with upstream.

### CODE REVIEW

**Comment by whchung** [comment]
@jeffdaily @sunway513 how far are we getting this PR merged

**Comment by jeffdaily** [comment]
After @deven-amd 's fixes and my fix to the cuda build, these are the remaining failures:
```
//tensorflow/python/estimator:keras_test                                TIMEOUT in 1215.0s
  /root/.cache/bazel/_bazel_root/86706540226bed5af3f7ba9c1699e357/execroot/org_tensorflow/bazel-out/k8-opt/testlogs/tensorflow/python/estimator/keras_test/test.log
//tensorflow/python:init_ops_test                                        FAILED in 9.5s
  /root/.cache/bazel/_bazel_root/86706540226bed5af3f7ba9c1699e357/execroot/org_tensorflow/bazel-out/k8-opt/testlogs/tensorflow/python/init_ops_test/test.log
//tensorflow/python/debug:debugger_cli_common_test                       FAILED in 4.9s
  /root/.cache/bazel/_bazel_root/86706540226bed5af3f7ba9c1699e357/execroot/org_tensorflow/bazel-out/k8-opt/testlogs/tensorflow/python/debug/debugger_cli_common_test/test.log
//tensorflow/python/kernel_tests:list_ops_test                           FAILED in 9.8s
  /root/.cache/bazel/_bazel_root/86706540226bed5af3f7ba9c1699e357/execroot/org_tensorflow/bazel-out/k8-opt/testlogs/tensorflow/python/kernel_tests/list_ops_test/test.log
//tensorflow/tools/api/tests:api_compatibility_test                      FAILED in 7.4s
  /root/.cache/bazel/_bazel_root/86706540226bed5af3f7ba9c1699e357/execroot/org_tensorflow/bazel-out/k8-opt/testlogs/tensorflow/tools/api/tests/api_compatibility_test/test.log
```

**Comment by whchung** [comment]
Please verify if they are regressions or newly introduced tests and modify white lists accordingly and log at confluence

**Comment by whchung** [comment]
@jeffdaily ping

**Comment by jeffdaily** [comment]
The test //tensorflow/python/kernel_tests:list_ops_test is failing.  I copied out a simple reproducer, replacing the asserts with print statements but leaving the asserts to show what the expected values had been.
```python
# pylint: disable=g-bad-name
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import numpy as np  # pylint: disable=unused-import

import tensorflow as tf
from tensorflow.python.eager import backprop
from tensorflow.python.framework import constant_op
from tensorflow.python.framework import dtypes
from tensorflow.python.framework import ops
from tensorflow.python.ops import list_ops

tf.enable_eager_execution()

with tf.device('/gpu:0'):
  with backprop.GradientTape() as tape:
    c0 = constant_op.constant([1.0, 2.0])
    tape.watch(c0)
    print("c0")
    print(c0)
    l = list_ops.tensor_list_scatter(
        c0, [1, 0], ops.convert_to_tensor([], dtype=dtypes.int32))
    t0 = list_ops.tensor_list_get_item(l, 0, element_dtype=dtypes.float32)
    print("t0")
    print(t0)
    t1 = list_ops.tensor_list_get_item(l, 1, element_dtype=dtypes.float32)
    print("t1")
    print(t1)
    #assert(t0 == 2.0)
    #assert(t1 == 1.0)
    loss = t0 * t0 + t1 * t1
  dt = tape.gradient(loss, c0)
  print("dt")
  print(dt)
  #assert(dt == [2., 4.])
```
If the device is /cpu:0, the result is correctly [2.,4.].  If the device is unset, the result is incorrectly [2.,1.].  If the device is /gpu:0, the result is incorrectly [2.,0.].

**Comment by whchung** [comment]
@jeffdaily thanks for the efforts :)

**Pull request merged**
