### PR TITLE
Renabling some unit-tests that were no_rocm's after the 200129 weekly sync

### PR DESCRIPTION
**Pull request by deven-amd**
see individual commit messages for details

### CODE REVIEW

**Comment by ROCm-Apps-Test** [comment]
Can one of the admins verify this patch?

**Comment by deven-amd** [comment]
the flaky test `//tensorflow/compiler/xla/tests:dynamic_ops_test_gpu` strikes again in `rocm-xla`

http://ml-ci.amd.com:21096/job/develop-upstream-unit-tests/job/tensorflow-upstream-unit-tests-rocm-xla/1116/console

**Comment by deven-amd** [comment]
jenkins : retest rocm-xla please

**Comment by deven-amd** [comment]
upstream PR https://github.com/tensorflow/tensorflow/pull/36698 filed for the rocm_solver fix.

upstream PR https://github.com/tensorflow/tensorflow/pull/36341 updated with the other commits

**Pull request merged**
