### PR TITLE
Develop upstream sync 230522

### PR DESCRIPTION
**Pull request by draganmladjenovic**

### CODE REVIEW

**Comment by draganmladjenovic** [comment]
retest Ubuntu-sanity please

**Comment by draganmladjenovic** [comment]
retest Ubuntu-GPU-single please

**Comment by i-chaochen** [comment]
Retest Ubuntu-GPU-single please

**Review by jayfurmanek — APPROVED** [review]
LGTM

**Comment by i-chaochen** [comment]
seems these two are failed at Ubuntu-GPU-single
```
//tensorflow/core/kernels/image:resize_ops_test_gpu
//tensorflow/python/kernel_tests/nn_ops:rnn_cell_test_gpu
```
but they are passed on gpu-pycpp.

@draganmladjenovic are they work ok in your local as well?

**Comment by draganmladjenovic** [comment]
> seems these two are failed at Ubuntu-GPU-single
> 
> ```
> //tensorflow/core/kernels/image:resize_ops_test_gpu
> //tensorflow/python/kernel_tests/nn_ops:rnn_cell_test_gpu
> ```
> 
> but they are passed on gpu-pycpp.
> 
> @draganmladjenovic are they work ok in your local as well?

The //tensorflow/core/kernels/image:resize_ops_test_gpu passes, but I'm only running that single tests, so I'm not sure if that is enough to reproduce the issue.
Second one failed at lininking with OOM. Which is odd. So I cannot reproduce it right now. **Update: It passes.**

Retest Ubuntu-GPU-single please

**Pull request merged**
