### PR TITLE
Develop upstream sync 230717

### PR DESCRIPTION
**Pull request by weihanmines**
Removed the API GetWindowedOutputSizeVerboseV2.

### CODE REVIEW

**Comment by weihanmines** [comment]
jenkins : retest Ubuntu-CPU please

**Comment by weihanmines** [comment]
CPU FAILURE: [31m[1mFAILED:[0m Build did NOT complete successfully
//tensorflow/compiler/xla/python/pjrt_ifrt:xla_sharding_serdes_test

**Comment by weihanmines** [comment]
Test output for //tensorflow/python/ops:nn_test_gpu:
Running test /home/jenkins/sharedspace/bazel-ci_build-cache/.cache/bazel/_bazel_jenkins/eab0d61a99b6696edb3d2aff87b585e8/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/python/ops/nn_test_gpu.runfiles/org_tensorflow/tensorflow/python/ops/nn_test_gpu  on GPU 0
2023-07-17 22:41:18.972500: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: SSE3 SSE4.1 SSE4.2 AVX AVX2 AVX512F FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
Running tests under Python 3.10.9: /home/jenkins/sharedspace/bazel-ci_build-cache/.cache/bazel/_bazel_jenkins/eab0d61a99b6696edb3d2aff87b585e8/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/python/ops/nn_test_gpu.runfiles/python_x86_64-unknown-linux-gnu/bin/python3
faulthandler.register(SIGTERM) failed AttributeError("module 'signal' has no attribute 'SIGTERM'"); ignoring.

**Comment by weihanmines** [comment]
Test output for //tensorflow/python/ops:nn_test_gpu:
Running test /home/jenkins/sharedspace/bazel-ci_build-cache/.cache/bazel/_bazel_jenkins/eab0d61a99b6696edb3d2aff87b585e8/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/python/ops/nn_test_gpu.runfiles/org_tensorflow/tensorflow/python/ops/nn_test_gpu  on GPU 0
2023-07-17 22:41:18.972500: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: SSE3 SSE4.1 SSE4.2 AVX AVX2 AVX512F FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
Running tests under Python 3.10.9: /home/jenkins/sharedspace/bazel-ci_build-cache/.cache/bazel/_bazel_jenkins/eab0d61a99b6696edb3d2aff87b585e8/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/python/ops/nn_test_gpu.runfiles/python_x86_64-unknown-linux-gnu/bin/python3
faulthandler.register(SIGTERM) failed AttributeError("module 'signal' has no attribute 'SIGTERM'"); ignoring.
FAIL: testDropout_generator_no_0.1 (__main__.DropoutTest)
DropoutTest.testDropout_generator_no_0.1
testDropout_generator_no_0.1('generator', functools.partial(<function general_dropout at 0x7f842dc80f70>, uniform_sampler=<function <lambda> at 0x7f8526d58f70>), 'no', 0.1)

Traceback (most recent call last):
  File "/home/jenkins/sharedspace/bazel-ci_build-cache/.cache/bazel/_bazel_jenkins/eab0d61a99b6696edb3d2aff87b585e8/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/python/ops/nn_test_gpu.runfiles/absl_py/absl/testing/parameterized.py", line 316, in bound_param_test
    return test_method(self, *testcase_params)
  File "/home/jenkins/sharedspace/bazel-ci_build-cache/.cache/bazel/_bazel_jenkins/eab0d61a99b6696edb3d2aff87b585e8/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/python/ops/nn_test_gpu.runfiles/org_tensorflow/tensorflow/python/ops/nn_test.py", line 372, in testDropout
    self.assertLess(rel_error, 0.15)
AssertionError: 0.16666666666666666 not less than 0.15

----------------------------------------------------------------------
Ran 284 tests in 97.165s

FAILED (failures=1, skipped=38)

**Comment by weihanmines** [comment]
//tensorflow/compiler/xla/service/gpu/tests:fused_slice_amdgcn.hlo.test:

**Comment by weihanmines** [comment]
//tensorflow/compiler/xla/service/gpu/tests:dynamic_update_slice_inplace_amdgcn.hlo.test

**Comment by weihanmines** [comment]
last commit fixes the fail unit test on CPU.

**Comment by i-chaochen** [comment]
2 failed unit tests will be fixed in next weekly-sync due to this PR https://github.com/openxla/xla/pull/4311/files

//tensorflow/compiler/xla/service/gpu/tests:dynamic_update_slice_inplace_amdgcn.hlo.test  //tensorflow/compiler/xla/service/gpu/tests:fused_slice_amdgcn.hlo.test

**Comment by weihanmines** [comment]
> 

Thanks!

**Comment by weihanmines** [comment]
//tensorflow/compiler/tests:unary_ops_test_gpu                           FAILED 
disabled for now

**Review by i-chaochen — APPROVED** [review]

**Comment by i-chaochen** [comment]
Also, we will enable the graph flag at next weekly-sync due to this PR is going to merge https://github.com/openxla/xla/pull/3960

**Pull request merged**
