### PR TITLE
Consolidated GPU versioning scheme

### PR DESCRIPTION
**Pull request by whchung**
Different methods are used in GPU common runtime, StreamExecutor, and XLA to
track GPU hardware versions. To support upcoming ROCm SteramExecutor and AMDGPU
XLA, it's now consolidated to DeviceVersion in StreamExecutor.

Adopt the scheme for both CUDA and ROCm platforms.

### CODE REVIEW

**Comment by whchung** [comment]
@parallelo This PR would be better checked by an external NV CI node as it affects both CUDA and ROCm execution path and there are non-trivial changes to bazel scripts on CUDA side.

**Comment by whchung** [comment]
jenkins: retest this please

**Comment by whchung** [comment]
The test on ROCm ends up with 1 failure, but it seems to be a flaky test. Retesting again.

@parallelo also it'd be good if we can test it on an NV node when available.

**Comment by whchung** [comment]
the test is a success on ROCm but I'll keep it open until we can test it on an NV node.

also I'll need to rebase

**Comment by parallelo** [comment]
jenkins: retest this please

**Comment by parallelo** [comment]
jenkins: retest this please

**Comment by parallelo** [comment]
jenkins: retest this please

**Comment by parallelo** [comment]
FYI - looking at the separate ROCm and CUDA target logs, `configure.py` still needs some further tweaks.

**Comment by parallelo** [comment]
Jenkins:  retest this please

Testing dual-target builds with ROCm (local) and CUDA (aws).

**Comment by whchung** [comment]
will do a different implementation instead

**Pull request closed without merging**
