### PR TITLE
Hipsparse add op

### PR DESCRIPTION
**Pull request by stevenireeves**
Adding hipsparseXcsrgeam to wrapper and including it in the add op.

### CODE REVIEW

**Comment by stevenireeves** [comment]
@deven-amd I'm actually getting a similar error to the points in https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/pull/1327

This time with the add related function. 

_pywrap_tensorflow_internal.so: undefined symbol: _ZN10tensorflow9GpuSparse20CsrgeamBufferSizeExtIfEENS_6StatusEiiPKT_PviS5_PKiS8_S5_S6_iS5_S8_S8_S6_PS3_PiSA_Pm

It appears that I'm missing something critical, do you have any ideas? I'll keep digging.

**Comment by deven-amd** [comment]
@stevenireeves which unit-test do I need to run reproduce the linker error above?

**Comment by deven-amd** [comment]
@stevenireeves , trace through the implementation of  `CSRSparseMatrixAdd<GPUDevice, T>` in `./tensorflow/core/kernels/sparse/add_op.cc` and you will see the reason for the link error.  We need to add ROCm support (in `rocm_sparse.cc` ) for the routine that the linker is complaining about (and others too)

**Comment by stevenireeves** [comment]
@deven-amd it was //tensorflow/python/kernel_tests/linalg/sparse:csr_sparse_matrix_test_gpu

I'll take a look into rocm_sparse.cc. Thanks for the pointer.

**Comment by stevenireeves** [comment]
jenkins : retest this please

**Review by deven-amd — APPROVED** [review]

**Comment by stevenireeves** [comment]
jenkins : retest this please

**Pull request merged**
