### PR TITLE
Re-enabling vectorization/packet support for certain cwise ops (on the ROCm platform)

### PR DESCRIPTION
**Pull request by deven-amd**
Doing so also requires making a slight modification to the Eigen codebase, which is included here in the eigen patch file. Once CI runs successfully on this PR, I will go ahead and file a PR on eigen to upstream the change in the patch.

/cc @whchung

### CODE REVIEW

**Comment by jerryyin** [comment]
Out of curiosity, what was it in Eigen to fail that cause us to disable the packet math?

BTW, judging from the name, does packet math pack a number of cwise ops to be calculated together for higher efficiency?

**Comment by deven-amd** [comment]
@jerryyin 
Eigen code to special case `pzero` template implementation was enabled only for `device` code prior to this change, and that was causing the `host` code compile to fail. 
That is because without the specialized version, 
* the default version in `GenericPacketMath.h` gets picked up, 
  * which in turn calls `pxor` on the `float4` type, 
    * which will cause `hipcc` to error out

enabling packet math enables leveraging code that uses "packet types" (8 fp16s or 4 fp32s or 2 fp64s). using those types leads to optimized codegen.

**Comment by deven-amd** [comment]
hmm, there is only one failure in `rocm`, 

`//tensorflow/python:convert_to_constants_test ` 

and that passes for me locally on a consistent basis...maybe just a flaky test?

will request jenkins to retest `rocm`.  
If retest passes, we can take this PR
If same test fails again, will add a `no_rocm` tag on it

**Comment by deven-amd** [comment]
link to failing `rocm` log : http://ml-ci.amd.com:21096/job/develop-upstream-unit-tests/job/tensorflow-upstream-unit-tests/1534/console

**Comment by deven-amd** [comment]
jenkins : retest rocm please

**Comment by deven-amd** [comment]
interesting.

Requesting jenkins to retest `rocm` 
* also seems to trigger the `rocm-cpp` build 
* but does not trigger the `rocm-xla` build. 

@parallelo any thoughts? 
(this is not important...it can wait, if need be)

**Comment by whchung** [comment]
@deven-amd on my experimental branch to enable PacketAccess, I had to disable quite a few operators due to compile errors I haven't studied yet: DivNoNan, MulNoNan, InvGrad, ReciprocalGrad, RsqrtGrad, SqrtGrad, Xdivy. Wonder has these been addressed in this PR?

**Comment by deven-amd** [comment]
@whchung 

Yes those compile errors have been addressed. The root cause for all those compile errors turned out to be the change in the second commit in this PR :)

**Comment by deven-amd** [comment]
btw, the change in the second commit (i.e. the eigen patch file update) has been upstreamed to the Eigen repo already.

**Pull request merged**
