### PR TITLE
Fix for SWDEV-203700

### PR DESCRIPTION
**Pull request by mshivama**
In hip-clang environment, ensure that hip header is included wherever it is required to avoid surprise build errors.

### CODE REVIEW

**Comment by ROCm-Apps-Test** [comment]
Can one of the admins verify this patch?

**Comment by ROCm-Apps-Test** [comment]
Can one of the admins verify this patch?

**Comment by ROCm-Apps-Test** [comment]
Can one of the admins verify this patch?

**Comment by ROCm-Apps-Test** [comment]
Can one of the admins verify this patch?

**Comment by mshivama** [comment]
@whchung 

Could you please review this patch?

**Comment by whchung** [comment]
jenkins: ok to test

**Comment by whchung** [comment]
@mshivama Now since most of our work has been upstreamed to TensorFlow mainline. It's advised to submit this PR directly to TensorFlow mainline too and I can also approve there.

**Comment by mshivama** [comment]
@whchung  Sure, will submit this PR to TensorFlow mainline too

**Comment by whchung** [comment]
jenkins: retest rocm-v2 please.

**Comment by whchung** [comment]
jenkins: retest rocm-xla please.

**Pull request merged**
