### PR TITLE
Update TF/ROCM version docs

### PR DESCRIPTION
**Pull request by jayfurmanek**

### CODE REVIEW

**Review by rsanthanam-amd — APPROVED** [review]

**Comment by jayfurmanek** [comment]
retest Ubuntu-GPU-single please

**Comment by jayfurmanek** [comment]
retest Ubuntu-GPU-single please

**Comment by jayfurmanek** [comment]
retest Ubuntu-GPU-multi please

**Comment by jayfurmanek** [comment]
retest Ubuntu-GPU-single please

**Comment by jayfurmanek** [comment]
retest Ubuntu-GPU-single please

**Pull request merged**
