### PR TITLE
Develop upstream sync 191230

### PR DESCRIPTION
**Pull request by deven-amd**

### CODE REVIEW

**Comment by deven-amd** [comment]
all 4 failures in the `rocm-xla` run passed locally....will retest `rocm-xla` once. If the second run also fails, then will add `no_rocm` tag to the failing tests

link to failing run:
http://ml-ci.amd.com:21096/job/develop-upstream-unit-tests/job/tensorflow-upstream-unit-tests-rocm-xla/950/

**Comment by deven-amd** [comment]
jenkins: retest rocm-xla please

**Comment by ROCm-Apps-Test** [comment]
Can one of the admins verify this patch?

**Comment by deven-amd** [comment]
one failure in `rocm` .... yet another case of the test passing locally but failing spuriously on the CI node :(

waiting for `rocm-xla` to finish, so that I can push out all the required `no_rocm` tags in one commit

**Pull request merged**
