### PR TITLE
remove no_rocm tag from most distribute tests

### PR DESCRIPTION
**Pull request by jeffdaily**
Now that RCCL is integrated, re-try distribute tests.

### CODE REVIEW

**Comment by deven-amd** [comment]
@jeffdaily can I request you to file an upstream PR for the same?

Please 
 * create a branch from the latest commit in the upstream repo master branch, 
 * push out your changes to that branch (from PR #541 and this one)
 * verify `--config=rocm` build successfully and all the tests which no longer have the `no_rocm` tag, pass.
 * file the PR

thanks

**Comment by deven-amd** [comment]
The `no_rocm` tag was not removed for this test (https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/blob/develop-upstream/tensorflow/python/distribute/BUILD#L176 )

is that by design or accident?

**Comment by jeffdaily** [comment]
By design -- the `distribute_lib_test` is still failing on rocm.  I thought it would be best to re-enable the ones in this PR while I continue to triage the last failing test.

**Comment by deven-amd** [comment]
> By design -- the `distribute_lib_test` is still failing on rocm. I thought it would be best to re-enable the ones in this PR while I continue to triage the last failing test.

In that case, please hold-off on filing the upstream PR until after we fix this. thanks.

**Pull request merged**
