### PR TITLE
TF integration of rocTracer

### PR DESCRIPTION
**Pull request by whchung**
This PR supersedes #238. A new configure-time option `TF_NEED_ROCM_GPU_TRACER` can be used to enable/disable ROCm GPU Tracer. By default it's disabled. Once ROCm GPU Tracer is officially in ROCm releases such option can be turned to on by default.

### CODE REVIEW

**Comment by whchung** [comment]
@eshcherb, per comment from @parallelo , could you help revise the Dockerfile so it uses stock HIP / HCC, and move roctracer-specific patches into a separate Dockerfile? We can setup additional Jenkins jobs if necessary.

**Comment by eshcherb** [comment]
Yes, I will created specific Dockerfile.

________________________________

**Comment by whchung** [comment]
@eshcherb I've added you as contributor of the project, so you should be able to directly push commits to `escherb-roctracer-hip-frontend-181110` branch used by this PR.

**Comment by whchung** [comment]
@parallelo could you change the link to CI logs from `http://205.234.28.200:21096/...` to `http://ml-ci.amd.com:21096/...` ?

**Comment by whchung** [comment]
@parallelo I've added one commit so `Dockerfile.rocm` goes back to its current shape. Please help review this PR.

@eshcherb I'd like to get this PR merged ASAP, you can submit the Dockerfile for roctracer in a separate PR.

**Comment by parallelo** [comment]
LGTM, although still trying to visualize the mods to the logic in `tensorflow/python/client/timeline.py`.  

I'll plan to test it out today.

**Comment by whchung** [comment]
@parallelo just resolved merge conflicts with the latest tip of `develop-upstream`.

**Comment by whchung** [comment]
@parallelo The failing tests on CUDA path and ROCm path should have nothing to do with the PR. They seem to be flaky (passes on local runs but fails on CI).

**Comment by parallelo** [comment]
Yes, I noticed that too.  I'm currently trying to reproduce it locally.

**Comment by parallelo** [comment]
FYI - need to set this path correctly in `Dockerfile.rocm-roctracer`:  
`-DPROF_API_HEADER_PATH=$HOME/roctracer/inc/ext`
```
diff --git a/tensorflow/tools/ci_build/Dockerfile.rocm-roctracer b/tensorflow/tools/ci_build/Dockerfile.rocm-roctracer
index 080af98..f6bff4a 100644
--- a/tensorflow/tools/ci_build/Dockerfile.rocm-roctracer
+++ b/tensorflow/tools/ci_build/Dockerfile.rocm-roctracer
@@ -84,9 +84,9 @@ RUN cd $HOME && git clone -b amd-master https://github.com/ROCmSoftwarePlatform/
 RUN cd $HOME && git clone -b roctracer-hip-frontend-181113 --recursive https://github.com/eshcherb/hcc.git
 RUN cd $HOME && git clone -b roctracer-hip-frontend-181113 https://github.com/eshcherb/HIP.git
 # build HCC
-RUN cd $HOME/hcc && mkdir build && cd build && cmake -DUSE_PROF_API=1 -DPROF_API_HEADER_PATH=$HOME/roctracer/inc/roctracer .. && sudo make package -j$(nproc) && sudo dpkg -i *.deb
+RUN cd $HOME/hcc && mkdir build && cd build && cmake -DUSE_PROF_API=1 -DPROF_API_HEADER_PATH=$HOME/roctracer/inc/ext .. && sudo make package -j$(nproc) && sudo dpkg -i *.deb
 # build HIP
-RUN cd $HOME/HIP && mkdir build && cd build && cmake -DUSE_PROF_API=1 -DPROF_API_HEADER_PATH=$HOME/roctracer/inc/roctracer .. && sudo make package -j$(nproc) && sudo dpkg -i *.deb
+RUN cd $HOME/HIP && mkdir build && cd build && cmake -DUSE_PROF_API=1 -DPROF_API_HEADER_PATH=$HOME/roctracer/inc/ext .. && sudo make package -j$(nproc) && sudo dpkg -i *.deb
 # build rocTracer
 RUN cd $HOME/roctracer && mkdir build && cd build && HCC_HOME=/opt/rocm/hcc HIP_PATH=/opt/rocm/hip CMAKE_PREFIX_PATH=/opt/rocm/lib:/opt/rocm/include/hsa cmake -DCMAKE_INSTALL_PREFIX=/opt/rocm .. && make package -j$(nproc) && sudo dpkg -i *.deb
```

Now working on getting through the rest of the build.

**Comment by parallelo** [comment]
Also had to remove `sudo` from the `Dockerfile.rocm-roctracer`.  It is still building on my machine.

For reference, you can (attempt to) build a rocTracer-enabled WHL file locally using something like this:  
```
export CI_DOCKER_EXTRA_PARAMS="-e CI_BUILD_PYTHON=python3.5 -e PIP_TEST_ROOT=pip35_test -e NO_TEST_ON_INSTALL=1 -e NO_TEST_USER_OPS=1 -e NO_TEST_TFDBG_BINARIES=1"
tensorflow/tools/ci_build/ci_build.sh rocm-roctracer tensorflow/tools/ci_build/builds/pip.sh rocm -c opt --config=rocm 2>&1 | tee ci_build.log
```

Here are my local mods so far:  
```
diff --git a/tensorflow/tools/ci_build/Dockerfile.rocm-roctracer b/tensorflow/tools/ci_build/Dockerfile.rocm-roctracer
index 080af98..2e564a0 100644
--- a/tensorflow/tools/ci_build/Dockerfile.rocm-roctracer
+++ b/tensorflow/tools/ci_build/Dockerfile.rocm-roctracer
@@ -84,11 +84,11 @@ RUN cd $HOME && git clone -b amd-master https://github.com/ROCmSoftwarePlatform/
 RUN cd $HOME && git clone -b roctracer-hip-frontend-181113 --recursive https://github.com/eshcherb/hcc.git
 RUN cd $HOME && git clone -b roctracer-hip-frontend-181113 https://github.com/eshcherb/HIP.git
 # build HCC
-RUN cd $HOME/hcc && mkdir build && cd build && cmake -DUSE_PROF_API=1 -DPROF_API_HEADER_PATH=$HOME/roctracer/inc/roctracer .. && sudo make package -j$(nproc) && sudo dpkg -i *.deb
+RUN cd $HOME/hcc && mkdir build && cd build && cmake -DUSE_PROF_API=1 -DPROF_API_HEADER_PATH=$HOME/roctracer/inc/ext .. && make package -j$(nproc) && dpkg -i *.deb
 # build HIP
-RUN cd $HOME/HIP && mkdir build && cd build && cmake -DUSE_PROF_API=1 -DPROF_API_HEADER_PATH=$HOME/roctracer/inc/roctracer .. && sudo make package -j$(nproc) && sudo dpkg -i *.deb
+RUN cd $HOME/HIP && mkdir build && cd build && cmake -DUSE_PROF_API=1 -DPROF_API_HEADER_PATH=$HOME/roctracer/inc/ext .. && make package -j$(nproc) && dpkg -i *.deb
 # build rocTracer
-RUN cd $HOME/roctracer && mkdir build && cd build && HCC_HOME=/opt/rocm/hcc HIP_PATH=/opt/rocm/hip CMAKE_PREFIX_PATH=/opt/rocm/lib:/opt/rocm/include/hsa cmake -DCMAKE_INSTALL_PREFIX=/opt/rocm .. && make package -j$(nproc) && sudo dpkg -i *.deb
+RUN cd $HOME/roctracer && mkdir build && cd build && HCC_HOME=/opt/rocm/hcc HIP_PATH=/opt/rocm/hip CMAKE_PREFIX_PATH=/opt/rocm/lib:/opt/rocm/include/hsa cmake -DCMAKE_INSTALL_PREFIX=/opt/rocm .. && make package -j$(nproc) && dpkg -i *.deb
 
 # Add target file to help determine which device(s) to build for
 RUN bash -c 'echo -e "gfx803\ngfx900\ngfx906" >> /opt/rocm/bin/target.lst'
```

**Comment by parallelo** [comment]
You guys familiar with this type of error?  Still trying to understand why the `amp*.h` links are bad.  
```
[5,870 / 10,574] Compiling tensorflow/contrib/decision_trees/proto/generic_tree_model.pb.cc; 7s local ... (63 actions running)
ERROR: /home/jeffp/tensorflow-upstream.parallelo/bazel-ci_build-cache/.cache/bazel/_bazel_jeffp/eab0d61a99b6696edb3d2aff87b585e8/external/local_config_rocm/rocm/BUILD:119:1: declared output 'external/local_config_rocm/rocm/rocm/include/hcc/amp.h' is a dangling symbolic link
ERROR: /home/jeffp/tensorflow-upstream.parallelo/bazel-ci_build-cache/.cache/bazel/_bazel_jeffp/eab0d61a99b6696edb3d2aff87b585e8/external/local_config_rocm/rocm/BUILD:119:1: declared output 'external/local_config_rocm/rocm/rocm/include/hcc/amp_short_vectors.h' is a dangling symbolic link
ERROR: /home/jeffp/tensorflow-upstream.parallelo/bazel-ci_build-cache/.cache/bazel/_bazel_jeffp/eab0d61a99b6696edb3d2aff87b585e8/external/local_config_rocm/rocm/BUILD:119:1: declared output 'external/local_config_rocm/rocm/rocm/include/hcc/amp_math.h' is a dangling symbolic link
ERROR: /home/jeffp/tensorflow-upstream.parallelo/bazel-ci_build-cache/.cache/bazel/_bazel_jeffp/eab0d61a99b6696edb3d2aff87b585e8/external/local_config_rocm/rocm/BUILD:119:1: not all outputs were created or valid
Target //tensorflow/tools/pip_package:build_pip_package failed to build
```

**Comment by parallelo** [comment]
@whchung - Looks like this specific fork of HCC does not even install those `hsa/amp*.h` files.  

I went into the container and could not find them where TF expects them:  
```
root@5854854acf9d:/# ls /opt/rocm/include/hcc/amd*.h  
/opt/rocm/include/hcc/amd_hsa_common.h  /opt/rocm/include/hcc/amd_hsa_elf.h  /opt/rocm/include/hcc/amd_hsa_kernel_code.h  /opt/rocm/include/hcc/amd_hsa_queue.h  /opt/rocm/include/hcc/amd_hsa_signal.h
```

**Comment by parallelo** [comment]
Good idea.  I bet the `ci_build`-produced container is using a cached layer with an "older" version of HCC, and then bazel's cache is getting confused.  Just did a `docker prune -a` and kicked off another build.

**Comment by whchung** [comment]
@parallelo a gentle ping on this PR?

**Comment by parallelo** [comment]
Still working on this..  fixed a bunch of build errors.  Now hitting hundreds of strange iHipException failing unit tests that end up looking like numpy-related errors.

**Comment by whchung** [comment]
@eshcherb to my understanding @bensander asked for a demonstration of `roctracer` next week.

wondering do we still need this PR? If it's needed would you help rebase it?

**Comment by whchung** [comment]
closing this PR after discussing with @eshcherb . @eshcherb would file a new PR.

**Pull request closed without merging**
