### PR TITLE
Add new runtime image for TF

### PR DESCRIPTION
**Pull request by jayfurmanek**
https://github.com/ROCmSoftwarePlatform/frameworks-internal/issues/3541

### CODE REVIEW

**Comment by jayfurmanek** [comment]
retest Ubuntu-GPU-multi please

**Comment by jayfurmanek** [comment]
retest Ubuntu-CPU please

**Comment by jayfurmanek** [comment]
retest Ubuntu-CPU please
retest Ubuntu-GPU-multi please
retest Ubuntu-GPU-single please

**Comment by jayfurmanek** [comment]
retest Ubuntu-CPU please
retest Ubuntu-GPU-multi please
retest Ubuntu-GPU-single please

**Review by rahulbatra85 — APPROVED** [review]

**Pull request merged**
