### PR TITLE
Merging updates from Tensorflow upstream master - 07/09/2018

### PR DESCRIPTION
**Pull request by deven-amd**

### CODE REVIEW

**Comment by whchung** [comment]
@deven-amd please help review those failures and update whitelist if necessary.

**Comment by deven-amd** [comment]
@whchung 

only two tests are failing.
1. //tensorflow/python/estimator:dnn_linear_combined_test
2. //tensorflow/python/ops/parallel_for:control_ops_test

I cannot reproduce the failure for #1 locally (3 consecutuive passes for me)

Failure #2 is reproducible (crash with stack dump while running) but currently do not know the cause of of the failure/crash.

**Comment by whchung** [comment]
a) let's put them into the whitelist.
b) please also help update the spreadsheet.
c) are they newly introduced tests? or regressions?

**Comment by deven-amd** [comment]
let me put the two tests on the whitelist and update the PR
will update the spreadsheet as well

The dnn_linear_combined_test is a regression (though I cannot reproduce the failure locally) ... it started passing recently (either due to disabling sharding or the "FloorDiv on GPU" fix)

The parallel_for/control_ops_test is a new test!

**Pull request merged**
