### PR TITLE
Develop upstream sync 210111

### PR DESCRIPTION
**Pull request by stevenireeves**
Daily upstream sync.

### CODE REVIEW

**Comment by deven-amd** [comment]
@stevenireeves  for the lone failures in the `Ubuntu-CPU` and `Ubuntu-GPU-single` CI jobs, you can add a `no_rocm` tag on those tests to get the sync done, and then come back to root-cause and fix those independent of the fix

**Comment by deven-amd** [comment]
The failure in `//tensorflow/compiler/xla/service/gpu/tests:mlir_sorting_test` seems to have been introduced by upstream changes (I see it in the `upstream/master` branch as well)

Filed Issue to track this failure - https://github.com/ROCmSoftwarePlatform/tensorflow-internal/issues/100

**Comment by stevenireeves** [comment]
@deven-amd Should I wait to merge then?

**Comment by deven-amd** [comment]
> Should I wait to merge then?

you mean to finish the merge...no.

just push out another commit which adds the `no_rocm` tag on the two failing tests. Hopefully all CI tests will pass with that change. Once that happens, proceed with the remaining steps for the weekly merge.

**Pull request merged**
