### PR TITLE
[ROCm:XLA] Adding XLA support to TF-2.0

### PR DESCRIPTION
**Pull request by jerryyin**
I manually serialized and cherry picked all commit in the following PRs:

- #30363
- #30374
- #30377
- #30379
- #30382
- #30660
- #30936
- #31146
- #31489
- #31560
- #31491
- #30381
- #31908

------

- I am currently validating the correctness of conflict resolution by doing local test
- The next step is to pull in `gpu_conv_algorithm_picker` from `develop-upstream` branch
- When all of this is done, I highly recommend to run full regression before and after this PR to ensure the correctness of the manual conflict resolution

### CODE REVIEW

**Comment by jerryyin** [comment]
@whchung I have cherry pick all our upstream PR's commit and make sure that `pip_package` can be generated. Can you double check that XLA support is actually enabled?

My suspicion is that I'm missing something, as I am compiling the `//tensorflow/compiler/xla/tests:convolution_test` target, only cpu backend version of the test is generated. I used to be able to get a gpu version of the test as well.

**Comment by jerryyin** [comment]
As an update, after last commit fixing XLA backend, I'm able to get amdgpu backend working in unit test. Right now I'm debugging segmentation fault in running `ConcatTest.Concat_1x1024_With_1x1024_InDim0`.

**Comment by jerryyin** [comment]
Up to now, a huge number of tests are failing with 
`2019-09-07 00:08:17.784923: F tensorflow/compiler/tf2xla/xla_op_registry.cc:339] Check failed: it != registry.backends_.end() Unknown backend XLA_GPU_JIT`

Will start with debugging `tensorflow/python/kernel_tests:conv_ops_test_gpu`

**Comment by jerryyin** [comment]
Current status: TMP-tensorflow-upstream-rel2.0-nightly-debug [task#3](http://ml-ci.amd.com:21096/job/TMP-tensorflow-upstream-rel2.0-nightly-debug/3/) is passing, kicking off a new build to include the latest commit in enabling `GpuConvAlgorithmPicker`.

@sunway513 Since all regression are passing for this CI job. Could you help with additional validation of this branch? I'd suggest we run the full set and go with the divide and conquer approach with any additional failures.

**Comment by sunway513** [comment]
Thank you @jerryyin , and yes I'll run additional sanity checks on this branch before merging to the 2.0-rocm-enahnced-rc0 branch. 
Please feel free to remove the "Do Not Merge" note if it's ready on your end.

**Comment by jerryyin** [comment]
@sunway513 Honestly I don't have enough confidence to have this branch merged, thanks for kicking off CI[#6](http://ml-ci.amd.com:21096/job/TMP-tensorflow-upstream-rel2.0-nightly-debug/6/console) for me. I realized that there is a number of failures in this task, thus also kick off a CI run for the `r2.0-rocm-enhanced-rc0` branch as CI[#7](http://ml-ci.amd.com:21096/job/TMP-tensorflow-upstream-rel2.0-nightly-debug/7/). Hopefully by tomorrow we'd know if the regressions are caused by XLA related code updates.

**Comment by sunway513** [comment]
@jerryyin , the failures for run_py3_core.sh scripts in run #6 doesn't seem like due to the changes in this PR, let's see how #7 goes.
I don't have full confidence of 100% passing rates for `run_py3_core.sh` for our upstream branches. Let's discuss the mitigation plan tomorrow in teams.

**Comment by jerryyin** [comment]
@sunway513  That's right, CI task `#7` is doing pretty well. Taking a double look at `#6`, a majority of failures are due to tests not disabled, that should have been disabled. For example, `//tensorflow/examples/speech_commands` have 6 failures, but we have disabled them from `develop-upstream`.

**Comment by sunway513** [comment]
@jerryyin  thank you for the contribution, I'm going to merge this PR.

**Pull request merged**
