### PR TITLE
Develop upstream sync 200805

### PR DESCRIPTION
**Pull request by jerryyin**
### Conflict file list

 * tensorflow/compiler/xla/service/gpu/llvm_gpu_backend/gpu_backend_lib.cc
 * tensorflow/core/kernels/BUILD
 * tensorflow/core/kernels/reduction_gpu_kernels.cu.h
 * tensorflow/python/eager/def_function_xla_jit_test.py
 * tensorflow/python/kernel_tests/BUILD
 * tensorflow/python/kernel_tests/array_ops/batch_gather_op_test.py

### CODE REVIEW

**Comment by ROCm-Apps-Test** [comment]
Can one of the admins verify this patch?

**Comment by jerryyin** [comment]
jenkins retest rocm
jenkins retest rocm-xla
jenkins retest rocm-cpp

**Comment by jerryyin** [comment]
jenkins retest rocm please

**Comment by jerryyin** [comment]
jenkins retest rocm-xla please

**Comment by jerryyin** [comment]
jenkins retest rocm-cpp please

**Comment by jerryyin** [comment]
jenkins retest rocm-cpp please

**Pull request merged**
