### PR TITLE
Fix GPU_LAUNCH_KERNEL for hip-clang

### PR DESCRIPTION
**Pull request by yxsamliu**

### CODE REVIEW

**Comment by ROCm-Apps-Test** [comment]
Can one of the admins verify this patch?

**Comment by ROCm-Apps-Test** [comment]
Can one of the admins verify this patch?

**Comment by ROCm-Apps-Test** [comment]
Can one of the admins verify this patch?

**Comment by ROCm-Apps-Test** [comment]
Can one of the admins verify this patch?

**Comment by whchung** [comment]
@yxsamliu to cope with changes upstream, we are in the processing of getting #439 merged, which abolishes `GPU_LAUNCH_KERNEL` and consolidate on a new syntax congruent with upstream `TF_CHECK_OK(GpuLaunchKernel(`.

**Comment by whchung** [comment]
... so instead of continue changing call sites of `GPU_LAUNCH_KERNEL`, could you check if #439 works with hip-clang?

**Comment by yxsamliu** [comment]
PR#439 works for hip-clang. So drop this PR. We need PR#439 merged ASAP since it is blocking hip-clang CI. Thanks.

**Pull request closed without merging**
