### PR TITLE
[DO NOT MERGE] Porting ROCm Dropout support to master-rocm-enhanced

### PR DESCRIPTION
**Pull request by jerryyin**
This PR is to port the ROCm Dropout support from the `develop-upstream` to the `master-rocm-enhanced` branch.

We need to have a few pre-reqs in place before we can take this PR
- [ ] identidy a commit on the `upstream/master` branch for which all ROCm CI jobs (`rocm`, `rocm-cpp`, `rocm-xla`)  are passing, aka the ROCm CI qualified commit
- [ ] rebase the `master-rocm-enhanced` branch to the ROCm CI qualified commit
- [ ] Setup ROCm CI jobs to run on PRs filed on the `master-rocm-enhanced` branch

The purpose of filing this PR now is to assist with filtering out the changes in this PR, from the set of diffs in `develop-upstream` that we need to triage before we abandon that branch 

/cc @deven-amd

### CODE REVIEW

**Comment by deven-amd** [comment]
thank you @jerryyin 

let me cherry-pick this PR to `master-with-triaged-diffs`

**Comment by jerryyin** [comment]
I and @deven-amd synced just now and leave a comment here in case it get forgotten: This PR only serves for diff purpose and should never be merged. I needs to later be rebased to `master-rocm-enhanced` and retested in CI before it can be closed.

**Comment by ROCm-Apps-Test** [comment]
Can one of the admins verify this patch?

**Comment by deven-amd** [comment]
@jerryyin , will rebase this branch shortly to remove merge-conflicts.  m in the process of updating the `master-with-triaged-diffs` branch, and running into merge conflicts when I pull in this PR

**Comment by deven-amd** [comment]
closing out this PR since dropout functionality has been upstreamed, and this PR is no longer needed

**Pull request closed without merging**
