### PR TITLE
Hliao/master/fix hip clang build

### PR DESCRIPTION
**Pull request by darkbuck**
Fix TF build due to new version of LLVM/Clang

### CODE REVIEW

**Comment by ROCm-Apps-Test** [comment]
Can one of the admins verify this patch?

**Comment by ROCm-Apps-Test** [comment]
Can one of the admins verify this patch?

**Comment by ROCm-Apps-Test** [comment]
Can one of the admins verify this patch?

**Comment by ROCm-Apps-Test** [comment]
Can one of the admins verify this patch?

**Comment by ROCm-Apps-Test** [comment]
Can one of the admins verify this patch?

**Comment by ROCm-Apps-Test** [comment]
Can one of the admins verify this patch?

**Comment by deven-amd** [comment]
@darkbuck 

please put your change in in branch based on `develop-upstream` branch (of this repo)  and then file a PR to merge that branch onto `develop-upstream`.  This will trigger the ROCm CI to run on just your change. 

Once the ROCm CI runs come back clean, you can proceed with the upstream PR. In this case, you have already filed the upstream PR, so filing the PR here is just to make sure that your change does not cause any unexpected regressions.

`develop-upstream` branch gets synced with the `upstream/master` branch on a weekly basis, so once your upstream PR is merged, that change will automatically show up in `develop-upstream` a week later.

Please close out this PR, and file another one (based on the `develop-upstream` branch)

**Comment by darkbuck** [comment]
@googlebot I signed it!

**Pull request closed without merging**
