### PR TITLE
[r2.4-rocm-enhanced] Add ROCm 5.1.0

### PR DESCRIPTION
**Pull request by jayfurmanek**
Update TF2.4 to build with ROCm 5.1.0 for newer hardware support.
Note: This does not add new hardware support for XLA. Newer LLVM is needed for that, which this does not include.

### CODE REVIEW

**Comment by rocm-mici** [comment]
Can one of the admins verify this patch?

**Comment by rocm-mici** [comment]
Can one of the admins verify this patch?

**Comment by rocm-mici** [comment]
Can one of the admins verify this patch?

**Comment by rocm-mici** [comment]
Can one of the admins verify this patch?

**Comment by okakarpa** [comment]
retest

**Comment by jayfurmanek** [comment]
retest ubuntu-gpu-multi

**Comment by jayfurmanek** [comment]
retest Ubuntu-gpu-multi please

**Comment by jayfurmanek** [comment]
https://github.com/ROCmSoftwarePlatform/frameworks-internal/issues/1795

**Comment by rahulbatra85** [comment]
retest

**Comment by rahulbatra85** [comment]
retest Ubuntu-gpu-multi please

**Comment by okakarpa** [comment]
retest

**Comment by rahulbatra85** [comment]
Tests disabled as part of this PR
https://confluence.amd.com/display/~rahbatra/TF2.4+CI

**Comment by okakarpa** [comment]
retest

**Comment by okakarpa** [comment]
retest

**Comment by okakarpa** [comment]
retest Ubuntu-gpu-multi please

**Comment by okakarpa** [comment]
retest-gpu-single

**Comment by rahulbatra85** [comment]
retest Ubuntu-gpu-single please

**Pull request merged**
