### PR TITLE
Develop upstream sync 230213

### PR DESCRIPTION
**Pull request by jayfurmanek**
https://github.com/ROCmSoftwarePlatform/frameworks-internal/issues/3667

Triton-based matmul have been added:
- https://github.com/tensorflow/tensorflow/commit/f158f8824540d00e7addd85decc27aa2e3170130#diff-10e7b23ad8d7400d5a23bc499fa11b06bbac4271975b009930a68a3c124fa1f7

This doesn't work yet on AMD GPUs so the tests are disabled:
- https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/pull/1992/commits/167e177e390864c9c675cb29dba07f34b1b9a3e6
- https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/pull/1992/commits/65bb1c7d147bb3a6ddb8932dfb708219c1d83f74

There was also a ifdef needed around a IsSupported query in gpu_compiler.cc to avoid kDot/triton for AMD:
- https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/pull/1992/commits/a13805408f72835bc7482e5429455e6b7c9c7519

Note the Event Manager was rewritten in this update as well:
- https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/commit/3a065e5af3d79ce41724d4918c2d7bf9af484600

### CODE REVIEW

**Comment by jayfurmanek** [comment]
retest Ubuntu-GPU-multi please

**Comment by jayfurmanek** [comment]
retest Ubuntu-GPU-multi please
retest cpu-non-pip please

**Comment by jayfurmanek** [comment]
retest cpu-non-pip please

**Comment by jayfurmanek** [comment]
retest cpu-non-pip please

**Comment by jayfurmanek** [comment]
retest cpu-non-pip please

**Comment by jayfurmanek** [comment]
retest Ubuntu-GPU-multi please
retest cpu-non-pip please

**Review by rahulbatra85 — APPROVED** [review]

**Comment by jayfurmanek** [comment]
retest Ubuntu-GPU-multi please

**Review by i-chaochen — APPROVED** [review]

**Comment by jayfurmanek** [comment]
retest Ubuntu-GPU-multi please
retest cpu-non-pip please

**Pull request merged**
