### PR TITLE
Develop upstream sync 200224

### PR DESCRIPTION
**Pull request by jerryyin**

### CODE REVIEW

**Comment by ROCm-Apps-Test** [comment]
Can one of the admins verify this patch?

**Comment by jerryyin** [comment]
retest rocm-xla please

**Comment by jerryyin** [comment]
retest rocm-xla please

**Comment by jerryyin** [comment]
@jeffdaily While I don't think the xla jitter on `token_xla_test` is nccl related, it does remind me that I should let you review about the conflict resolution on nccl build side. Could you double check 98187d0 (also as a FYI), and see if I'm making the right move on resolving `nccl_configure.bzl`? Looks like upstream is being working on it most recently. We might/not need to do something additional to `nccl_configure.bzl`.

**Comment by jeffdaily** [comment]
I think we could even get rid of `and not enable_rocm(repository_ctx))` from ` third_party/nccl/nccl_configure.bzl`.  It's inserting a stub BUILD file to skip downloading and building NCCL if cuda is disabled or the platform is not linux.  For us, `not enable_cuda(repository_ctx)` == `enable_rocm(repository_ctx)`, so the rocm check seems redundant.

**Comment by jerryyin** [comment]
Thanks @jeffdaily. I reverted to original upstream version according to your suggestion.

**Pull request merged**
