### PR TITLE
Enable geam in single and double precision.

### PR DESCRIPTION
**Pull request by iotamudelta**

### CODE REVIEW

**Comment by whchung** [comment]
@iotamudelta is there a particular version of `rocBLAS` we should expect to enable this feature?

**Comment by iotamudelta** [comment]
@whchung I think this should work with the current one but it obviously works w/ the one in ROCm 1.8.2 (which we will anyways depend on if we merge the rocFFT PR).

**Comment by whchung** [comment]
The 1st check mark we are seeing today...

**Comment by whchung** [comment]
@iotamudelta I noticed even though we added rocblas_sgeam and rocblas_dgeam we don't really invoke them in `rocm_blas.cc`?

**Comment by iotamudelta** [comment]
Correct. In the CUDA case, they are used from the solver, I expect us to need to do the same.

**Pull request merged**
