### PR TITLE
Immediate Mode Integration to r1.15-rocm-enhanced

### PR DESCRIPTION
**Pull request by deven-amd**
@sunway513

### CODE REVIEW

**Comment by sunway513** [comment]
Thanks @deven-amd , let's watch for the following CI run:
http://ml-ci.amd.com:21096/job/tensorflow-upstream-rel1.15-enhanced-nightly/26/

**Comment by deven-amd** [comment]
@sunway513 

Please wait on merging this PR. I want to make a couple of minor tweaks to the default settings for how immediate mode is used....will push out a commit with those tweaks later today.

**Comment by deven-amd** [comment]
@sunway513 

pushed out a couple of new commits
 * first commit has a minor tweak which skips doing a profiling run when the number of algorithms returned by immediate mode is 1. When the number of algorithms returned is 1, it is by default the best one available, and doing a profiling run to determine the best algorithm (which TF does by default) is redundant. 
   * Combining this tweak with setting the env var `TF_ROCM_MIMIC_FIND_MODE=1` will result in the fastest startup time. Setting the env var `TF_ROCM_MIMIC_FIND_MODE=1` results in the rocm_dnn layer returning only one result in the vector returned by the call to GetMIOpenAlgorithms. 
 * second commit simply changes VLOG level of the immediate mode related info messages from -1 to 3, so that their dumping is no longer enabled by default.

**Comment by deven-amd** [comment]
I did some tf_cnn_benchmark runs with and without immediate mode, and I basically get the same performance in both cases. This is expected because both Find Mode and Immediate mode are expected to give the same "answer" for the best algorithm. Immediate Mode will probably be faster at "startup" but since the tf_cnn_benchmark measurement is an average of 100 batch runs, any improvement in "startup" will not show up in that measurement.

**Comment by deven-amd** [comment]
@sunway513 once you have done your perf measurements, and I have your thumbs up, I will 

* port the last two commits to develop-upstream
* file a PR to upstream immediate mode support

**Comment by sunway513** [comment]
Here's the new CI test:
http://ml-ci.amd.com:21096/job/tensorflow-upstream-rel1.15-enhanced-nightly/27/

**Comment by ROCm-Apps-Test** [comment]
Can one of the admins verify this patch?

**Comment by deven-amd** [comment]
@sunway513 , do we need this PR anymore? 

This PR was to add support for Immediate mode in `r1.15-rocm-enhanced`. Given that immediate mode will not be ready for prime-time atleast for the next couple of months, do we need to port support for it back to `r1.15-rocm-enhanced` branch?

**Comment by sunway513** [comment]
@deven-amd , right, we can close this PR now, thanks.

**Pull request closed without merging**
