### PR TITLE
Adding clang/18 to the list of include dirs

### PR DESCRIPTION
**Pull request by jayfurmanek**

### CODE REVIEW

**Comment by jayfurmanek** [comment]
retest Ubuntu-CPU please

**Review by i-chaochen — APPROVED** [review]

**Comment by i-chaochen** [comment]
I think we need to upstream this to XLA as well?

**Comment by jayfurmanek** [comment]
yes, but not yet. This is a change needed for ROCm 6.0. 
The clang17 update was for 5.7, so we can push that one

**Comment by i-chaochen** [comment]
So ROCm6.0 is from ROCm5.7 and there is no ROCm5.8?

**Comment by jayfurmanek** [comment]
Correct.

**Pull request merged**
