### PR TITLE
TF integration of rocTracer

### PR DESCRIPTION
**Pull request by eshcherb**
Rebased PR#107

### CODE REVIEW

**Comment by ROCm-Apps-Test** [comment]
Can one of the admins verify this patch?

**Comment by ROCm-Apps-Test** [comment]
Can one of the admins verify this patch?

**Comment by parallelo** [comment]
Jenkins:  okay to test

**Comment by parallelo** [comment]
Jenkins:  test this please

**Comment by whchung** [comment]
per discussion with @eshcherb , I'll amend this PR introducing new configure-time option to enable / disable integration logic of `rocTracer` so end users can build TF on ROCm before `rocTracer` is in ROCm proper. The default value would be to disable `rocTracer` integration logic.

**Comment by whchung** [comment]
Close this PR as it has been superseded by #260 . @eshcherb / @parallelo please help review and test it. Thanks.

**Pull request closed without merging**
