### PR TITLE
ROCm enable depthwise_conv_ops_test

### PR DESCRIPTION
**Pull request by jeffdaily**

### CODE REVIEW

**Comment by deven-amd** [comment]
the corresponding unit test is whitelisted...can you check if it passes in your local build, and if it does please remove it from the whitelist as well :)

**Comment by whchung** [comment]
@jeffdaily even the CI test result is a success I'm still closing this PR as the test itself is in the whitelist after all. please help address the comments from me and @deven-amd and reopen it.

**Comment by jeffdaily** [comment]
Removing `//tensorflow/python/kernel_tests:depthwise_conv_op_test` (`tensorflow/python/kernel_tests/depthwise_conv_op_test.py`) from the whitelist failed.  That test is trying to use the kernel `DepthwiseConv2dNative` labeled `cudnn_grouped_convolution` from `tensorflow/core/kernels/depthwise_conv_op.cc` line 489.  

The test that this PR is enabling is `//tensorflow/core/kernels:depthwise_conv_ops_test`.  The test is also failing, but because `tensorflow/core/kernels/ops_testutil.cc` returns with error `Requesting GPU on binary compiled without GOOGLE_CUDA`.  See https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/blob/develop-upstream/tensorflow/core/kernels/ops_testutil.cc.  _Should we ROCm enable this file?_

**Comment by jeffdaily** [comment]
I'll answer my own question.  Enabling ROCm in the above file would also require `hipMallocManaged`.  Since we don't support `hipMallocManaged` this test will never work.  Best to leave this PR closed for good.

In other news depthwise conv will be supported in MIOpen 1.5, so we should revisit the depthwise kernel and whitelist again after that release.

**Pull request closed without merging**
