### PR TITLE
Develop upstream sync 191209

### PR DESCRIPTION
**Pull request by jeffdaily**

### CODE REVIEW

**Comment by jeffdaily** [comment]
Only rocm-xla is failing.  There was one build error in `hlo_module_loader.cc` that is fixable.  Not sure how to root cause and fix the remaining 5 runtime errors.

- tensorflow/compiler/tests/conv_node_name_test_cpu/test.log
- tensorflow/compiler/tests/conv_node_name_test_gpu/test.log
- tensorflow/compiler/xla/service/gpu/tests/reduction_degenerate_dim_remover_test/test.log
- tensorflow/compiler/xla/service/gpu/tests/reduction_dimension_grouper_test/test.log
- tensorflow/compiler/xla/service/gpu/tests/reduction_layout_normalizer_test/test.log

**Comment by jeffdaily** [comment]
Two rocm-xla failures remain unchanged from prior commit.
- tensorflow/compiler/tests/conv_node_name_test_cpu/test.log
- tensorflow/compiler/tests/conv_node_name_test_gpu/test.log

One new failure after prior commit.
- tensorflow/compiler/xla/service/gpu/tests/gpu_kernel_tiling_test/test.log

**Comment by jerryyin** [comment]
Working on following unit tests:

- //tensorflow/compiler/tests:conv_node_name_test_gpu
- //tensorflow/compiler/tests:conv_node_name_test_cpu

**Comment by jeffdaily** [comment]
@jerryyin looks like this is the commit that caused the failures.

722fc02b3ffa6b272469fe4719deeb60d45fe08c

**Comment by jeffdaily** [comment]
The single XLA failure was 
```//tensorflow/compiler/mlir/tensorflow/tests/tf_saved_model:shapes_for_variables.py.test FAILED in 3 out of 3 in 18.1s```
But this is a known flaky test, or at least I've seen this be flaky in previous runs.

**Comment by deven-amd** [comment]
jenkins : retest rocm-xla please

**Pull request merged**
