### PR TITLE
Adjust crosstool wrapper to use -no-canonical-prefixes option

### PR DESCRIPTION
**Pull request by jayfurmanek**
Needed because of: https://github.com/llvm/llvm-project/commit/578a4716

### CODE REVIEW

**Comment by jayfurmanek** [comment]
retest gpu-pycpp please

**Comment by jayfurmanek** [comment]
retest cpu-pycpp please

**Comment by jayfurmanek** [comment]
retest gpu-pycpp please

**Comment by jayfurmanek** [comment]
retest Ubuntu-GPU-single please

**Comment by jayfurmanek** [comment]
retest Ubuntu-GPU-single please

**Comment by jayfurmanek** [comment]
retest Ubuntu-GPU-single please

**Comment by jayfurmanek** [comment]
retest Ubuntu-GPU-single please

**Comment by jayfurmanek** [comment]
retest Ubuntu-GPU-single please

**Comment by jayfurmanek** [comment]
retest Ubuntu-GPU-single please

**Comment by jayfurmanek** [comment]
retest Ubuntu-GPU-single please

**Comment by jayfurmanek** [comment]
retest Ubuntu-GPU-single please

**Review by i-chaochen — APPROVED** [review]

**Pull request merged**
