### PR TITLE
Add clang-16 to Docker files

### PR DESCRIPTION
**Pull request by draganmladjenovic**
Split from PR2192.

### CODE REVIEW

**Review by i-chaochen — APPROVED** [review]

**Comment by draganmladjenovic** [comment]
Retest Ubuntu-CPU please
Retest Ubuntu-GPU-single please
Retest continuous-integration/jenkins/pr-head please

**Comment by draganmladjenovic** [comment]
@i-chaochen  The continuous-integration/jenkins/pr-head does not have retest comment trigger?

**Comment by i-chaochen** [comment]
> @i-chaochen The continuous-integration/jenkins/pr-head does not have retest comment trigger?

haha :) you can click that magic button to rerun

**Comment by draganmladjenovic** [comment]
Retest Ubuntu-CPU please
Retest Ubuntu-GPU-single please

**Comment by draganmladjenovic** [comment]
@i-chaochen ThirdParty xla CI is blocking me from submitting the PR. I could disable the failing tests but CI is not filtering no_rocm tags. How should I proceed?

**Comment by i-chaochen** [comment]
> @i-chaochen ThirdParty xla CI is blocking me from submitting the PR. I could disable the failing tests but CI is not filtering no_rocm tags. How should I proceed?

You can ignore xla CI for now. Please go head if you can PASSED Ubuntu-GPU-single

**Pull request merged**
