### PR TITLE
enable self_adjoint_eig op

### PR DESCRIPTION
**Pull request by micmelesse**
This pr enables the self_adjoint_eig_op.

### CODE REVIEW

**Comment by micmelesse** [comment]
@stevenireeves Let me know if you are happy with pr and then we can merge. I will create the upstream pr afterwards.

**Review by stevenireeves — COMMENTED** [review]
Just a nit but can you fix the spacing in the wrapper.

**Comment by micmelesse** [comment]
@stevenireeves I have updated the spacing

**Review by stevenireeves — APPROVED** [review]
LGTM

**Pull request merged**
