### PR TITLE
Develop upstream sync 210913

### PR DESCRIPTION
**Pull request by reza-amd**

### CODE REVIEW

**Comment by reza-amd** [comment]
jenkins : retest Ubuntu-sanity please

**Comment by reza-amd** [comment]
jenkins : retest Ubuntu-sanity please

**Comment by reza-amd** [comment]
@okakarpa could you please take a look at the sanity job failure? It seems that the bare metal asks for ```sudo``` password. As far as I know, this should not happen.

**Comment by okakarpa** [comment]
> @okakarpa could you please take a look at the sanity job failure? It seems that the bare metal asks for `sudo` password. As far as I know, this should not happen.

@reza-amd  i made some changes on the node you shouldn't see the issue anymore

**Comment by reza-amd** [comment]
jenkins : retest Ubuntu-sanity please

**Comment by reza-amd** [comment]
@okakarpa it seems that it has a DNS issue now.

**Comment by okakarpa** [comment]
jenkins : retest Ubuntu-sanity please

**Comment by reza-amd** [comment]
jenkins : retest Ubuntu-GPU-single please

**Comment by reza-amd** [comment]
jenkins : retest Ubuntu-GPU-multi please

**Comment by reza-amd** [comment]
jenkins : retest Ubuntu-CPU please

**Comment by reza-amd** [comment]
jenkins : retest Ubuntu-CPU please

**Comment by reza-amd** [comment]
This weekly sync has a unit test failure for test ``` //tensorflow/python/kernel_tests:pooling_ops_test_gpu PoolingTest.testAvgPoolKernelSmallerThanStrid data_format='NHWC` data_type=tf.float16 use_gpu=True, v2=False```.

The error message for the failure is :
```Memory access fault by GPU node-2 (Agent handle: 0x39be380) on address 0x100000000. Reason: Page not present or supervisor privilege.```

After going through the commits, I discovered the root cause of this failure is the Eigen commit update specified in the following change:

https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/commit/34fcc9bd9e8e4429f8943751ceb733a5d9c79e52

**Comment by reza-amd** [comment]
jenkins : retest Ubuntu-CPU please

**Comment by reza-amd** [comment]
jenkins : retest Ubuntu-CPU please
jenkins : retest Ubuntu-GPU-multi please

**Pull request merged**
