### PR TITLE
Update llvm and pybind11 urls

### PR DESCRIPTION
**Pull request by apivovarov**
Update llvm and pybind11 urls

### CODE REVIEW

**Comment by ROCm-Apps-Test** [comment]
Can one of the admins verify this patch?

**Comment by ROCm-Apps-Test** [comment]
Can one of the admins verify this patch?

**Comment by ROCm-Apps-Test** [comment]
Can one of the admins verify this patch?

**Comment by ROCm-Apps-Test** [comment]
Can one of the admins verify this patch?

**Comment by whchung** [comment]
jenkins: ok to test

**Comment by deven-amd** [comment]
@apivovarov , what is the intent / reason for making this change?

ideally these changes should be submitted to the upstream TF repo, and they will get picked up by our fork via our weekly-syncs with the upstream TF repo

**Comment by apivovarov** [comment]
tensorflow-upstream fails because bezel can not download llvm and pybind11 using outdated URLs
The change was taken from the HEAD of tensorflow repo.
We can wait for the sync or merge the fix now

**Comment by apivovarov** [comment]
Why all CI links are not working?
```
HTTP ERROR 404
Problem accessing /job/develop-upstream-unit-tests/job/tensorflow-upstream-unit-tests-nvidia/1231/. Reason:

    Not Found
```

**Comment by apivovarov** [comment]
This PR changes are included to https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/pull/709 already

**Comment by sunway513** [comment]
Thanks @apivovarov , if this PR is part of #709 , we'll likely have it as part of `develop-upstream` branch by end of the week. 
To reiterate the comments from @deven-amd , we don't typically accept PRs other than ROCM-specific features. 
All the other changes shall be submitted to upstream tensorflow repo, then those would be propagated to this repo through weekly merges. 

> Why all CI links are not working?
> 
> ```
> HTTP ERROR 404
> Problem accessing /job/develop-upstream-unit-tests/job/tensorflow-upstream-unit-tests-nvidia/1231/. Reason:
> 
>     Not Found
> ```
To this question - the CI logs are not visible to the public. 
For contributors who need access to the CI logs, please firstly register on the Jenkins ([link](http://ml-ci.amd.com:21096/signup)), and then let us know.
We'll review the request and justification, then grant access accordingly.

**Pull request closed without merging**
