### PR TITLE
Fix MIOpen BN nan error in fp16

### PR DESCRIPTION
**Pull request by whchung**
Use fp32 for intermediate tensor and fp16 for input and output.

### CODE REVIEW

**Comment by whchung** [comment]
@ce1adon and @daniellowell , would the fix in MIOpen develop branch for this topic be included in the upcoming 1.5 release?

**Comment by daniellowell** [comment]
@whchung No, not for 1.5.

**Comment by daniellowell** [comment]
@whchung This is still in progress:
https://github.com/AMDComputeLibraries/MLOpen/issues/1121

**Comment by ce1adon** [comment]
@whchung @daniellowell 
A PR in miopen for this issue should be ready today. Do you expect it merge into miopen develop branch or 1.5.x branch?

**Comment by daniellowell** [comment]
@ce1adon Develop. Nothing but critical bug fixes in 1.5.x at this point.

**Comment by ce1adon** [comment]
@daniellowell 
Got. Thanks!

**Comment by whchung** [comment]
jenkins: retest this please

**Comment by whchung** [comment]
jenkins: retest this please

**Comment by whchung** [comment]
jenkins: retest this please

**Comment by whchung** [comment]
@daniellowell / @ce1adon since this PR doesn't really involve any API changes in MIOpen, I'll merge it after CI test. Earlier CI failures we saw in this PR were benign (CI node config issue).

**Pull request merged**
