### PR TITLE
Develop upstream update issue template

### PR DESCRIPTION
**Pull request by sunway513**
This PR updates the github issue submission templates and the environment collection script.

### CODE REVIEW

**Comment by whchung** [comment]
@sunway513 do we want to upstream changes here?

**Comment by sunway513** [comment]
@whchung We should, however, it won't help a lot before ROCm path can fully functional in the upstream.

**Comment by whchung** [comment]
Ok, up to you to decide when to submit then.

**Comment by sunway513** [comment]
Sure, will submit it after community builds up running on upstream.

**Pull request merged**
