### PR TITLE
Enable builds based on ROCM_TOOLKIT_PATH environment variable.

### PR DESCRIPTION
**Pull request by mvermeulen**
Allow ROCM_TOOLKIT_PATH variable to be pass if TF_ROCM and ROCM_TOOLKIT_PATH are both set.

Change ROCm bazel config file to replace hard-coded paths to /opt/rocm with rocm_toolkit_path.

In addition to these changes, the following should be done at the script used to build:
- Pass the ROCM_TOOLKIT_PATH variable to the configure, e.g. env ROCM_TOOLKIT_PATH=/opt/rocm-2.8.1
- Make sure PATH is set to find components in new location, e.g. PATH=/opt/rocm-2.8.1/opencl/bin:/opt/rocm-2.8.1/bin:/opt/rocm-2.8.1/hcc/bin:/opt/rocm-2.8.1/hip/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

### CODE REVIEW

**Comment by ROCm-Apps-Test** [comment]
Can one of the admins verify this patch?

**Comment by ROCm-Apps-Test** [comment]
Can one of the admins verify this patch?

**Comment by ROCm-Apps-Test** [comment]
Can one of the admins verify this patch?

**Comment by ROCm-Apps-Test** [comment]
Can one of the admins verify this patch?

**Comment by sunway513** [comment]
jenkins: ok to test

**Comment by sunway513** [comment]
LGTM, thanks @mvermeulen :-)
Let's run a set of tests to make sure if it's safe or not to merge in with CI stick with ROCm2.8. Then we can decide where to move next.

**Comment by mvermeulen** [comment]
The rocm_config.h.tpl file is interesting...

Looks like there is a pre-configured file also checked in and this header file gets used in the RocmRoot() routine.  I haven't found any callers for RocmRoot but agree this is something to identify and also fix...

**Comment by mvermeulen** [comment]
Updated rocm_config.h.tpl using similar pattern as done for CUDA.

**Comment by sunway513** [comment]
CI checks all passed, which indicates this PR won't cause regressions with ROCm2.8 base. 
Hence I'm going to merge it and ask the QA team to expand the coverage.

**Pull request merged**
